### ISSUE TITLE
Help in compiling NetHook2

### ISSUE THREAD

**Issue by knkitten** [SteamRE/SteamKit#1004]
Hello. I am a beginner and regular user. I am having difficulty building NetHook2. Further, strictly step by step instructions.

_"1. Execute SetupDependencies.cmd to automatically acquire the zlib and protobuf headers and libraries."_
Launched "SetupDependencies.cmd" using cmd. The whole process went smoothly. The "native-dependencies" directory has appeared, which contains 4 folders "protobuf-3.15.6", "protobuf-bins", "zlib-1.2.11", "zlib-bins". According to the message after installation in cmd, I understand that you need to work with the file "libprotobuf.vcxproj"? But how exactly?

_"2. Build with VS 2015 (the v140 toolset is required to link with libprotobuf correctly)."_
Installed Visual Studio 2019 (couldn't find 2015). I tried to open the file "libprotobuf.vcxproj", but what to do with it? How wrong would VS 2019 be to use?

Also tried downloading the ready-made dll library. Downloaded NetHook2.zip (203 KB) release from 5 Jul 2020 (SteamKit 2.3.0). But when executed in cmd "rundll32 NetHook2.dll, Inject" gave the following:

`CCrypto::SymmetricEncryptChosenIV = 0x791d8f10
Unable to find PchMsgNameFromEMsg.
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x0
CCMInterface::RecvPkt = 0x0
Unable to hook CWebSocketConnection::BBuildAndAsyncSendFrame: func scan failed.
Unable to hook CCMInterface::RecvPkt: func scan failed.`

Please, help. Your project is very cool, but there is no way I can work with it.

**Comment by yaakov-h** [comment]
VS2019 works, I guess we should update the docs.

That binary is incredibly old. Try downloading one from [the latest builds](https://github.com/SteamRE/SteamKit/actions/workflows/steamkit2-build.yaml?query=is%3Asuccess+branch%3Amaster).

**Comment by yaakov-h** [comment]
Docs fixed in c6d67ab.

**Comment by knkitten** [comment]
Thanks it seems I figured it out.

here is a **short summary** of what you need to do **to get** the **netnook2.dll** file

the first step is described earlier
I will describe **the second step** in more **detail** (I think it might help others):
after the first step your folder will look something like this
![image](https://user-images.githubusercontent.com/78342823/128548219-6d4e33df-f19f-4d70-aa40-c8358503949c.png)
where the **file we need is** highlighted in blue (**NetHook2.sln**)
then **double click on this file** (provided that you have **installed Microsoft Visual Studio 2019**, I can't exactly reproduce the build tools I need, but the environment suggested them automatically) 
a window like this will open
![image](https://user-images.githubusercontent.com/78342823/128548697-6c7c7080-dcec-4a31-8802-6250a341cea3.png)
as I understand it, you need to **select** the **Release** version **and click** on the **start** button (highlighted in blue)

![image](https://user-images.githubusercontent.com/78342823/128548868-5ea2cc59-29a8-4dcb-80a2-9c42e8687c63.png)
a new folder will appear in the original **folder** named **Release**

![image](https://user-images.githubusercontent.com/78342823/128548961-cdfd8f97-ddf2-4284-b6a1-fd11aae49fe5.png)
which **contains** our **compiled file** 

and it works fine without errors.
