### ISSUE TITLE
CryptoHelper.SymmetricDecrypt produces incorrect result on .NET 6.0

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#1007]
I'm currently experimenting with running my projects under .NET 6.0 (preview 6) and I've found quite huge regression in SK2 in regards to that, which I'm reporting in this issue.

Consider repro like that:

```csharp
private const string EncryptionKey = "zmkXyWQzRHiameIe";

private static string? Decrypt(string encryptedString) {
	if (string.IsNullOrEmpty(encryptedString)) {
		throw new ArgumentNullException(nameof(encryptedString));
	}

	byte[] key;

	using (SHA256 sha256 = SHA256.Create()) {
		key = sha256.ComputeHash(EncryptionKey);
	}

	byte[] decryptedData = Convert.FromBase64String(encryptedString);
	decryptedData = CryptoHelper.SymmetricDecrypt(decryptedData, key);

	return Encoding.UTF8.GetString(decryptedData);
}

private static string? Encrypt(string decryptedString) {
	if (string.IsNullOrEmpty(decryptedString)) {
		throw new ArgumentNullException(nameof(decryptedString));
	}

	byte[] key;

	using (SHA256 sha256 = SHA256.Create()) {
		key = sha256.ComputeHash(EncryptionKey);
	}

	byte[] encryptedData = Encoding.UTF8.GetBytes(decryptedString);
	encryptedData = CryptoHelper.SymmetricEncrypt(encryptedData, key);

	return Convert.ToBase64String(encryptedData);
}

private static int Main() {
	const string decrypted = "qF7Sr1RfOZ9K9bfTXfl3";

	Console.WriteLine(decrypted);

	var encrypted = Encrypt(decrypted);

	Console.WriteLine(encrypted);

	var decrypted2 = Decrypt(encrypted);

	Console.WriteLine(decrypted2);

	return decrypted == decrypted2 ? 0 : 1;
}
```

This code produced following (example) output on `net48` and `net5.0` targets:

```
qF7Sr1RfOZ9K9bfTXfl3
XC5d5iL8ZoejDjr5IaQeV1cpcHvd3Wr3vojo8yBI9snRwcADq3xb2TQ5Cz3nOBGd
qF7Sr1RfOZ9K9bfTXfl3
(exit code 0)
```

And following on `net6.0`:

```
qF7Sr1RfOZ9K9bfTXfl3
npQePt1w6VAiTRS9NCbxIeBpvITRNHujrH0niQ/8XKDmiwhbUUVVbGxSWfjT4SpC
qF7Sr1RfOZ9K9bfT
(exit code 1)
```

Not all inputs are corrupted, it seems that only those of particular length/structure are. Give it a try with my values if in doubt.

I didn't dig deep enough to find the root cause of this culprit, but it's definitely connected with .NET 6.0. It could have something common with https://github.com/SteamRE/SteamKit/issues/1005 or could be even the same issue in a different place.

In any case, I believe that it'd be worthy to at least add unit test verifying the above as a bullet-proof for .NET 6.0 in case we don't have such test yet. Originally I hope that whatever .NET folks have broken will be corrected, but I'm afraid that it'll bite us in the bottom part and SK2 code will require a correction in regards to that.

Thank you in advance for taking into account this issue.

/cc @xPaw @yaakov-h

**Comment by azuisleet** [comment]
Is this https://github.com/SteamRE/SteamKit/pull/1006?

**Comment by JustArchi** [comment]
Could be.

**Comment by JustArchi** [comment]
It's definitely in different place though. I don't have any exception here and I'm not dealing with connection or packets per-se.

**Comment by xPaw** [comment]
It is that PR, test it with that patch.

**Comment by JustArchi** [comment]
Yep, looks like the patch corrects this one. Thanks @xPaw 

I'll close this in favour of https://github.com/SteamRE/SteamKit/pull/1006
