### ISSUE TITLE
[NetHook2]: Websocket hooks don't working

### ISSUE THREAD

**Issue by SasukeK93** [SteamRE/SteamKit#1013]
### What did you expect to happen?

Websocket functions sucessfully detoured

### Instead of that, what actually happened?

func scan failed

### Relevant log output

```plain
Initializing NetHook2...
Built at 2021-08-08 04:19:42 +00:00 from b2ff41e (2021-08-08 14:16:23 +1000)
CCrypto::SymmetricEncryptChosenIV = 0x6caab710
Unable to find PchMsgNameFromEMsg.
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x0
CCMInterface::RecvPkt = 0x0
Unable to hook CWebSocketConnection::BBuildAndAsyncSendFrame: func scan failed.
Unable to hook CCMInterface::RecvPkt: func scan failed.
```

### Additional Information

Tested on srcds from Counter Strike : Global Offensive

ServerVersion=1306
PatchVersion=1.37.9.7
SourceRevision=6691253
VersionDate=Jul 27 2021
VersionTime=14:29:51

**Comment by SasukeK93** [comment]
Solved ^^

Function : WebSocketConnection::BBuildAndAsyncSendFrame
Signature : \x55\x8B\xEC\x83\xEC\x74\xA1\x10\xA8\xC0\x38\x53
Mask : xxxxxxx????x

Function : CCMInterface::RecvPkt
Signature : \x55\x8B\xEC\x81\xEC\x00\x00\x00\x00\xA1\x00\x00\x00\x00\x53\x56\x8B\xD9\x83\x38\x00\x57\x89\x5D\xF8\x75\x04\x33\xC0\xEB\x14\x8D\x45\xE4
Mask : xxxxx????x????xxxxxxxxxxxxxxxxxxxx

**Comment by yaakov-h** [comment]
I can't reproduce this. The latest NetHook2 definitions work properly against the latest Steam build (20th July).

Are you in the Steam Client Beta program?

**Comment by SasukeK93** [comment]
No I'm not.

However CSGO dedicated was updated a few days ago and currently the NetHook definitions work perfectly.
