### ISSUE TITLE
[Bug]: Can not set CGCStorePurchaseInit_LineItem in k_EMsgGCStorePurchaseInit

### ISSUE THREAD

**Issue by Skr1pt** [SteamRE/SteamKit#1023]
### What did you expect to happen?

I want set line_items values to k_EMsgGCStorePurchaseInit request

### Instead of that, what actually happened?

line_items in k_EMsgGCStorePurchaseInit request have only getter 
Example: 
```csharp
 [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<CGCStorePurchaseInit_LineItem> line_items { get; } = new global::System.Collections.Generic.List<CGCStorePurchaseInit_LineItem>();
```

### Which operating system are you running on?

Windows

### Which .NET Runtime are you running on?

.NET Framework

### Version

4.5

### Example Code

```csharp
var clientMsgProtobuf0 =
          new ClientGCMsgProtobuf<CGCStorePurchaseInit_LineItem>(
                     (uint)EGCItemMsg.k_EMsgGCStorePurchaseInit)
          {
              Body =
                    {
                        item_def_id = 4670,
                        quantity =1,
                        cost_in_local_currency = 99,
                        purchase_type = 0
                    }
          };
            _gameCoordinator.Send(clientMsgProtobuf0, CsgoAppid);
            var clientMsgProtobuf =
                new ClientGCMsgProtobuf<CMsgGCStorePurchaseInit>(
                    (uint)EGCItemMsg.k_EMsgGCStorePurchaseInit)

                {
                    Body =
                    {
                        country = "",
                        language = 6,
                        currency = 3,


                    }
                };

            _gameCoordinator.Send(clientMsgProtobuf, CsgoAppid);
```

### Additional Information

How to set LineItem values to EMsgGCStorePurchaseInit body manually?

**Comment by JustArchi** [comment]
Why do you need a setter for this? You have initialized `List` there, which you can `Clear()` (shouldn't be needed, it's empty by default), `Add()` and `AddRange()` to, what is the problem in adding objects to it rather than re-initializing from a constructor?

**Comment by Skr1pt** [comment]
> Why do you need a setter for this? You have initialized `List` there, which you can `Clear()` (shouldn't be needed, it's empty by default), `Add()` and `AddRange()` to, what is the problem in adding objects to it rather than re-initializing from a constructor?
> 
> Proto members do not allow setters in `repeated` (collection) types, because the default value for them is being empty, and their re-initialization is entirely pointless.

![image](https://user-images.githubusercontent.com/44027401/134992683-d76ced59-a183-4dc8-8154-f0095c3fe3a3.png)
I must set line_items param, but it is read-only
Can u provide simple example with this method?

**Comment by wangxingzhen** [comment]
> > Or you can also use fancy C# syntax and write in your line `line_items = { ... }` which calls `Add()` under the hood. Not sure if your .NET Framework 4.5 is fresh enough for that syntax though.
> 
> thank you my friend, I am from ukrainian village and dont understand with first time, (braindead cuz drink vodka every day from 10 years)

hi bro,Now it is 2024, can this method still work? I want to in game purchase keys

**Comment by Skr1pt** [comment]
> > > Or you can also use fancy C# syntax and write in your line `line_items = { ... }` which calls `Add()` under the hood. Not sure if your .NET Framework 4.5 is fresh enough for that syntax though.
> > 
> > 
> > thank you my friend, I am from ukrainian village and dont understand with first time, (braindead cuz drink vodka every day from 10 years)
> 
> hi bro,Now it is 2024, can this method still work? I want to in game purchase keys

yes, its working if item is in the store

**Comment by wangxingzhen** [comment]
> > > > Or you can also use fancy C# syntax and write in your line `line_items = { ... }` which calls `Add()` under the hood. Not sure if your .NET Framework 4.5 is fresh enough for that syntax though.
> > > 
> > > 
> > > thank you my friend, I am from ukrainian village and dont understand with first time, (braindead cuz drink vodka every day from 10 years)
> > 
> > 
> > hi bro,Now it is 2024, can this method still work? I want to in game purchase keys
> 
> yes, its working if item is in the store

You just saved me a ton of time!  You're my hero!
