### ISSUE TITLE
New Dota2 Specializations 

### ISSUE THREAD

**Issue by alainhb2000** [SteamRE/SteamKit#1122]
### What problem is this feature trying to solve?

I've found new SO types, but i don't have any info about them
codes: 
2013
2014
2015
2016

i suposed that this are the types:
UNKNOWN = 2013
SERVER_LOBBY = 2014, //CSODOTAServerLobby
STATIC_LOBBY = 2015, //CSODOTAStaticLobby
SERVER_STATIC_LOBBY = 2016 //CSODOTAServerStaticLobby

If anyone can confirm this.

### How would you like it to be solved?

Add to Dota2SOHelper.cs

### Have you considered any alternative solutions

No

**Comment by yaakov-h** [comment]
This was done in #1123, though not autoclosed at the time.
