### ISSUE TITLE
Missing EEconTradeResponse = 19

### ISSUE THREAD

**Issue by BlueRaja** [SteamRE/SteamKit#114]
Our bot just got an `EEconTradeResponse = 19` response, which is [missing from the enum](https://github.com/SteamRE/SteamKit/blob/c0055a47abf096f9d53309122d7f51aae77f9b4d/SteamKit2/SteamKit2/Base/Generated/SteamLanguage.cs#L2586).

The problem was that the other user _(not the bot)_ could not trade because of Steam Guard restrictions.  When the other user attempted to trade the bot _(which is **not** situation in which the response was 19)_, he saw the following message:

> You must have had Steam Guard enabled for at least 15 days before you can participate in a trade.

**Comment by psychonic** [comment]
While 19 may have existed at one time, it does not appear to at this time. However, many more are documented now.
