### ISSUE TITLE
[Bug]: Can't create KeyValue with non-string value type

### ISSUE THREAD

**Issue by SamusAranX** [SteamRE/SteamKit#1140]
### What did you expect to happen?

I expected to be able to wrap a non-string value in a `KeyValue` instance.

### Instead of that, what actually happened?

I'm only able to wrap nullable strings in `KeyValue` instances.

### Which operating system are you running on?

Windows

### Which .NET Runtime are you running on?

.NET Core or .NET 5 or higher.

### Version

6.0.401

### Example Code

```csharp
var kv = new KeyValue("0");
// this won't compile because this is not a nullable string
kv["appid"] = new KeyValue { Value = 3826460162 }; 
```

### Additional Information

I'm trying to use SteamKit2 to reconstruct a shortcuts.vdf file but I'm not getting very far. `KeyValue` has a lot of convenience methods for reading various value types, but apparently there's nothing to help me if I want to do the reverse. I tried several ways of building strings that encapsulate integers but somehow, I can't get it right. Having similar convenience methods would be much appreciated.

**Comment by xPaw** [comment]
Keyvalues only have strings, this isn't a bug. The int type comes from type guessing from strings during parsing.

**Comment by xPaw** [comment]
Right, you mean binary keyvalues, steamkit indeed doesn't support any other types for that.

https://github.com/SteamRE/SteamKit/blob/111054ec16747ef6bc03137b41f4fc3e185a9619/SteamKit2/SteamKit2/Types/KeyValue.cs#L746-L751

You can use https://github.com/SteamDatabase/ValveKeyValue which supports types.
