### ISSUE TITLE
Implement an API for CMsgClientReadMachineAuth

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#115]
@Netshroud, get on it

**Comment by VoiDeD** [comment]
I think I missed the discussion on IRC about this. Are the Steam servers requesting reads for sentry files now?

**Comment by xPaw** [comment]
Not yet, but we're futureproofing.

**Comment by xPaw** [comment]
There's probably no reason to keep this in a milestone, as far as I know Valve still isn't using this.

**Comment by yaakov-h** [comment]
I’m tempted to shove it under a “foresight” or “toldyaso” tag.

**Comment by xPaw** [comment]
Reopen when Valve actually uses this :)
