### ISSUE TITLE
what is the sessionkey's  work style

### ISSUE THREAD

**Issue by gyn7561** [SteamRE/SteamKit#117]
Sorry for my poor english. :)
When i read souce code,gamecoordinator's packet encrypted with seesionkey.but i didn't find any code send sessionkey to server.when program receive packet,that packet can be decrypted with same sessionkey.
Thank you for reading my question. :) sorry for my poor english....

**Comment by Netshroud** [comment]
Game Coordinator communications go through the CM Server. The very first thing that Steam/SteamKit sends to a CM Server is the encrypted session key.

See https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/CMClient.cs#L440 for implementation details.

SteamKit then sets the session key on the `Connection` object(s), which uses the key to decrypt incoming messages and encrypt outgoing messages.

What are you trying to achieve?

**Comment by gyn7561** [comment]
thank you!I try to catch Dota game packet with sharpwcap and use steamkit analyse protobuf packet.
thank you very much!
