### ISSUE TITLE
[Bug]: Fails to init SteamClient in maui framework at Android Runtime

### ISSUE THREAD

**Issue by OnRaptor** [SteamRE/SteamKit#1170]
### What did you expect to happen?

No exception thrown

### Instead of that, what actually happened?

Error

### Which operating system are you running on?

Other

### Which .NET Runtime are you running on?

.NET Core or .NET 5 or higher.

### Version

6.0

### Relevant log output

```shell
System.UnauthorizedAccessException
  Message = Access to the path '/proc/stat' is denied.
```

### Example Code

```csharp
private async void Steam_Clicked(object sender, EventArgs e){
   SteamClient steamClient = new SteamClient();
//...
```

### Additional Information

I found that problem with Process.StartTime in SteamClient constructor. It doesn't work properly on android system

**Comment by OnRaptor** [comment]
As temporary solution i edit SteamClient constructor, follow:

**Comment by yaakov-h** [comment]
`Process.StartTime` is only marked as unsupported on iOS and tvOS, so I expect it should either work in Android, or .NET / MAUI is not annotated correctly.

Can you please raise this with https://github.com/dotnet/runtime first?
