### ISSUE TITLE
Missing clan rank info

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#118]
Hi.

I couldn't find any way to get clan rank of a given steamID, even if I call ```requestFriendInfo()``` with ```EClientPersonaStateFlag.ClanInfo | EClientPersonaStateFlag.ClanTag``` flags. Also, ```onClanState()``` doesn't return members as well.

Is it possible to add members info either to request or onClan callback? I can see that we already have announcements and other misc info. All I need is a list of ```SteamID```s, preferably with  a ```isAdministrator```, ```isModerator``` and ```isMember``` booleans.

In case it's already possible with any already existing method, please guide me to the right track.

Thank you in advance!

**Comment by JustArchi** [comment]
I also tried to specify my own handler but getOfficers() returns "Timeout" as the result for me.

```
    class ArchiHandler : ClientMsgHandler {
        public class OnGetClanOfficersCallback : CallbackMsg {
            public EResult Result { get; private set; }

            internal OnGetClanOfficersCallback(EResult res) {
                Result = res;
            }
        }

        public void getClanOfficers(SteamID clanID) {
            var request = new ClientMsgProtobuf<CMsgClientAMGetClanOfficers>(EMsg.ClientAMGetClanOfficers);
            request.Body.steamid_clan = clanID;
            Client.Send(request);
        }

        public override void HandleMsg(IPacketMsg packetMsg) {
            switch (packetMsg.MsgType) {
                case EMsg.ClientAMGetClanOfficersResponse:
                    handleClanOfficersResponse(packetMsg);
                    break;
            }
        }

        private void handleClanOfficersResponse(IPacketMsg packetMsg) {
            var response = new ClientMsgProtobuf<CMsgClientAMGetClanOfficersResponse>(packetMsg);
            EResult result = (EResult)response.Body.eresult;
            Console.WriteLine("archiTest: {0}", result);
            Client.PostCallback(new OnGetClanOfficersCallback(result));
        }
    }
```

**Comment by VoiDeD** [comment]
This one is a bit tricky to implement due to the way the SteamFriends handler handles caching of persona state (we don't bucket users into their SteamID sources as steamclient does, so it's difficult to get information about users in a given clan.

However, your handler should be working correctly. In my tests, an EResult of `Timeout` appears to be normal, the message is still populated with the officer count, and Steam still sends down many PersonaState messages for each of the officers/moderators.

If you handle `PersonaStateCallback`, check to ensure the `SourceSteamID` matches the SteamID of the clan you're requesting officers for, and then the `ClanRank` should be populated with the information you're looking for.

**Comment by JustArchi** [comment]
Thank you for the tips, I really appreciate that!

Indeed, it makes sense, I just considered my code as bad due to misleading "Timeout" EResult, I'll re-evaluate this after I find some time (about a week as I'm busy lately).

Thanks to you and the whole team for what you've done, SteamKit is awesome!

**Comment by JustArchi** [comment]
Thanks a ton @VoiDeD, indeed it worked as you described. After executing above ```getClanOfficers()``` method I've received all data that I wanted in ```OnPersonaState``` callback :+1:

If anybody else would need something like this, then you can do it like that:
```
        private static void OnPersonaState(SteamFriends.PersonaStateCallback callback) {
            if (callback != null) {

                SteamID steamID = callback.FriendID;
                SteamID sourceSteamID = callback.SourceSteamID;
                EClanRank clanRank = (EClanRank) callback.ClanRank;

                if (sourceSteamID.IsClanAccount) {
                    switch (clanRank) {
                        case EClanRank.Owner:
                        case EClanRank.Officer:
                        case EClanRank.Moderator:
                            lock (steamChatAdminsLock) {
                                log("Adding " + steamID + " to " + sourceSteamID + " as " + clanRank);
                                // You can do anything you want here
                            }
                            break;
                    }
                }
            }
        }
```

Thanks once again! :+1:
