### ISSUE TITLE
Why is there no setter for Servers on CMClient?

### ISSUE THREAD

**Issue by paralin** [SteamRE/SteamKit#120]
It would make sense to be able to serialize the Server List callback and later load that data and use it as the initial CM server list for a new Steam Client. At the moment the setter is private, consider making it public too? Or at least adding a public method to do this?

**Comment by Netshroud** [comment]
Check out the [smart-server-list](https://github.com/SteamRE/SteamKit/tree/smart-server-list) branch. I'm working on this, among other things.

In the meantime, you can hold onto the CM list yourself and use `SteamClient.Connect(IPEndPoint)`.

**Comment by VoiDeD** [comment]
A `SteamClient` instance will handle the Server List callback and add the servers to the list. As Netshroud said though, you can use this list to get an endpoint to feed to Connect.

**Comment by paralin** [comment]
Okay, so this stuff is being rethought by @Netshroud right now. My concern @VoiDeD was not for updating the servers list during the operation of a SteamClient but to update it with a newer cached server list stored externally. 

For now I'll just use my own logic to select a server to connect to. Thanks!

**Comment by Netshroud** [comment]
Closing as this is now possible.
