### ISSUE TITLE
[Solved] Client keeps failing. Please help me.

### ISSUE THREAD

**Issue by VictoriaBloss** [SteamRE/SteamKit#121]
Hii, I'm having trouble connecting to Steam's system using SteamKit2. It seems I'm always receiving a failure response no matter what I do.

I tried analyzing the game's packets with NetHook2 and could not find anything that I'm not already doing. However, I'm probably missing something...

Does SteamKit2 not support interfacing with this section of Steam's network? I'm very confused... please help me!! Thanks in advance.

~V♥

**Comment by Netshroud** [comment]
Assuming `chat_room_enter_response` is an `EChatRoomEnterResponse`, 2 is `DoesntExist`. 

I'll play around with it a little later and see if I can reproduce this.

**Comment by VictoriaBloss** [comment]
Yeah! That's what is so confusing! I have a separate project which runs on Steamworks and I'm able to join the lobby using the exact same lobby id, so it definitely exists. Maybe I'm sending the steam_id_lobby incorrectly?

**Comment by Netshroud** [comment]
Figured it out. You need to set `joinLobby.ProtoHeader.routing_appid` to `730`.

Interestingly, that's the first time I've seen `routing_appid` used.

**Comment by VictoriaBloss** [comment]
Thank you so much!! You saved my day.
