### ISSUE TITLE
[Bug]: SteamUserStats.GetNumberOfCurrentPlayers() does not make request to Steam Network

### ISSUE THREAD

**Issue by lucaswalter** [SteamRE/SteamKit#1214]
### What did you expect to happen?

I am writing a simple program which users `SteamUserStats.GetNumberOfCurrentPlayers()` to try and fetch the number of concurrent players for a given game.

In my application, I am able to successfully connect to the Steam Network and Login. Once authenticated, I execute a request like the snippet below and would expect to get the number of players back _(or some sort of error code / network activity)_.
```
const uint dota2AppId = 570;
var userStats = await _steamUserStats.GetNumberOfCurrentPlayers(dota2AppId);
            
_logger.LogInformation("Dota 2 User Stats: {0}", userStats);
```

### Instead of that, what actually happened?

Instead, it appears like there is no network request being made at all. I can confirm that:

- My application is actually calling `SteamUserStats.GetNumberOfCurrentPlayers()` through a breakpoint when debugging
- The client is connected to the Steam network when attempting to make this call
- My application is continuously attempting to execute callbacks via a loop calling `_manager.RunWaitCallbacks(TimeSpan.FromSeconds(1)); `

**Other Observations**

- My application (and the minimal repro) have `DebugLog.Enabled = true;` as well as a listener writing to the console log. After calling `SteamUserStats.GetNumberOfCurrentPlayers()`, there are no log entries written by the listener.

### Which operating system are you running on?

macOS

### Which .NET Runtime are you running on?

.NET Core or .NET 5 or higher.

### Version

.NET 7

### Relevant log output

```shell
Log sample from the minimal repro example which shows successful connection and attempt to get user stats.

info: Program[0]
      [SteamKit] - ServerList: Resolving server list
info: Program[0]
      [SteamKit] - ServerList: Server list provider had no entries, will query SteamDirectory
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
info: Program[0]
      [SteamKit] - ServerList: Resolved 200 servers
info: Program[0]
      [SteamKit] - ServerList: Next server candidate: 162.254.197.39:27018 (Tcp)
info: Program[0]
      [SteamKit] - ed594e2ff53c40e2a6e5ce5b35f0650d/TcpConnection: Connecting to 162.254.197.39:27018...
info: Program[0]
      [SteamKit] - ed594e2ff53c40e2a6e5ce5b35f0650d/TcpConnection: Connected to 162.254.197.39:27018
info: Program[0]
      [SteamKit] - ed594e2ff53c40e2a6e5ce5b35f0650d/EnvelopeEncryptedConnection: Got encryption request. Universe: Public Protocol ver: 1
info: Program[0]
      [SteamKit] - ed594e2ff53c40e2a6e5ce5b35f0650d/EnvelopeEncryptedConnection: Encryption result: OK
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
info: SteamKit.Repro.SteamService[0]
      Connected to Steam network. Logging in...
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
info: SteamKit.Repro.SteamService[0]
      Successfully logged on
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
info: SteamKit.Repro.SteamService[0]
      Attempting to fetch Dota 2 User Stats...
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
info: SteamKit.Repro.SteamService[0]
      Executing Steam Callbacks...
```

### Example Code

```csharp
Git repository with minimal example that reproduces the issue: https://github.com/lucaswalter/SteamKit-GetNumberOfCurrentPlayers-Repro
```

### Additional Information

Git repository with minimal example that reproduces the issue: https://github.com/lucaswalter/SteamKit-GetNumberOfCurrentPlayers-Repro

**Zip file of code minimal repro example as well**
[Uploading SteamKit-GetNumberOfConcurrentPlayers.zip…]()

**Comment by yaakov-h** [comment]
It works for me if I log in with an actual account.

It seems to me that the problem here isn't that SK2 isn't making a request to the network, but that the servers aren't responding to the request.

This is somewhat expected when you use anonymous login, and not every function is available to anonymous accounts, and Steam is more than happy to ignore messages that it doesn't expect.

**Comment by lucaswalter** [comment]
Thanks a ton @yaakov-h — A bit embarrassed I didn't try that earlier. Hopefully your note can help anyone else facing a similar issue.
