### ISSUE TITLE
Is it possible to run multiple games at once with SteamKit?

### ISSUE THREAD

**Issue by NewbTheGamer2** [SteamRE/SteamKit#122]
Hai
So yes, I am an idler - I idle on games to gain hours. Since I don't want my computer to die early/use so many resources at once, I was thinking if it's possible to run multiple games at once via SteamKit.

Thanks,
~Newb

**Comment by VoiDeD** [comment]
This isn't exactly the SteamBot repo, but yes, the `CMsgClientGamesPlayed` message uses a list of games that can be populated with multiple appids.

Whether or not that will actually grant you more gameplay hours today (it did in the past) I can't answer.

**Comment by NewbTheGamer2** [comment]
How would I format the games list for the SteamKit?

**Comment by Netshroud** [comment]
An array of `CMsgClientGamesPlayer.GamePlayed` (see [the definition](https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L206)).

As far as I know the only mandatory field on that object is `game_id`.

**Comment by WildCard65** [comment]
Mind providing an example so I can help @NewbTheGamer2 in integrating it with his steambot. I have a rough idea how, just need to make sure it's correct.

**Comment by Netshroud** [comment]
https://github.com/SteamRE/SteamKit/blob/master/Projects/DotaMatchRequest/DotaMatchRequest/DotaClient.cs#L132-141 but with multiple GamePlayed objects added to the message body.

**Comment by WildCard65** [comment]
Ya. I editted my reply stating I found that line in SteamBot I originally missed.

**Comment by rishav394** [comment]
Why are all the DotaMatchRequest links broken?

**Comment by yaakov-h** [comment]
DotaMatchRequest was moved into the Samples folder a while ago.
