### ISSUE TITLE
Remove ICallbackMsg.Handle<T>()

### ISSUE THREAD

**Issue by Netshroud** [SteamRE/SteamKit#124]
We provide two ways of handling callbacks, but one way is "preferred" (`CallbackMgr`) and one way is not (`Handle<T>`).

It seems like many consumers are using the non-preferred way, but then using it in such a way that they should have used `CallbackMgr` instead, i.e. something resembling the following

    msg.Handle<SteamClient.DisconnectedCallback>(cb =>
    {
        OnDisconnected(cb);
    };

We should phase out `Handle<T>`.

Timeline:

1. Add `ObsoleteAttribute` with a deprecation warning for next minor release (1.6.4 [1])
2.  Remove entirely for the next major release (1.7.0)

[1]: Not 1.6.3, as consumers should be able to pick up the reliability improvements in `TcpConnection` without picking up this deprecation at the same time.

**Comment by VoiDeD** [comment]
:+1:

**Comment by BlueRaja** [comment]
Why not combine the advantages of the two approaches and introduce syntax like `manager.Handle<SteamClient.ConnectedCallback>( OnConnected );`?

`new Callback<SteamClient.ConnectedCallback>( OnConnected, manager );` is non-intuitive and non-idiomatic C# code - you should basically _never_ be creating a new instance without assigning it to something.

**Comment by Netshroud** [comment]
It's also not obvious that `manager.Handle<T>` would set up an ongoing action to be called continually.

I do agree that the callback constructor is non-intuitive, myself I usually do `new Callback<T>(...)` and then call `CallbackMgr.Register`.

It's not so much a callback as a subscription to callbacks, but then we'd be getting into Reactive Extensions territory (or similar) which is rather confusing for beginners to adopt.

One option would be to make `Callback` internal, and create `Subscribe`/`Unsubscribe` methods on `CallbackMgr`. That way you only ever deal with the `CallbackMgr` directly, not indirectly (i.e. the `Callback<T>` constructor doing the interaction for you, which is not visible from the external API). The naming would also make it obvious that the `Action<TCallback>` could (and likely will) be called multiple times.

What do you think of that, or do you have any alternative suggestions?

**Comment by BlueRaja** [comment]
Yes, I agree naming it `Subscribe` instead of `Handle` is better.  Is there a reason regular C# events aren't an option _(other than their generally cruddy syntax)_?

**Comment by Netshroud** [comment]
They're an option, but given the amount of events we have it makes it much more work. For each one we would need:
1. To Change (or duplicate, for backwards compatibility) Callback to EventArgs.
2. The Event itself
3. A Thread-safe asynchronous event caller

We would also lose consumer control over what thread the callbacks are executed on, and possibly guaranteed ordering - I'm not sure, would need to do more research.

**Comment by VoiDeD** [comment]
>new Callback<SteamClient.ConnectedCallback>( OnConnected, manager ); is non-intuitive and non-idiomatic C# code - it's not obvious at all that the Callback won't immediately be collected (or why you're creating a new Callback instance at all).

It's the result of the early design of SteamKit: to emulate the original reference implementation (that implementation being Valve's steamclient library).

The callback queue, the callback manager, callback objects, and the related public APIs are all a result of copying the existing design.

>We would also lose consumer control over what thread the callbacks are executed on, and possibly guaranteed ordering - I'm not sure, would need to do more research.

This is essentially the biggest issue. With the `CallbackMgr` mechanism you get absolute certainty what thread a callback handler will be executed on. Other alternatives are deeply tied into the synchronization method being used (Form.Invoke for WinForms, a Dispatcher for WPF, SynchronizationContext for TPL).

It's likely a lot cleaner to leave it as-is and make consumers evaluate which thread they want to execute callbacks on, and it works with the existing signaling machinery around the callback queue.

I do like the idea of exposing a static `Callback<T>.Subscribe( func, mgr )` or `mgr.Subscribe<T>( func)`, however. It would be an API that is definitely much more clear in its intentions.

**Comment by Netshroud** [comment]
Notes from IRC discussion: the `better-callback-api` branch is a good start, but we can't remove the current best practice (`new Callback<T>( Handler, manager )`) for a while. We'll deprecate soon via `ObsoleteAttribute`, but won't actually remove for 12 months after deprecation.

----

I'll try get the new APIs in by 1.6.4 so that anyone using `Handle<T>` can migrate to (`Subscribe`) immediately, and consumers using `new Callback<T>` can also begin migration but will have longer to migrate.

i.e.
1.6.4:
* Deprecate `Handle<T>`
* Deprecate `new Callback`
* Deprecate `CallbackMgr.Register`
* Add `CallbackMgr.Subscribe`

1.7.0:
* Remove `Handle<T>`

Some release 12 months later:
* Remove `new Callback`
* Remove `CallbackMgr.Register`

**Comment by WildCard65** [comment]
I guess I'm going to need to keep an eye on commits that go for this issue since I'm mostly the one that gets Jessecar96/SteamBot to even use the latest SteamKit2 version.

**Comment by Netshroud** [comment]
If you can compile without warnings (without having disabled warnings :smile:) on master, you should be future-proof. If not, it should be a simple conversion.

**Comment by WildCard65** [comment]
@Netshroud SteamBot won't be able to use the new api until SteamKit 1.6.4 is released.

**Comment by Netshroud** [comment]
There technically won't be a new API to use until SteamKit 1.6.4 is released (but you can prepare).

I'm hoping to release 1.6.4 soon.

**Comment by WildCard65** [comment]
@Netshroud Well, SteamBot uses Nuget to grab SteamKit so until Nuget has the binaries for 1.6.4, I want to keep SteamBot compilable(without errors/warnings) until then.

**Comment by VoiDeD** [comment]
Resolved via e97e655.
