### ISSUE TITLE
[Bug]: Auto disconnected after some period of time

### ISSUE THREAD

**Issue by ExistentialDysfunction** [SteamRE/SteamKit#1257]
### What did you expect to happen?

I get automatically disconnected from steam after some period of time while trying to idle some game hours. Not sure if it's a bug, but seems like one to me.

### Instead of that, what actually happened?

---

### Which operating system are you running on?

Windows

### Which .NET Runtime are you running on?

.NET Framework

### Version

7

**Comment by ExistentialDysfunction** [comment]
EDIT: I made a multithreaded steam game hours idling bot and in 7-8 hours all bots got disconnected and logged off with the following error: Unable to logon to Steam: 0 / 1

I have implemented auto reconnect logic, but this error is unknown to me, would appreciate some help here.

**Comment by xPaw** [comment]
I'm gonna close this because there's no actionable information or repro here. Other bots have no such issues (including mine).
