### ISSUE TITLE
C project

### ISSUE THREAD

**Issue by armaldio** [SteamRE/SteamKit#126]
How to use SteamKit with a C project ?

**Comment by VoiDeD** [comment]
You generally can't (outside of making a C++/CLI binding library and exporting C functions), you may be interested in [Steam++](https://github.com/seishun/SteamPP) if you don't have a requirement of only C code.

**Comment by armaldio** [comment]
Thanks for quick answer.
I'm restricted to code in C so, aborting ^^

**Comment by armaldio** [comment]
I saw it's possible to use it when the dll is registered as COM
Is it possible to turn this project into a COM dll ?

http://p2p.wrox.com/c/15992-calling-c-c.html

**Comment by VoiDeD** [comment]
Outside of my area of expertise, but it looks like [this MSDN documentation](https://msdn.microsoft.com/en-us/library/zsfww439%28v=vs.110%29.aspx) might get you started. A quick glance shows that it would likely require code changes to SteamKit, so it might not be possible unless you're willing to fork your own version of the library.

A better question may be why there's a requirement on only using C, as it makes interop with .NET more difficult.

**Comment by armaldio** [comment]
I wanted to developp a third party plugin but no c# sdk with the programm
I'll look you link, thanks again :)
