### ISSUE TITLE
[Help] API Key help

### ISSUE THREAD

**Issue by krisser143** [SteamRE/SteamKit#130]
Hi, I'm currently using the Java SteamKit, but this must be the same on both libraries.
I'm trying to make a program that will involve using the WebAPI class. But what website do i need to fill in here http://steamcommunity.com/dev/apikey ? Does it matter what website the API key is for? Or does the API key need to be made from the IP that the bot is run from?

**Comment by picapi** [comment]
As far as I know, the web address you put in doesn't matter in the slightest, although you should put in the domain name you'll be using the API key for if you can, or your own domain if you own one.
