### ISSUE TITLE
MatchMaking interface?

### ISSUE THREAD

**Issue by Jvs34** [SteamRE/SteamKit#131]
Hi, I was wondering if there's any way to implement the ISteamMatchMaking interface within steamkit, I've looked at the code and there's no protobufs of it at all.

Is it something overlooked or does it simply not use protobufs ( or am I blind)?

Otherwise I guess I would have to do it myself with nethook2.

**Comment by Netshroud** [comment]
Have a look at the protobufs starting with `CMsgClientMMS`.

**Comment by Jvs34** [comment]
Alright I was just blind then, thanks.

**Comment by Jvs34** [comment]
Finally decided to give this a try, although for now I'm just working on the lobbies side of things, then I'll head onto the server list stuff and just work down other stuff.

Question: should I keep the API kind of similar to what steam exposes with steamworks?
Things like ISteamMatchmaking::GetLobbyByIndex are kind of lame to do in c# since the proto itself returns the lobbies straight up, and it'd require pretty much caching all the lobby data received from the messages just like SteamFriends does.

Considering the caching too, the lobbies would probably be readonly for the user, and then updated when steam sends the lobby data updates.

Also, should I provide async methods with the AsyncJob way or stick to callback based approach? What's the consensus on that?

One last thing, should I offer overloads that let you pass the Lobby class itself instead of just the steamid?

ISteamMatchmaking
- [X] CreateLobby( appid, privacy , maxmembers )
- [ ] JoinLobby( appid , lobbysteamid )
- [X] RequestLobbyList( appid , filterclass ) (you can call chaining methods like so ) 
```csharp
            steamMatchMaking.RequestLobbyList( 480 , new SteamMatchMaking.LobbyFilter()
                .AddDistanceFilter( ELobbyDistanceFilter.Worldwide )
                .AddNearValueFilter( "LEVEL" , 5 )
                .AddStringFilter( "MAP" , "whatever" , ELobbyComparison.Equal )
            );       
```
- [ ] InviteUserToLobby( lobbysteamid , usersteamid ) 
- [ ] GetNumLobbyMembers
- [ ] Etc etc

Nothing done on these atm

- ISteamMatchmakingServers
- ISteamGameSearch
- ISteamParties

**Comment by Jvs34** [comment]
The original scope was just matchmaking, will open a new issue for the other interfaces in the future.
