### ISSUE TITLE
Login to 2FA protected account using stored data to avoid entering Code all the time if desired

### ISSUE THREAD

**Issue by Autositz** [SteamRE/SteamKit#132]
20150630-150302 <Autositz> so when an acc is using 2FA the user has to ALWAYS enter the code.. no reason to store the sentry file then oO
20150630-150325 <Netshroud> Not always always, but yes for now in steamkit.
20150630-150345 <Netshroud> You'd need to listen for a loginkey message and send that to log on instead of your password
20150630-150359 <Netshroud> Open an issue and I'll see if I can expose it as API.

**Comment by Netshroud** [comment]
You can now do this as of 08e272b.

1. Log on as usual with `ShouldRememberPassword` set to `true` on the `LogOnDetails` object.
2. Listen for the `LoginKeyCallback`. Save the `LoginKey` somewhere (secure), then call `SteamUser.AcceptNewLoginKey`.
3. When logging in next time, set the `LoginKey` on the `LogOnDetails` object to the value you saved, and set `ShouldRememberPassword` to `true`. Don't set `Password`.
