### ISSUE TITLE
Send raw bytes to CM

### ISSUE THREAD

**Issue by Rosentti** [SteamRE/SteamKit#1341]
### What problem is this feature trying to solve?

I construct messages to send to the CM myself, without using IClientMsg. How can I send raw bytes to the CM?

### How would you like it to be solved?

Add a Send() overload that allows you to send raw bytes, or a function SendRaw.

### Have you considered any alternative solutions

Hacking around and trying to construct a IClientMsg from the passed in raw bytes.

**Comment by yaakov-h** [comment]
What are you trying to do that involves sending raw data?

**Comment by Rosentti** [comment]
I'm looking at reimplementing the local steamclient.dll. One of the interfaces I need is IClientSharedConnection, which sends raw data over the connection to the CM (which is just regular serialized message data, headers, body and all). 
The data that gets passed is only bytes with no extra context, so not much else I can do except parse the bytes in order to pass it to the Send function.

**Comment by Rosentti** [comment]
Actually, nevermind. Turns out I'll need to reparse the incoming messages anyway to add a JobID.
