### ISSUE TITLE
Update dota protobufs to new ones.

### ISSUE THREAD

**Issue by yanshkr** [SteamRE/SteamKit#1353]
### What problem is this feature trying to solve?

Allows you to update the project for new dota protobuffs that have not yet been added.

### How would you like it to be solved?

Add new messages to classes with protobuffs.

### Have you considered any alternative solutions

I looked at the protobuff gen in the resources, but, as I understand it, it is not suitable for gc protobuffs.

**Comment by Qunik** [comment]
I agree, we need to add new dota protobufs
