### ISSUE TITLE
Depotmanifest.Serialize() should be made public.

### ISSUE THREAD

**Issue by nightshadow92** [SteamRE/SteamKit#1354]
### What problem is this feature trying to solve?

Currently, the only way to save DepotManifest is using `SaveToFile()`, making `Serialize()` public would allow alternatives.

### How would you like it to be solved?

Make the `Serialize()` function in DepotManifest public.

### Have you considered any alternative solutions

No.

**Comment by xPaw** [comment]
Serialize() should accept a Stream (which removes the internal MemoryStream), and then SaveToFile can pass the file stream directly in, and then an overload can be added like SaveToStream (for consistency) which just calls Serialize.

PRs welcome.

**Comment by skylayer** [comment]
I've implemented a potential solution for this. Please see PR #1337 for a minimalistic approach that addresses the issue.
