### ISSUE TITLE
[NetHook2]: steam crash after sending websocket frame with invalid opcode

### ISSUE THREAD

**Issue by flameoflust69** [SteamRE/SteamKit#1366]
### What did you expect to happen?

No crash happen

### Instead of that, what actually happened?

Steam automatically exit because nethook crash

### Relevant log output

```plain
CCrypto::SymmetricEncryptChosenIV = 0x67156650
PchMsgNameFromEMsg = 0x67168250
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x672BA640
CCMInterface::RecvPkt = 0x66B01FF0
Detoured CWebSocketConnection::BBuildAndAsyncSendFrame!
Detoured CCMInterface::RecvPkt!
Wrote 84 bytes to 001_in_147_k_EMsgServiceMethodResponse
Wrote 84 bytes to 002_in_147_k_EMsgServiceMethodResponse
Wrote 134 bytes to 003_in_147_k_EMsgServiceMethodResponse
Wrote 84 bytes to 004_in_147_k_EMsgServiceMethodResponse
Wrote 84 bytes to 005_in_147_k_EMsgServiceMethodResponse
Wrote 84 bytes to 006_in_147_k_EMsgServiceMethodResponse
Wrote 136 bytes to 007_in_147_k_EMsgServiceMethodResponse
Wrote 84 bytes to 008_in_147_k_EMsgServiceMethodResponse
Wrote 614 bytes to 009_in_147_k_EMsgServiceMethodResponse
Wrote 138 bytes to 010_in_147_k_EMsgServiceMethodResponse
Wrote 1657 bytes to 011_in_147_k_EMsgServiceMethodResponse
Wrote 30 bytes to 012_in_751_k_EMsgClientLogOnResponse
Sending websocket frame with opcode 117053640 (<Invalid>), ignoring
```

### Additional Information

Steam Beta Branch:  Stable Client
Steam Version:  1718305227
Steam Client Build Date:  Fri, Jun 14 2:42 AM UTC -08:00
Steam Web Build Date:  Thu, Jun 13 11:50 PM UTC -08:00
Steam API Version:  SteamClient021

Windows 23H2

**Comment by flameoflust69** [comment]
Fixed after updating sigs:
- CWebSocketConnection::BBuildAndAsyncSendFrame
  - x86
    `\x55\x8B\xEC\x83\xEC\x00\xA1\x00\x00\x00\x00\x53\x8B\xD9\x89\x5D\x00\x83\x38\x00\x75\x00\x33\xC0\xEB\x00\x8D\x45\x00\x50\x6A\x00\x68\x00\x00\x00\x00\xFF\x15\x00\x00\x00\x00\x83\xC4\x00\x83\x7B\x00\x00\x89\x45\x00\x74 xxxxx?x????xxxxx?xx?x?xxx?xx?xx?x????xx????xx?xx??xx?x` 
  - x64
    `\x48\x8B\xC4\x55\x48\x8D\x68\x00\x48\x81\xEC\x00\x00\x00\x00\x48\x89\x70\x00\x49\x8B\xF0\x48\x89\x78\x00\x4C\x89\x60 xxxxxxx?xxx????xxx?xxxxxx?xxx
`
- CCMInterface::RecvPkt
  - x86
    `\x55\x8B\xEC\x81\xEC\x00\x04\x00\x00\xA1\x00\x00\x00\x00\x56\x57\x8B\xF9 xxxxx?x??x????xxxx`

**Comment by mrbeardad** [comment]
It does not work for steamclient.dll (8.98.27.94)

**Comment by xPaw** [comment]
Can you make a pull request with new signatures please.
