### ISSUE TITLE
SmartCMServerList should refresh itself over the api

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#1421]
If it fetches no servers from API and fallbacks to resolving cm0.steampowered.com, it will still call UpdateServerListAsync which saves this lone server to the file storage. So later on it will still stick to using this server.

Do we not have a mechanism for updating the server list, so if it loads something from cache it will use it forever until it gets a new server list after connecting to the CM? Seems problematic.

**Comment by yaakov-h** [comment]
I think we were relying on the list being updated on logon:

https://github.com/SteamRE/SteamKit/blob/4affed174f6fcc5e39fd34e618b741e219d9151a/SteamKit2/SteamKit2/Steam/CMClient.cs#L621-L633

**Comment by xPaw** [comment]
Yeah which may not happen if you never connect due to a bad initial list.

**Comment by xPaw** [comment]
CMList emsg was seemingly removed: https://github.com/SteamDatabase/Protobufs/commit/a4d678cce1cfb867babf216bdbd26a102fdcc8fc#diff-0890ddf12b92549d22334ac7fc8c2a7e57ce0e2c48193be0e95174253ff7b435

**Comment by xPaw** [comment]
We should use the api to refresh the server list, i've run into an issue where it initially returned dead servers, and it keeps trying them first on app start because it doesn't refresh the list.

**Comment by xPaw** [comment]
For some reason Steam keeps returning servers that don't actually work, our server list definitely needs a way to refresh itself instead of always relying on the cache it saved.
