### ISSUE TITLE
Callback handle() throws "Collection was modified" when unregistering callback

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#1424]
introduced in 21fe9567445510cf2d6e27c3a7cf3368da6a7b82 I think.

I have a Unregister callback call in licenselist so that it gets triggered once, which causes a threading issue here now. Unsure what's an easy fix besides just locking the collection.

**Comment by xPaw** [comment]
I'm not sure that wrapping it into locks would even be a good fix, because you'd deadlock if you tried to unregister a callback from inside of a callback I think.

@yaakov-h any ideas besides just changing it to concurrent collection?

**Comment by yaakov-h** [comment]
Nope.

**Comment by xPaw** [comment]
Theres no ConcurrentList directly (and we kind of want to retain the ordering here). Maybe recreate the list in Add/Remove calls, and in Handle have a temporary var that holds ref to the current list?

**Comment by yaakov-h** [comment]
That doesn't exactly help with concurrency. You might be better served with a loop and Interlocked.CompareExchange or ImmutableInterlocked.CompareExchange
