### ISSUE TITLE
Load inventory

### ISSUE THREAD

**Issue by jacobs100500** [SteamRE/SteamKit#146]
Help please. I found Protobuf messages "steammessages_inventory.steamclient" and tried to use them, but they do not work. The response returns the result OK, but the body is empty. steam support these messages? I sent this messages with assistance SteamUnifiedMessages handler.

**Comment by Netshroud** [comment]
Steam should support them - I believe the unified messages power the new Inventory Steamworks APIs.

Can you post an example of what you're doing, what results you're expecting, and what the actual results are that you're getting?

**Comment by jacobs100500** [comment]
I need to get someone else Inventory of the apps ID 570, 730, 440, 753(gifts). The result should be like in the WebAPI (/IEconItems_{APP_ID}/GetPlayerItems/). But i can not use the API, because it does not have the app 753, and app 730 is not stably. The usual method (/{STEAMID}/inventory/json/...) of loading inventory is not suitable. I hoped that Protobufs messages will solve my problem. 
Here is an example of my code:
var Service = SteamUnifiedMessages.CreateService<CInventory>();
CInventory_GetInventory_Request request = new CInventory_GetInventory_Request();
request.appid = 570;
request.steamid = SteamClient.SteamID.ConvertToUInt64();
Service.SendMessage<CInventory_Response>((x) => x.GetInventory(request));

CInventory сlass does not affect the answer. Methods therein are not caused.

Callback is SteamUnifiedMessages.ServiceMethodResponse.
callback.Result - OK.
callback.MethodName - Inventory.GetInventory#1.
callback.MethodName - GetInventory.
callback.MethodName - Inventory.
callback.ResponseRaw.Length - 4.

I deserialize response in class CInventory_Response. Result:
CInventory_Response.item_json - []
Another fields is empty.

Also, in protobufs messages I found the message CSOEconItem (base_gcmessages.proto). I need response containing this message.

**Comment by Netshroud** [comment]
That's because the Inventory service has no data for that game.

The Inventory service is not the same as the Econ system which powers Dota 2, TF2 and CS:GO. It's a new service for Steamworks developers to build inventories without having to build their own backend.

I managed to get a `CInventory_Response` containing data by using an `appid` and `steamid` for a game that is actually using the Inventory service, but as I expected, it returns no data for other appids.

**Comment by VoiDeD** [comment]
Closing as this looks resolved.
