### ISSUE TITLE
never get reply with findSourceTVGames and findTopSourceTVGames

### ISSUE THREAD

**Issue by TJRoger** [SteamRE/SteamKit#147]
I cannot receive any response for EDOTAGCMsg.k_EMsgGCFindSourceTVGames, message CMsgFindSourceTVGames and EDOTAGCMsg.k_EMsgClientToGCFindTopSourceTVGames ,message CMsgClientToGCFindTopSourceTVGames

**Comment by Netshroud** [comment]
SteamKit exposes the GC for you to use, but for any specifics you're on your own.

You can try using NetHook2 and NetHookAnalyzer to see what Dota 2 does and mimic that.
