### ISSUE TITLE
[Bug]: Custom UnifiedServices can't be created

### ISSUE THREAD

**Issue by ezhevita** [SteamRE/SteamKit#1476]
### What did you expect to happen?

In the previous versions of SteamKit you could create a custom UnifiedService just by supplying the necessary .proto file to ProtobufGen and use the generated definitions as-is, which solves the problem of SteamKit not including some of the unified services.

### Instead of that, what actually happened?

If you try to use the same process for UnifiedService generation, you'd encounter that `SteamUnifiedMessages.HandleResponseMsg<TService>(PacketClientMsgProtobuf packetMsg)` is internal and thus not accessible through the user code. This method wraps the response using the internal constructor and then posts as a callback (in order to be usable with `AsyncJob`), so this also can't be reimplemented in the user code. The only existing workaround is to call that method through the reflection.

### Which operating system are you running on?

None

### Which .NET Runtime are you running on?

.NET Core or .NET 5 or higher.

### Version

9.0.100 SDK

### Example Code

```csharp
// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: service_steamawards.proto
// </auto-generated>

#region Designer generated code

using SteamKit2;

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace CustomPlugin
{
    // Class definitions omitted for brevity

    public class SteamAwards : SteamUnifiedMessages.UnifiedService
    {
        public override string ServiceName { get; } = "SteamAwards";

        // Method definitions omitted for brevity

        public override void HandleResponseMsg( string methodName, PacketClientMsgProtobuf packetMsg )
        {
            switch ( methodName )
            {
                case "GetNominationRecommendations":
                    // error: Cannot access internal method 'HandleResponseMsg<TService>(PacketClientMsgProtobuf)' here
                    UnifiedMessages.HandleResponseMsg<CSteamAwards_GetNominationRecommendations_Response>( packetMsg );
                    break;
            }
        }

        public override void HandleNotificationMsg( string methodName, PacketClientMsgProtobuf packetMsg )
        {
        }
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
```

**Comment by xPaw** [comment]
I thought we have covered necessary changes to allow user supplied services. Can you make a PR to fix the issue you're having?
