### ISSUE TITLE
[Bug]: Stats - stat_value only allows for units

### ISSUE THREAD

**Issue by DeadStarlin** [SteamRE/SteamKit#1478]
### What did you expect to happen?

Valve now allows for floats in stats: https://steamdb.info/app/24010/stats/ eg. stat dlc.1267507.HoursPlayed

### Instead of that, what actually happened?

Some way to receive stat if is also not as uint but also as floating point values

### Which operating system are you running on?

None

### Which .NET Runtime are you running on?

.NET Framework

### Version

9

**Comment by xPaw** [comment]
What are you talking about?

**Comment by DeadStarlin** [comment]
About that line https://github.com/SteamRE/SteamKit/blob/792385fdd688354f96a6172a530b0393caaf35be/SteamKit2/SteamKit2/Base/Generated/SteamMsgClientServerUserStats.cs#L133C9-L133C35 - I can be mistaken but from what I see stat_value is as uint

**Comment by xPaw** [comment]
Prorobufs come from Steam client and are ATP generated, we don't modify them.
