### ISSUE TITLE
Add SteamID.Parse

### ISSUE THREAD

**Issue by WildCard65** [SteamRE/SteamKit#149]
It would be useful if the SteamID class has a static Parse method that takes an input string and attempts to convert it to a SteamID instance.
ex: SteamID.Parse("insert 64bit id string here") would return a new SteamID object.
ex2: SteamID.Parse("insert 32bit id string here") would also return a new SteamID object.
ex3: SteamID.Parse("insert steam3 string here") would again return a new SteamID object.

**Comment by xPaw** [comment]
Is this what you want? https://github.com/SteamDatabase/SteamDatabaseBackend/blob/master/IRC/Commands/SteamID.cs#L143-L163

**Comment by WildCard65** [comment]
Yes, but I need it for c#

**Comment by xPaw** [comment]
And I linked you in what...?

**Comment by WildCard65** [comment]
Something that I don't plan on using. I didn't notice it was c# though.

**Comment by xPaw** [comment]
Copy the function, what's the problem?

**Comment by WildCard65** [comment]
It would make sense if SteamKit adds one. But I did make my own though after looking through SteamID.cs

**Comment by Netshroud** [comment]
What's your use case? Nowhere in SteamKit is there a requirement for SteamID-from-arbitrary-string. The format should be known beforehand.

If you're validating user input, that's up to the consumer.

Also, your example 2
> SteamID.Parse("insert 32bit id string here")

isn't actually a valid SteamID - you only have the account ID. You would still need to specify universe, account type and instance.

**Comment by WildCard65** [comment]
I'm just saying in my examples what to imagine to go in there. A use case: Converting JSon string into a SteamID. Also for 32bit ids, default universe param of Public.

**Comment by Netshroud** [comment]
When converting a JSON into a SteamID, you ought to know what format that that JSON value will be in.

Regarding a "32-bit ID", you only have half a SteamID. You know from your context what the other half of the SteamID is, but that's not a globally applicable case.

**Comment by JustArchi** [comment]
When I receive steamID from JSON, it's always in 64-bit form. So you can then check if it parses to ```ulong```, and if yes, use ```SetFromUInt64()``` function of SteamID.

However, like mentioned above, I have no idea what do you need SteamID for. All requests that are being sent or used do accept ```ulong``` and converting that ```ulong``` to ```SteamID``` only to convert it back to ```ulong``` before sending sounds really silly to me.

**Comment by Netshroud** [comment]
I'm gonna close this one as `wontfix`, or I would if we had that tag.

You've got your own function now, and I don't see the value in adding this to SteamKit itself.

**Comment by JustArchi** [comment]
Just one more comment - I found one place where it's actually used, and it's Steam API - https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService under ```accountid_other```.

I created a class with those properties:
```
internal int accountid_other { get; set; }
		internal ulong OtherSteamID64 {
			get {
				return new SteamID((uint) accountid_other, EUniverse.Public, EAccountType.Individual).ConvertToUInt64();
			}
			private set { }
		}
```

Probably there is a better way, but that works and is quite fast.

Just in case somebody needs similar code in future.

**Comment by VoiDeD** [comment]
It should be noted that there's more than one SteamID that an account ID can create. You have to be wary of the context:

* In general the universe will always be public, but it's best to account for the universe you're connected to.
* Individual accounts belong to users, but what if the response is telling you about the account ID of a game server?

**Comment by JustArchi** [comment]
In case of trades, they always must be done on public universe and made from invidual users.

But I agree it's not always the case.

**Comment by Netshroud** [comment]
> In case of trades, they always must be done on public universe

I bet you it works in some fashion on `Beta` and `Dev` as well. Just because you don't interact with them doesn't mean that nobody else using the library won't.

The best solution would be to use `SteamClient.ConnectedUniverse`.

Also, for both you and future users reading this, the empty private setter makes no sense. Skip it.

**Comment by JustArchi** [comment]
Corrected my response a bit, thank you! :+1:
