### ISSUE TITLE
SteamFriends.JoinChat not working?

### ISSUE THREAD

**Issue by Tenrys** [SteamRE/SteamKit#154]
Calling this method with the SteamID from the ChatInvite callback just doesn't do anything, no error.
Even with a 5 second timer between the invite and the attempt to join.

Am I just doing it wrong?

    steamFriends.JoinChat(callback.ChatRoomID);

**Comment by VoiDeD** [comment]
Have you tried handling `ChatEnterCallback` and seeing what the `EnterResponse` value is?

**Comment by Tenrys** [comment]
I haven't, I'll try this out.

**Comment by Tenrys** [comment]
Says "Limited". What does it mean?

**Comment by VoiDeD** [comment]
The account you're attempting to join the chat room with is limited. 

https://support.steampowered.com/kb_article.php?ref=3330-IAGK-7663

**Comment by Tenrys** [comment]
darn, didn't know this was a thing.
