### ISSUE TITLE
Errors on HardwareUtils

### ISSUE THREAD

**Issue by HugKitten** [SteamRE/SteamKit#159]
When I try to compile SteamKit, I get, "This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105."

So I right click on the solution and click enable package restore and try to rebuild everything. I then get "Expected class, delegate, enum, interface, or struct" errors on these lines in HardwareUtils.cs:

using static SteamKit2.Util.MacHelpers.LibC;
using static SteamKit2.Util.MacHelpers.CoreFoundation;
using static SteamKit2.Util.MacHelpers.DiskArbitration;
using static SteamKit2.Util.MacHelpers.IOKit;

And finally this error:
Metadata file 'D:\Documents\SteamKit-master\SteamKit-master\SteamKit2\SteamKit2\bin\Debug\SteamKit2.dll' could not be found

I'm using Visual Studios 2013

**Comment by VoiDeD** [comment]
You need VS 2015 to compile, namely C# 6.0 support.

**Comment by HugKitten** [comment]
Thanks for help, I really appreciate it.
