### ISSUE TITLE
Move the protobufs into a separate repo

### ISSUE THREAD

**Issue by seishun** [SteamRE/SteamKit#16]
Many projects use Steam .proto files in one way or another. Some maintain local copies of the protobufs, e.g. [SKSteamKit](https://github.com/yaakov-h/SKSteamKit), while others, including [node-dota2](https://github.com/seishun/node-dota2), [go-steam](https://github.com/Philipp15b/go-steam) and [Steam++](https://github.com/seishun/SteamPP), link to this repo. With the former approach, the protos will be constantly out of date, while the latter requires the user to clone the pretty huge SteamKit2 repo.

It would greatly benefit the aforementioned projects if the .proto files were in their own repository. This would ensure a single central source for the protobufs that's easy to use as a dependency.

**Comment by paralin** [comment]
DOTA2 protobufs are now kept up to date in http://github.com/paralin/Dota2 which is now referenced by node-dota2

**Comment by SinZ163** [comment]
Theres also the http://github.com/SteamDatabase/GameTracking repo with maintained protobufs

**Comment by Netshroud** [comment]
Those both have the same drawbacks as cloning SteamKit.

**Comment by paralin** [comment]
That's not exactly true, my repo is tiny in comparison

**Comment by xPaw** [comment]
So I want to make a separate repository entirely just for protobufs which will be synced by @SteamTracker automatically.

Currently it will track steamclient, tf2, csgo, dota2. Are these enough to be in a single repository?

**Comment by psychonic** [comment]
Protobufs are now used from the SteamDB repo mentioned above. I'm not sure if there's still any consideration being done to move anything else to separate repos.
