### ISSUE TITLE
Bug After Disconnect

### ISSUE THREAD

**Issue by HugKitten** [SteamRE/SteamKit#160]
This is an issue in the class CMClient:

HandleLoggedOff is only called when the client logs off but not when it disconnects. If I disconnect and reconnect with a different account it uses the old steamID instead of 0. This causes a bug where you login as an anonymous user instead of the new user.

Am I suppose to call logout first?

**Comment by VoiDeD** [comment]
Ideally the client should attempt a logoff first (this will also trigger a disconnection initiated by the Steam servers), but this may not always be possible.

Can you check if 75bc4273831431d2416c9c4cdc8de2c16aa01140 resolves this issue for you?

**Comment by HugKitten** [comment]
That's the same thing I did to fix it for me. So I can confirm that it does resolve the issue. Thanks!
