### ISSUE TITLE
Can the following be used with SteamID class?

### ISSUE THREAD

**Issue by WildCard65** [SteamRE/SteamKit#161]
Which of the following can be placed inside a SteamID instance?
A game's app id?
An inventory's context id?
An Item's Unique ID?
A trade offer id?
A trade id?

**Comment by xPaw** [comment]
None of them.

**Comment by WildCard65** [comment]
Alrighty then

**Comment by rlabrecque** [comment]
A SteamID can.

**Comment by WildCard65** [comment]
@rlabrecque I know a user's steamid can, but I was wondering what else counts as a steamid

**Comment by rlabrecque** [comment]
https://github.com/SteamRE/open-steamworks/blob/master/Open%20Steamworks/CSteamID.h#L36
