### ISSUE TITLE
return dynamic for WebApi.GetInterface and GetAsyncInterface

### ISSUE THREAD

**Issue by WildCard65** [SteamRE/SteamKit#162]
Wouldn't it be best for WebApi.GetAsyncInterface and WebApi.GetInterface to return dynamic that way AsyncInterface and Interface can be internal?

**Comment by VoiDeD** [comment]
Consumers may not have dynamic language support; I believe at some point VB didn't have a dynamic keyword (and it still might not, I'm not sure).

On top of that, `AsyncInterface` and `Interface` are public APIs, we can't make them internal considering that they also find use in client code, even in SteamKit itself.
