### ISSUE TITLE
The DotaMatchRequest project is not working.

### ISSUE THREAD

**Issue by TimotheeJeannin** [SteamRE/SteamKit#165]
It looks like the GC is not sending with any `k_EMsgGCClientWelcome` message.
As a result the program just hangs.

    mono DotaMatchRequest/bin/Debug/DotaMatchRequest.exe Macheteueu PasswordOfMacheteueu 1056167535
    Connecting to Steam...
    Connected! Logging 'Macheteueu' into Steam...
    Logged in! Launching DOTA...

**Comment by xPaw** [comment]
Try adding `clientHello.Body.engine = ESourceEngine.k_ESE_Source2;` when sending a hello message.

**Comment by TimotheeJeannin** [comment]
Just added `engine = ESourceEngine.k_ESE_Source2` to the body of the `k_EMsgGCClientHello` message. 

It goes a little further but still hangs. 

    mono DotaMatchRequest/bin/Debug/DotaMatchRequest.exe Macheteueu PasswordOfMacheteueu 1796519998
    Connecting to Steam...
    Connected! Logging 'Macheteueu' into Steam...
    Logged in! Launching DOTA...
    GC is welcoming us. Version: 1505
    Requesting details of match 1796519998

**Comment by TimotheeJeannin** [comment]
I feel it's not just the DotaMatchRequest project. When I try to get leagues information or a player's match history, it looks like the GC just doesn't respond.

**Comment by VoiDeD** [comment]
I'm experiencing the same behavior in Dota as well; it's just unable to load match details of either live games or replays.

**Comment by TimotheeJeannin** [comment]
It looks like the GC is responding now. :)
