### ISSUE TITLE
Compile CSGO's gcsdk to CSGO.Internal

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#172]
Dota 2's S2 welcome message is not compatible with CSGO's thus making it impossible to parse correctly.

Any downside to compiling csgo/gcsdk to CSGO.Internal namespace?

**Comment by VoiDeD** [comment]
I don't think there's anything wrong with this.

In fact, I think it'd likely be okay to remove the game agnostic "base" GC messages and replace them entirely with each game's own compiled versions in `<game>.Internal`.

We don't provide any API contracts for generated messages in `Internal` namespaces, so there's lots of room to rework this.

**Comment by xPaw** [comment]
Yeah this might be a better solution over all. Is there any reason to call it `Internal` at that point though, might be better to come up with something better.
