### ISSUE TITLE
ProtobufDumper: Consider adding specialization to handle fat Mach-O binaries

### ISSUE THREAD

**Issue by Netshroud** [SteamRE/SteamKit#179]
I.e. only dump protos from one architecture. Otherwise, since we load every proto twice, extensions are duplicated.

This could also halve runtime since there's half as much data to scan.

**Comment by xPaw** [comment]
#611 should have fixed the issue with duplicate extensions.

**Comment by yaakov-h** [comment]
Seems to be working well enough without this anyway.
