### ISSUE TITLE
CI: Code Coverage Analysis

### ISSUE THREAD

**Issue by Netshroud** [SteamRE/SteamKit#184]
Options:
* [codecov.io](https://codecov.io) - first-party C# support, used by StyleCopAnalyzers. We can probably pilfer Travis commands from their AppVeyor config :)
* [coveralls.io](https://coveralls.io) - No first-party .NET support. They offer a third-party uploader, requires another third-party analysis tool such as `monocov`. @xPaw seems to like them.
* Any others?

**Comment by VoiDeD** [comment]
Can we exclude assemblies/types? Code coverage metrics wouldn't be particularly useful for all our generated code.

**Comment by Netshroud** [comment]
OpenCover (the uploader tool to use for both of the above) has filters to include and exclude by type.
