### ISSUE TITLE
SteamFriends.SetPersonaName modification is a "breaking change"

### ISSUE THREAD

**Issue by StoneWolf** [SteamRE/SteamKit#189]
I tried upgrading from SteamKit2 1.6.2 to 1.6.5 and got "MissingMethodException"s everywhere, telling me that the SetPersonaName method could not be found. I then noticed that SetPersonaName has changed return type, so you might want to add that as a breaking change to the release notes, since simply replacing the DLL could break your current installation.

**Comment by VoiDeD** [comment]
Our breaking changes list is generally geared towards source level compatibility. I guess we need a more formal stance on our version compatibility with regards to the binary level.

On that subject, I'm not sure if we want to strongly police any ABI breakage or encourage consumers to decide if they should or should not replace the binary in-place (that is, I feel that recompilation should always be involved).

Here's a few points of interest:
* Anything in our `Internal` namespaces is mostly generated code, and as such it has a high tendency for breakage/regeneration. Any other assemblies referencing types or fields that have changed will explode violently on an in-place binary replacement.
* If another Steam message gets "jobified" in the future, we'd like to be able to freely change the return type to `JobID`.
* We'd also like to have the ability to add default parameters to methods in future versions, if needed.
* There's also #170 in the pipeline for the future, and this will also end up being a binary level break.

I think the first point alone is enough to encourage a recompilation step in most cases, especially for anyone building code with their own message handlers or around GC messages.

**Comment by Netshroud** [comment]
I'm in agreement with VoiDeD on this.

It's often not particularly hard to provide binary compatibility, but it becomes a large maintenance overhead in a project such as this, where changes can be necessitated to mirror a change in Steam, and our APIs aren't abstracted as well as something like Steamworks.

For something like SetPersonaName, that's harder. A method signature includes the return type as far as the runtime is apparently concerned, but you cannot have two identical methods that differ only by return type. We would have to have made `SetPersonaNameEx` or `SetPersonaName2` or `SetPersonaNameJob` or something like that, whilst maintaining the older non-Job version.

Considering that our primary distribution method is NuGet, which runs before the compilation stage of any project, I don't think drop-in replacement compatibility at runtime is a major concern.
