### ISSUE TITLE
[Question] Steam online

### ISSUE THREAD

**Issue by Frodiwe** [SteamRE/SteamKit#199]
I tried to use CMsgDPGetNumberOfCurrentPlayers and its response to get current online on Steam but    it work only with games and etc. and doesn't work with Steam 'app' (appId = 753). Is there any other ways to do it?

**Comment by VoiDeD** [comment]
For Steam you want to pass 0 as the app.

**Comment by Frodiwe** [comment]
It worked! Thanks!
