### ISSUE TITLE
Steam Market Transactions

### ISSUE THREAD

**Issue by overheader** [SteamRE/SteamKit#201]
Is it possible with SteamKit to buy the keys to the cases in cs:go (not marketplace)?
I can pay for the work.

**Comment by SinZ163** [comment]
this isn't node-steam...

**Comment by overheader** [comment]
Sorry, I just duplicated the topic.

**Comment by VoiDeD** [comment]
Community market interaction is outside the scope of SteamKit (and can be performed with regular HTTP requests). On top of being a violation of the Steam Subscriber Agreement:
>You may not use Cheats, automation software (bots), mods, hacks, or any other unauthorized third-party software, to modify or automate any Subscription Marketplace process.
