### ISSUE TITLE
PICSGetChangesSince only returns changes for high values for LastChangeNumber

### ISSUE THREAD

**Issue by angyan** [SteamRE/SteamKit#207]
The CurrentChangeNumber for Steam is 1571380. 

If I use PICSGetChangesSince(0, true, true) or PICSGetChangesSince(1, true, true) to get the initial list, I get AppChanges and PackageChanges = 0. 

If I use PICSGetChangesSince(1571000, true, true), I get some AppChanges and PackageChanges. 

I'm basically trying to get an initial list of all applications, so that I can seed my database and then make changes from there. Is there an easier way to get a list of all applications?

**Comment by xPaw** [comment]
Valve added a restriction on this not too long ago, so this method no longer works.

**Comment by angyan** [comment]
I'm basically trying to get an initial list of all applications, so that I can seed my database and then make changes from there. Is there an easy way to get a list of all applications in Steam?

**Comment by xPaw** [comment]
There is not.

**Comment by RudeySH** [comment]
In an attempt to figure out how many change numbers you can go back before it stops returning `AppChanges`, I found something mildly interesting. I was able to go back 9340 change numbers, and I noticed `AppChanges` contained exactly 4000 items. I guess there isn't a fixed number of change numbers you can go back, and instead Valve restricted the total number of `AppChanges` you can retrieve. If it would go over 4000, you'll get 0 `AppChanges` instead.

There seems to be a different threshold for `PackageChanges`.
