### ISSUE TITLE
Add DNX 5.0 platform support

### ISSUE THREAD

**Issue by paralin** [SteamRE/SteamKit#209]
I've just moved DOTA2 to the DNX model for publishing C# libraries.

This follows the style that [EntityFramework](https://github.com/aspnet/EntityFramework/tree/dev/src/EntityFramework.Core), a Microsoft project, and many other projects now follow.

DNX is a very cross-platform tolerant, open source thinking version of .NET, and is supposedly the "next generation".

It can compile to target any framework, though. As you can see in the [project.json](https://github.com/paralin/Dota2/blob/master/src/Dota2/project.json) I define three platforms to target, `net451`, `dnx451`, `net40`. You can define other targets as well. The DNX builder (integrated with VS 2015) then outputs a nuget package targeting all defined frameworks.

protobuf-net is compatible. 

I will send a PR if you are interested.

**Comment by paralin** [comment]
This might be worth bundling with your awaiter/async work. Would make things far easier in terms of testing on Travis since DNX supports mono or coreclr on Linux.

**Comment by VoiDeD** [comment]
Closing since most of this is superseded by #299.
