### ISSUE TITLE
GC enum values missing

### ISSUE THREAD

**Issue by ChaosEmperor** [SteamRE/SteamKit#210]
I'm using the latest NuGet package of SteamKit2.

Some enum values such as `EGCItemMsg.k_EMsgGCTrading_CancelSession` seem to be missing. I'm not sure why, as these appear to have been in the SteamKit2 source since commits before Oct, when 1.6.5 had been released.

Most other ones seem to be present though.

**Comment by VoiDeD** [comment]
You'll likely need to be specific about what game's GC messages here.

Prior to #180, we've used Dota's protobufs to generate the "base" set of GC messages and enums. Over time, however, the base messages of games such as Dota and TF2 have diverged considerably, so now we generate each game's base messages separately.

So I imagine the issue you're encountering was solved by that PR, but one problem is that #180 hasn't landed in any release, so you'll either need to use steamkit tip, or generate your own protobufs for the game you're targeting (this has been the recommended advice, as game protobufs often aren't timely updated in our project, and you can get stuck waiting for updates inbetween releases).

**Comment by ChaosEmperor** [comment]
I apologize for not being clear. I was referring to TF2's messages. I was working on a simple port of `node-tf2` for c#.

May I know why #180 has not landed in any release?

**Comment by VoiDeD** [comment]
>May I know why #180 has not landed in any release?

I don't think there's been enough feature churn to do another release. We could do one so that you could get the changes in #180, but the recommended approach is still for you to generate your own protobufs.

**Comment by ChaosEmperor** [comment]
I understand. I was shying away from generating my own protos since I know nothing about the protobuf scene and there seems to be oh-so-much for a library I'm not going to use excessively.

But I guess I'll try my hand at it and if I fail, I'll just hard code the `uint` EMsg values.

Keeping my fingers crossed that the next release with #180 is not too far away.
