### ISSUE TITLE
Receiving a non-OK ChannelEncryptResult leads to Connected callback still firing, but no encryption set up

### ISSUE THREAD

**Issue by XMPPwocky** [SteamRE/SteamKit#213]
https://github.com/SteamRE/SteamKit/blob/10e5b78cc315ec230611c7d5c3082f2703e7ed9a/SteamKit2/SteamKit2/Steam/CMClient.cs#L459

CMClient's handling of ChannelEncryptResult will set up encryption if and only if the ChannelEncryptResult was EResult.OK. Otherwise, the connection remains in plaintext.

https://github.com/SteamRE/SteamKit/blob/c45c93b490d1dc5508c5b232069e00ff7e17c0fd/SteamKit2/SteamKit2/Steam/SteamClient/SteamClient.cs#L324

SteamClient handles all ChannelEncryptResult messages by firing Connected. 

An attacker who can modify network packets between a SteamKit client and Steam can intercept all communication, in plaintext. First, they block the ChannelEncryptResponse from the client to Steam; they replace it with their own, with their own session key.

Next, they send a non-OK ChannelEncryptResult to the client; it now thinks it is connected, but is still communicating unencrypted! The attacker encrypts the plaintext messages with their own keys, and Steam just sees a normal, encrypted connection.

**Comment by VoiDeD** [comment]
>Next, they send a non-OK ChannelEncryptResult to the client

It seems to me that the attack would end here. The consumer is expected to check the `Result` of the `ConnectedCallback`. If it's not OK then a logon shouldn't be attempted.

**Comment by Netshroud** [comment]
We should either heavily document this fact, or make it harder for consumers to shoot themselves in the foot.

If we take the responsibility internally, a bad crypto result should probably trigger a disconnect.

**Comment by XMPPwocky** [comment]
Yeah; "not checking the result in ConnectedCallback" doesn't seem like the sort of thing that would let a MITM attacker read your credentials off the wire.

(For what it's worth, DepotDownloader doesn't check it.)
