### ISSUE TITLE
Possible to set EPersonaStateFlags?

### ISSUE THREAD

**Issue by bartico6** [SteamRE/SteamKit#215]
Is it anyhow possible? Looking through the repo I can't seem to find anything, while it must be possible given mobile steam and the main client can set those whenever needed. I have a decompiled source of Steam's mobile app apk, if you'd wish to include an option to do this - I'll provide mobile code.

**Comment by VoiDeD** [comment]
My understanding is that those are Steam's flags for users, how can the main client set them?

**Comment by bartico6** [comment]
When you switch into big picture, the steam flag is added to the user somehow.

**Comment by VoiDeD** [comment]
Which is done with `CMsgClientUIMode`, and that should clue you into how persona state flags work.

You can't directly set them, you have to perform the relevant action to acquire the flag (set UI mode for big picture, connect via the mobile and web endpoints, etc).

**Comment by bartico6** [comment]
Setting UI mode is purely clientside though (right?), you could simulate this and sent relevant data to Steam, effectively setting the flag. No idea if spoofing those could cause an accout suspesion, but I'd say it's worth a shot :)

**Comment by Netshroud** [comment]
Persona State Flags are dictated server-side only. There are certain actions that the user can do to influence this, such as set up a community profile, set up Steam Guard, connect the Mobile or Web chat clients, change native client mode to Big Picture, or purchase a 2014 golden Holiday Profile.

Some flags are beyond our control, such as being a Steam Support administrator.

There's no way to directly manipulate the field as a whole. If there's a particular flag you want to manipulate, you need to find out how to manipulate that particular flag.

Regarding `CMsgClientCurrentUIMode`, UI Mode 1 is Big Picture, 0 is regular desktop client.

**Comment by bartico6** [comment]
Thank you for telling me, this will be useful
