### ISSUE TITLE
Normal trades and escrow, does Steamclient have a role in it?

### ISSUE THREAD

**Issue by WildCard65** [SteamRE/SteamKit#216]
@bartico6 wanted my help in finding out how a normal trade knows about if escrow should be applied. I eventually assumed the steamclient is involved and placed nethook onto the process, it eventually dumped me 2 unknown messages right after a in_7705_k_EMsgEconTrading_StartSession, the 2 messages are also an in message id 13879, is it possible for steamkit to implement what these messages are?

**Comment by bartico6** [comment]
I have also found that it's apparently **very very disappointingly** hardcoded into the webpage and not in the trade events, suggesting steam might be inserting something into the request and/or hardcoding.
>><script>
	// The number of days the trade will be placed on hold if the corresponding party is sending items in the trade.
	// We round up, thus even a single second of escrow will be shown to the user.
	var g_daysMyEscrow = 0;
	var g_daysTheirEscrow = 3;
</script>

**Comment by VoiDeD** [comment]
I think it's unlikely the Steam client has any involvement with escrow. Trading has always been web based, with the client only involved in initiating the session.

**Comment by WildCard65** [comment]
Could you atleast look into the in message from steam please?

**Comment by Netshroud** [comment]
There are no new documented `EMsg`s in steamclient.

That `EMsg` sounds way out of range. If you're using the Steam Client Beta, make sure you're using the latest NetHook2 code, i.e. at or after a1b7aee.

**Comment by WildCard65** [comment]
@Netshroud I was using NetHook2 version in https://github.com/SteamRE/SteamKit/commit/0f3c51ff754f3c7f91385d38ba3b7141af89b9a3 which is a few commits after one you linked

**Comment by WildCard65** [comment]
@Netshroud I just recaptured the same 2 messages with the same id I said they were with NetHook2 from current head

**Comment by Netshroud** [comment]
I took a look through steamclient but couldn't find anything with this `EMsg`. Can you upload it somewhere (if you trust me enough), or otherwise provide step by step instructions on how to reproduce it with two Steam accounts?

**Comment by WildCard65** [comment]
@Netshroud To produce(I only tested this by being the one who sent the trade request, idk if it works being on the receiving end of one): Request a trade with someone, they accept and you get the EMsg TradeSessionStart then instantly after, the 2 EMsgs that are unknown. Also can you provide me a wait to privately send you the .bin file(like email)?

**Comment by Netshroud** [comment]
^ username - at - gmail

**Comment by WildCard65** [comment]
@Netshroud ok I sent email(my email address has my IRL name on the account though)

**Comment by Netshroud** [comment]
That's not a message. It looks more like a cookie or something similar - it's plain text, not a CM message format.

**Comment by WildCard65** [comment]
Good to know then
