### ISSUE TITLE
Reintroducing two factor code

### ISSUE THREAD

**Issue by AlekseySkynox** [SteamRE/SteamKit#223]
Hello everybody. Please tell me, i'm use "Sample5_SteamGuard" the example for authorization. After enter the mobile code authorizations successful, but after the restart the program again asks to enter the code.

How to avoid re-entering the code?

Thanks and sorry for the my bad english!

**Comment by AlekseySkynox** [comment]
I'm saving "LoginKeyCallback LoginKey" in the file (key.txt). After, in "LogOnDetails" i add "ShouldRememberPassword = true" and if file (key.txt) exists, i loading in "LoginKey" file content.

It's right ?
Again, sorry for the my english.

**Comment by Netshroud** [comment]
My understanding of the authenticator-based two-factor login is that the two-factor code is required on every single login attempt. Therefore, the login key will stop you having to enter the account password, but still requires the authenticator-generated code.

**Comment by Netshroud** [comment]
Also, the login key can and does change. If you want to use login key correctly, remove the `!File.Exists` check when writing to file.

**Comment by AlekseySkynox** [comment]
Thanks for answer, i understand.
