### ISSUE TITLE
error event throws incorrect EResult

### ISSUE THREAD

**Issue by nimrodical** [SteamRE/SteamKit#224]
So this snippet is pretty much all that's relevant here, I noticed that it was throwing InvalidPassword, sure my password was correct, I tried from Steam itself and got the following:

![Image of error](http://i.imgur.com/ChT2mDL.png)

Here's the code:
```javascript

client.on('error', function(eresult){
		console.log("Error: "+eresult);//Error: InvalidPassword
});
```

For more information, the details object passed was:
```
	 var details = {
		"accountName": "username",
		"password": "password",
		"rememberPassword":true
	};

```
This was outputted and then tested on Steam to get the picture above yet still thrown InvalidPassword, I've confirmed this isn't an issue with my code.

I'm assuming that either **Steam.EResult.AccountLoginDeniedThrottle** or **Steam.EResult.RateLimitExceeded** should be the returned EResult here, am I missing something?

**Comment by VoiDeD** [comment]
Based off the code, you're probably looking for [node-steam](https://github.com/seishun/node-steam).

That said, you likely want to set the `supports_rate_limit_response` field on the logon protobuf, however that's done with node-steam.
