### ISSUE TITLE
Update GC protos

### ISSUE THREAD

**Issue by bartico6** [SteamRE/SteamKit#225]
Mainly asking about TF2 protos - new actions that can be done on items, like festivizing, also removing gifter's name. IIRC you do it almost automagically (autogenerated with a program) so this shouldn't be a problem :)
Thanks in advance guys, keep up the great work on the project <3

**Comment by Netshroud** [comment]
I've updated the protobufs but there doesn't appear to be anything new related to what you're asking about. It may be re-using existing messages, use NetHook2 to figure out what TF2 is doing.

**Comment by DoctorMcKay** [comment]
Removing gifter's name is most likely [`k_EMsgGCRemoveGiftedBy`](https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/tf/econ_gcmessages.proto#L169) and [`CMsgGCRemoveCustomizationAttributeSimple`](https://github.com/SteamRE/SteamKit/blob/18b045fe600da482f7a5b5e17c65a7f41b749d43/Resources/Protobufs/tf/base_gcmessages.proto#L448) (or really any protobuf with a `uint64 item_id = 1;`).

Festivizing is most likely [`k_eMsgGCApplyXifier`](https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/tf/econ_gcmessages.proto#L77) and [`CMsgApplyToolToItem`](https://github.com/SteamRE/SteamKit/blob/18b045fe600da482f7a5b5e17c65a7f41b749d43/Resources/Protobufs/tf/base_gcmessages.proto#L508). I'm unsure about the ApplyXifier part here though.

Really though use NetHook2 to find out.
