### ISSUE TITLE
Somewhat port

### ISSUE THREAD

**Issue by Stilldabomb** [SteamRE/SteamKit#227]
https://github.com/yaakov-h/SKSteamKit -- haven't looked into the comparison too much but it says it's based off of SteamKit, thought I'd suggest it.

**Comment by Netshroud** [comment]
Suggest it for what purpose?

**Comment by Stilldabomb** [comment]
For it to be added to the "ports" page.

**Comment by Netshroud** [comment]
It was last updated nearly 3 years ago. I don't see any value in adding it at this point - whilst some of the other ports listed are also old and seemingly abandoned, they weren't at the time.

If the owner definitely wants it added, I'll reevaluate.
