### ISSUE TITLE
Voice chat

### ISSUE THREAD

**Issue by Rottweiler** [SteamRE/SteamKit#228]
Would it be possible to stream audio into the voice communication in group chats? I'd love to see this implemented.

Great job so far everyone.

**Comment by Netshroud** [comment]
It's definitely possible, but I have no idea how it works.

**Comment by JustArchi** [comment]
It's too much to ask, but if somebody ever found out how it works or even implemented a way to use it e.g. with PulseAudio as a source for voice chat for the bot, I couldn't express my grattitude.

**Comment by Netshroud** [comment]
I did look into it for a short period but it's mostly out-of-band communication utilising a whole alphabet soup of third-party libraries. Being out of band, it's largely out of scope of SteamKit.
