### ISSUE TITLE
Deserialize a bytes row

### ISSUE THREAD

**Issue by jacobs100500** [SteamRE/SteamKit#230]
Hello. I use NetHookAnalyzer to debug a Steam messages. Some messages have field with bytes row value. For example, the ClientServiceCall message return this data:

sysid_routing: F1010201
call_handle: 471067433
module_crc: 4262202477
module_hash: <null>
function_id: 4
cub_output_max: 4096
flags: 3
callparameter: (a bytes row)

I have tried deserialize "callparameter" through KeyValue class, but the method TryReadAsBinary returned False. Maybe need use MessageObject, but I don't know which fields uses in this message. Is there any schemas for similar messages? How I can detect when use some method of deserialize?
Attachment:
Converted to C# bytes "callparameter"
byte[] data = new byte[] { 0x0C, 0x20, 0x57, 0x04, 0x01, 0x00, 0x00, 0x00, 0xCB, 0x1B, 0xBD, 0x07, 0x0F, 0x78, 0x5D, 0x0A, 0x26, 0xE1, 0x82, 0x6B, 0x78, 0x01, 0x07, 0x1D, 0x26, 0xE1, 0x82, 0x6B, 0x78, 0x01, 0x07, 0x1D, 0xF8, 0x1D, 0xC1, 0xC0, 0xB6, 0xAB, 0x2D, 0x7A, 0x85, 0xE1, 0x37, 0x4B, 0x22, 0xF7, 0x10, 0x5D, 0xBE, 0x85, 0x92, 0xED, 0x98, 0x0B, 0x08, 0x7F, 0xD4, 0x73, 0x09, 0x69, 0x40, 0xFD, 0xD5, 0xE7, 0xAC, 0xEF, 0x1F, 0x09, 0x64, 0x72, 0x9E, 0xF6, 0x8C, 0x6D, 0xAB, 0x3F, 0x11, 0xA4, 0xA7, 0x16, 0x44, 0x76, 0x1F, 0x07, 0x51, 0xAD, 0xFB, 0xE7, 0x91, 0x16, 0x98, 0xFF, 0x17, 0xC8, 0xD0, 0xF4, 0x60, 0xCF, 0xFD, 0x59, 0x6E, 0x66, 0xE1, 0xE8, 0xF0, 0x31, 0x7A, 0xFB, 0xAE, 0x33, 0xF4, 0x23, 0x30, 0x69, 0x07, 0x22, 0xBD, 0x90, 0x20, 0x27, 0xAE, 0x43, 0x35, 0x1D, 0xA3, 0x71, 0x48, 0x4F, 0xC7, 0x5C, 0xC3, 0xC1, 0x53, 0xDB, 0x1C, 0xE9, 0x31, 0xBC, 0xDE, 0xA3, 0xE6, 0x78, 0xBC, 0xB3, 0xAA, 0x31, 0x0E, 0xB0, 0xB8, 0x6F, 0xDA, 0xF2, 0x03, 0xE4, 0xA7, 0xB3, 0x3B, 0xC8, 0x34, 0x4D, 0x1D, 0x96, 0x84, 0x8F, 0xE6, 0x6C, 0xDB, 0xBC, 0x61, 0xF6, 0xB6, 0x60, 0xBA, 0x9D, 0xAA, 0x1C };

**Comment by Netshroud** [comment]
This is not KeyValues - or likely anything we can read. From my experience with `ClientServiceCall` and it's friends, this is encrypted.

What are you trying to do?

**Comment by jacobs100500** [comment]
I'm trying to connect to the game as it does Steam. When I sending the message CMsgClientGamesPlayed with EMsg type ClientGamesPlayedWithDataBlob, then Steam send me  ClientServiceCall. I think that it is necessary to respond to it.

**Comment by Netshroud** [comment]
That depends what you're doing exactly. This is one of the messages that powers VAC, so it could be safe to ignore or you could end up getting your account banned; it's impossible to tell ahead of time.

So far, though, it's been quite safe to ignore. So far.
