### ISSUE TITLE
Chat logger without destroying the Steam Client's friend connection

### ISSUE THREAD

**Issue by Pugsworth** [SteamRE/SteamKit#231]
I'm in the process of migrating a project from node-steam to C# SteamKit, but I've ran into an issue.
Upon logging in to the same account as one already on the Steam Client, the friends connection in the Steam Client closes until the client is restarted.
This didn't happen with node-steam.

I'm unsure if this is just a config/option issue or if there is a bigger underlying issue with how this library works compared to node-steam.

I've done a bit of searching around and cannot find anything useful for my intended goal.
Any assistance is appreciated.

**Comment by Netshroud** [comment]
See #217.

**Comment by Pugsworth** [comment]
Oh thank you very much.
