### ISSUE TITLE
Unable to logon to Steam: NoConnection / Invalid

### ISSUE THREAD

**Issue by merowing** [SteamRE/SteamKit#233]
Hello guys.
When I trying to connect with invalid authenticator code I trying to reconnect again and I get this error.
I must close the application to try connect again.

How to resolve this? How don't close the app to retry connect?
Thanks

**Comment by Netshroud** [comment]
IIRC if you fail a logon, Steam disconnects you. Listen for the `DisconnectedCallback` and handle this.

You will need to reconnect before you can try again to log in.
