### ISSUE TITLE
Matchmaking-Rank in CS:GO

### ISSUE THREAD

**Issue by sKeLeTr0n** [SteamRE/SteamKit#235]
Has someone figured out how to get the Matchmaking-Rank of a Friend in CS:GO with SteamKit?

**Comment by Netshroud** [comment]
Possibly, but specific uses of the GC are outside of the scope of this project. You can use NetHook2 to figure out how CS:GO does it (if CS:GO does indeed do it).

If CS:GO doesn't do it, you're probably SOL.
