### ISSUE TITLE
Steam goes offline whenever bot is running

### ISSUE THREAD

**Issue by arslanmkhan** [SteamRE/SteamKit#238]
I am trying to run DotaMatchRequest project and steam side by side but when ever i run bot steam goes offline and i am unable to play the game online.

**Comment by Netshroud** [comment]
Yes, it's known to do that. It's not much more than a sample project for the GC.

See `LogOnDetails.LoginID`.

**Comment by JustArchi** [comment]
That's why you need to use ```LoginID``` property I recently introduced.

I suggest to set it to ```MsgClientLogon.ObfuscationMask```, as done in [ASF](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs#L44).
