### ISSUE TITLE
Different messages for steam client and bot

### ISSUE THREAD

**Issue by arslanmkhan** [SteamRE/SteamKit#239]
Hello, 
I am trying to receive game coordinator messages outside of steam client. I want my client and steam client to receive same messages. here is my code of subscription to GC callbacks

`callbackMgr.Subscribe<SteamGameCoordinator.MessageCallback>( OnGCMessage );`

my understanding is after that i should be able to receive all gc call backs in OnGCMessage.  but i am receiving none of it.

also nethook dump of my client and steam client is different could that be the issue?

**Comment by Netshroud** [comment]
If I'm understanding you correctly, you're expecting that a SteamKit connection will receive all the GC messages that your Steam Client does, at the same time?

**Comment by arslanmkhan** [comment]
Yes thats what i would like to acheive

**Comment by Netshroud** [comment]
That's not how the Game Coordinator works. Each connection has it's own session and receives its own messages.

**Comment by arslanmkhan** [comment]
Hmm, i just want to accept or decline match requests outside of the steam client kindly let me know if its possible

**Comment by Netshroud** [comment]
I don't think it is without hooking the game client, which is waaaaay off topic and out of scope.
