### ISSUE TITLE
Sending game coordinator message outside of steam client

### ISSUE THREAD

**Issue by arslanmkhan** [SteamRE/SteamKit#240]
I am Trying to accept or decline the match outside of steam client. After tracking the match found event i am using following code to decline the match request.

`var requestMatch = new ClientGCMsgProtobuf<CMsgReadyUp>((uint)EDOTAGCMsg.k_EMsgGCReadyUp); `
`requestMatch.Body.state = DOTALobbyReadyState.DOTALobbyReadyState_DECLINED;`
            
`gameCoordinator.Send(requestMatch, APPID);`

server isnt accepting this. kindly let me if its possible or not

**Comment by xPaw** [comment]
You're misunderstanding what SteamKit is for. You can't use it to send packets on an existing open Steam client connection. Your previous issue had the same question, and was closed for being out of scope of the project.

**Comment by arslanmkhan** [comment]
Yes i totally understood it. I Know i cannot use it to send packages on an already open connection. and i am not trying to achieve it anymore. I am sending packages on a new connection. I ran a simple test through which i was initiating start find match command through my client which was successful. Steam client gave me the message that i have selected too many regions. this shows that i can send GC messages to server from my own client and server can accept that. only problem is i have to give selected regions in command too. 

now coming back to my current question If i can send start finding match command outside of client then why cant i send decline match command outside of steam client. 

I personally think that either declining match request works differently than start finding match command or i am not sending all the data in message. my logic of sending data can also be wrong. I got a feeling that i need to send "ready_up_key" too

I am not asking for any game related help neither i am asking for providing a solution. I am just asking if the piece of code i wrote is correct or not. if it is then am i missing any data from it?. Which in my opinion lies within the scope of project. may be I am wrong as i am new and don't understand steamkit perfectly and you guys have spent lot of time on it

Any help would be appreciated
Thanks

**Comment by JustArchi** [comment]
You ask about reverse-engineering of dota 2, which is in fact game knowledge and it's **totally out of the scope of SK2**. SK2 is a tool - it provides you with generic functions and nother methods required to do the thing, but the whole logic as in which packets to send, what they contain, in what orders, and how to react to everything - relies on you, and developers here most likely never ever tried the thing which you want to achieve, and even if they did - it's out of the scope of this project.

**Comment by arslanmkhan** [comment]
Okay my bad. will you please redirect me to a place where i could ask this question

**Comment by SinZ163** [comment]
@arslanmkhan There is already an "extention" of sorts for Steamkit to be able to talk to the dota GC at [paralin/Dota2](/paralin/Dota2), it doesn't let you mess with your normal connection, but it allows you to more easily communicate with the GC and has a bunch of utility methods to do common actions
