### ISSUE TITLE
Automatically join SteamGroup chat on connect?

### ISSUE THREAD

**Issue by immastoner** [SteamRE/SteamKit#241]
Is this possible? If so how would I go about doing it? I cannot find out how.

**Comment by JustArchi** [comment]
```SteamFriends.JoinChat(XXXXX);``` in ```OnLoggedOn()``` ?

**Comment by cghippo** [comment]
JoinChat doesn't exist though?

**Comment by cghippo** [comment]
Sorry, I haven't played with CS in quite awhile.

**Comment by JustArchi** [comment]
***[Of course it does, I'm using it](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs#L1019)**

**Comment by cghippo** [comment]
http://imgur.com/rFkw94q

**Comment by cghippo** [comment]
And I have 1.7.0

**Comment by JustArchi** [comment]
Check out provided examples because I feel like you don't have any idea what you're doing.

**Comment by cghippo** [comment]
Wow sorry I wasn't even reading the error haha. My bad dude. Thanks :)
