### ISSUE TITLE
Need help with receiving private messages

### ISSUE THREAD

**Issue by rjmig88** [SteamRE/SteamKit#243]
I'm able to log into steam great using the server list example. I'm able to send private friend messages with ease. I don't seem to be able to receive any private friend messages though. My bot is always shown as offline on steam even though it can send messages, change its display name, get the friends list and persona state changes, and other steam functionality. Does the bot need to appear online to receive messages? If so, how do I go about doing that? I've tried ensuring LoginID is unique. Here is the code I have setup for the callback:

```
manager.Subscribe<SteamFriends.FriendMsgCallback>(OnMessageReceived);

static void OnMessageReceived(SteamFriends.FriendMsgCallback callback)
{
            Log.Info("Got callback: " + callback);
}

```

I've tried both FriendMsgCallback and ChatMsgCallback. Is there any sort of keep alive or heartbeat I need to send to steam to make sure I stay online?

Thanks

**Comment by Netshroud** [comment]
Are you [setting your persona state](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/Handlers/SteamFriends/SteamFriends.cs#L98-L118) to Online?

**Comment by rjmig88** [comment]
I was not! Thank you! Now the bot appears online and is receiving friend messages perfectly. Thank you so much! :)
