### ISSUE TITLE
Set profile to playing game.

### ISSUE THREAD

**Issue by linkjay1** [SteamRE/SteamKit#244]
I want to be able to set my profile to be playing a game by the App ID. An example can be found in the Steam package in the Node.js Javascript API.

**Comment by JustArchi** [comment]
https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiHandler.cs#L163

**Comment by linkjay1** [comment]
You are a beautiful person <3

Will test this out ASAP

**Comment by linkjay1** [comment]
Now, using that function i have turned it into.

`public static void playGame(int gameID) {

			var request = new ClientMsgProtobuf<CMsgClientGamesPlayed>(EMsg.ClientGamesPlayed);

			    request.Body.games_played.Add(new CMsgClientGamesPlayed.GamePlayed 
                {
				    game_id = new GameID(gameID),
			    });
			}

			Client.Send(request);
		}`

What i can't figure out is, what does Client.Send do? It has to be a custom function because it is not being found. Can you link the source to that, or maybe give me and alternate to that?

**Comment by JustArchi** [comment]
That function won't work without a custom handler that you should add.

Check out Program.cs for "ArchiHandler" and add all required references.

**Comment by JustArchi** [comment]
Alternatively, you can replace ```Client``` with any instance of ```SteamClient``` if you don't want to add a custom handler.

**Comment by Netshroud** [comment]
That's on SteamClient. See https://github.com/SteamRE/SteamKit/blob/master/Projects/DotaMatchRequest/DotaMatchRequest/DotaClient.cs for full example of setting yourself as in-game.
