### ISSUE TITLE
CMsgClientAMGetClanOfficersResponse returns InvalidParam

### ISSUE THREAD

**Issue by zerox56** [SteamRE/SteamKit#245]
So after messing around for a few day, I still can't fix this problem.

I found a closed and only issue here related to sending and recieving the ClanOfficers message.
I used the code that the user @JustArchi posted since it's basically all I need (Thanks btw). Though the problem in that issue was that the user recieved a EResult message TimeOut. But whatever I do, I only get the EResult message InvalidParam. Trying and recieving other messages works well. For example the EMsg ClientFriendProfileInfo.

I tried using the Emsg AMGetClanOfficers and AMGetClanOfficersResponse as well. But that didn't help. 

From what I can tell. The EResult message InvalidParam happens when the Emsg doesn't belong to the ClientMsgProtobuf type. But I may be wrong! Still new with SteamKit2. But couldn't find any solutions and my attempts to fix it didn't help. 

The piece of code that is commented is for setting some info that wasn't send with the message, but I did recieve it in the response. Thought that had something to do with it, but I guess not.

If someone can help me with this problem. That would be great!

Also part of the code didn't want to get into the code tag. Couldn't fix it. Sorry about that.

```
    public class ClanMemberInfo : ClientMsgHandler
    {
        public class OnGetClanOfficersCallback : CallbackMsg
        {
            public EResult Result { get; private set; }

            internal OnGetClanOfficersCallback(EResult res)
            {
                Result = res;
            }
        }
        public void getClanOfficers(SteamID clanID, SteamID chatterID)
        {
            var request = new ClientMsgProtobuf<CMsgClientAMGetClanOfficers>(EMsg.ClientAMGetClanOfficers);
            request.Body.steamid_clan = clanID;
            //request.Header.Proto.client_sessionid = Client.SessionID.Value;
            //request.Header.Proto.steamid = Client.SteamID;
            //request.SteamID = Client.SteamID;
            //request.SessionID = Client.SessionID.Value;
            Client.Send(request);
        }

        public override void HandleMsg(IPacketMsg packetMsg)
        {
            switch (packetMsg.MsgType)
            {
                case EMsg.ClientAMGetClanOfficersResponse:
                    handleClanOfficersResponse(packetMsg);
                    break;
                case EMsg.AMGetClanOfficersResponse:
                    handleClanOfficersResponse(packetMsg);
                    break;
            }
        }

        private void handleClanOfficersResponse(IPacketMsg packetMsg)
        {
            var response = new ClientMsgProtobuf<CMsgClientAMGetClanOfficersResponse>(packetMsg);
            EResult result = (EResult)response.Body.eresult;
            Client.PostCallback(new OnGetClanOfficersCallback(result));
        }
    }
```

**Comment by Netshroud** [comment]
Surround a code block with 3 backticks, or inline code with just one.

```
look
a
block
of
code
surrounded
by
three
backticks
```

here is `some inline code` using just one backtick


-------


Are you sure that your `clanID` is a valid clan ID? Is that supposed to be the 64-bit ID, or just the 32-bit account ID?

**Comment by JustArchi** [comment]
I can show my up-to-date method I'm using in my ArchiBoT.

For simplicity, I include only core parts.

Program.cs - How I launch the request
```
private static async void OnChatEnter(SteamFriends.ChatEnterCallback callback) {
	ArchiHandler.GetClanOfficers(callback.ClanID);
}
```

In above example I'm launching it on chat enter, but it can be any other event, as long as you provide ```ulong``` to ArchiHandler. Next...

ArchiHandler.cs - Sends request
```
internal void GetClanOfficers(ulong clanID) {
	if (clanID == 0) {
		return;
	}

	var request = new ClientMsgProtobuf<CMsgClientAMGetClanOfficers>(EMsg.ClientAMGetClanOfficers);
	request.Body.steamid_clan = clanID;

	Client.Send(request);
}
```

I have my own custom handler for SteamClient, so I have everything in one place, but if you need only thatone part then simply you can change ```Client.Send()``` into ```steamClient.Send()``` which is based on ```SteamClient``` instance.

Lastly the code that is responsible for receiving answer:
```
private static async void OnPersonaState(SteamFriends.PersonaStateCallback callback) {
	SteamID steamID = callback.FriendID;
	SteamID sourceSteamID = callback.SourceSteamID;
	string steamNickname = callback.Name;
	EPersonaState personaState = callback.State;
	EClanRank clanRank = (EClanRank) callback.ClanRank;
	
	if (sourceSteamID.IsClanAccount) {
		// ONLY THIS CASE has EClanRank properly set
	}
}
```

Of course to make above work you also need to be listening for ```PersonaStateCallback ```.

I totally ignore ```EResult``` returned by request itself, because it doesn't make sense (neither my old ```Timeout``` made, nor your one). I just listen for actual answer.

Hope it helped.

**Comment by zerox56** [comment]
I did a double check through my code. And it seems like I've been mistaken clanID with chatroomID here and there. After I changed it, I got the EResult Timeout which I ignored. I already implemented PersonaStateCallback. It is not skipping the if statement in the method now..The only extra thing I've added is to make the method async. Atleast I was on the right track.

Anyhow I cleaned up my code and made sure I used clanID and chatroomID correctly. Everything seems to be working again and the same goes for this custom handler. I'm going to keep the custom handler since I might have more use for it later on.

Thanks for your help you two. Cleared up some things.

**Comment by JustArchi** [comment]
> It is not skipping the if statement in the method now

It depends on your usage. If you don't want to get "wrong" unset ```EClanRank``` which are there in case of "normal" callbacks then you need to add an if, otherwise you can e.g. ask of clan rank user X in clan Y, and get unexpected response in that callback because given user changed his state to online. That's why I say that it's important if you want to be sure that what you're receiving is correct.
