### ISSUE TITLE
Handle EDOTAGCMsg.k_EMsgGCToClientSteamDatagramTicket Callback

### ISSUE THREAD

**Issue by studentworksl3** [SteamRE/SteamKit#248]
I want to connect to a lobby, which worked out fine. When I try to start the server it just says "Waiting for players to load" and the client gets the EDOTAGCMsg.k_EMsgGCToClientSteamDatagramTicket Message. 
I don't know how to respond to that request.

**Comment by Netshroud** [comment]
SteamKit exposes the GC for you to use, but for any specifics you're on your own.

You can try using NetHook2 and NetHookAnalyzer to see what Dota 2 does and mimic that.
