### ISSUE TITLE
[question] Non-Steam games - setting as in-game?

### ISSUE THREAD

**Issue by bartico6** [SteamRE/SteamKit#250]
Simply put, I'm trying to display an account as in non-steam game.
Tried this, although I have no idea if I'm going the right way.
![CodeSnippet](http://i.imgur.com/IvTgFvS.png)
I've noticed while using Steam's console
![HERE](http://i.imgur.com/EkOkdNx.png)
that the appid is 0 for nonsteam games, but I don't know where to "stuff" that string so it displays..
(right now, with passing a **new int [0]** and **new string[] {"TESTING"}** as the parameters, the account is online (not in-game as expected)
I've noticed there's quite a bit of **other vars** though idk what to do with them
![AdditionalVars](http://i.imgur.com/8i5dGUb.png)
Any ideas guys? Please help :3
@VoiDeD @Netshroud

**Comment by JustArchi** [comment]
I have that part on my TODO list for reverse-engineer, so if nobody will help you in a few hours, I will eventually later today :3.

**Comment by Ne3tCode** [comment]
Try [15190414816125648896](https://github.com/DoctorMcKay/node-steam-user/blob/master/components/apps.js#L24)

**Comment by bartico6** [comment]
Nope, doesn't work. Still says it's "Online"

**Comment by JustArchi** [comment]
Just wrote my own piece of code:

```
		internal void PlayGame(string gameName) {
			var request = new ClientMsgProtobuf<CMsgClientGamesPlayed>(EMsg.ClientGamesPlayed);

			var gamePlayed = new CMsgClientGamesPlayed.GamePlayed();
			if (!string.IsNullOrEmpty(gameName)) {
				gamePlayed.game_id = 12350489788975939584;
				gamePlayed.game_extra_info = gameName;
			}

			request.Body.games_played.Add(gamePlayed);

			Client.Send(request);
		}
```

Usage: ```PlayGames("asd")``` for showing as playing non-steam game "asd", ```PlayGames(null)``` for resetting status.

**Comment by Ne3tCode** [comment]
9223372036888330240 (0x8000000002000000) works for me too. This mean:
[`AppID`](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Types/GameID.cs#L129) == 0
[`AppType`](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Types/GameID.cs#L146) == [`Shortcut`](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Types/GameID.cs#L35)
[`ModID`](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Types/GameID.cs#L163) high bit == 1 // important

**Comment by JustArchi** [comment]
Nice find @Ne3tCode!

My code looks much better now:
```
		internal void PlayGame(string gameName) {
			var request = new ClientMsgProtobuf<CMsgClientGamesPlayed>(EMsg.ClientGamesPlayed);

			var gamePlayed = new CMsgClientGamesPlayed.GamePlayed();
			if (!string.IsNullOrEmpty(gameName)) {
				gamePlayed.game_id = new GameID() {
					AppType = GameID.GameType.Shortcut,
					ModID = uint.MaxValue
				};
				gamePlayed.game_extra_info = gameName;
			}

			request.Body.games_played.Add(gamePlayed);

			Client.Send(request);
		}
```

This is much better than magical number :+1:

**Comment by Netshroud** [comment]
https://github.com/SteamRE/open-steamworks/blob/master/Open%20Steamworks/CGameID.h#L91-L107

**Comment by bartico6** [comment]
I should've closed this 9 days ago. I'm sorry guys, closing.
