### ISSUE TITLE
Some questions about steamkit

### ISSUE THREAD

**Issue by JeromeHuang** [SteamRE/SteamKit#251]
I study the steamkit for a couple of days. I know we can log on through steamkit and get the userinfo. I wonder if we can buy games through steamkit, get the price of the game through it, get the information of steam card?
Thanks!

**Comment by Netshroud** [comment]
Purchases are done via the storefront, and I believe all related info (e.g. pricing) is likewise only available through the store.

What's a "steam card"?

**Comment by JeromeHuang** [comment]
steam card means the steam cd key.

**Comment by Netshroud** [comment]
See #68 for information on CD keys.

**Comment by JeromeHuang** [comment]
OK, thanks!

**Comment by VoiDeD** [comment]
Closing since I believe this was resolved.
