### ISSUE TITLE
How can I get the code for authorization from steam guard

### ISSUE THREAD

**Issue by IvanOpenProject** [SteamRE/SteamKit#253]
How can I get the code for authorization from steam guard?

I use Sample5_SteamGuard, i can auth, but i don't how to get auth key (which changes every 20 seconds).

How do I get the key?

**Comment by JustArchi** [comment]
SK2 doesn't have any built-in support for acting like mobile device. What you're looking for is a tool like https://github.com/geel9/SteamAuth

Unless you're asking how you can **put** your 2FA token for logging in. In this case it's easy - https://github.com/SteamRE/SteamKit/blob/master/Samples/5.SteamGuard/Program.cs#L131 + https://github.com/SteamRE/SteamKit/blob/master/Samples/5.SteamGuard/Program.cs#L163

**Comment by IvanOpenProject** [comment]
Thank you for helping SteamAuth, what I need

**Comment by IvanOpenProject** [comment]
Maybe you know a lib for receiving, sending and confirming orders for a trade?

**Comment by JustArchi** [comment]
Yes, the lib I linked you above does offer all of those functions.

ASF makes use of some of those features, and you can take a look at it for example code that integrates SteamAuth, but it has different concept in mind.

**Comment by IvanOpenProject** [comment]
Thank you
