### ISSUE TITLE
[Bug] ClientLogon is not being sent

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#254]
Recently I found out user of my ASF that for some reason couldn't log in to steam using my program based on SK2. Program would be stuck right after "Connected to steam!" which is handled in ```OnConnected()```. Program should then send ```SteamUser.LogOn```, but for some reason it does not.

I tried to make sure that it's not my own issue before filling this ticket, as I appreciate your time. I couldn't find any potential issue inside my code.

ASF log is following:
```
12.03.2016 00:44:31 [*] INFO: CheckForUpdate() <Main> Checking new version...
12.03.2016 00:44:32 [*] INFO: CheckForUpdate() <Main> Local version: 2.0.0.7 | Remote version: 2.0.0.7
12.03.2016 00:44:32 [*] INFO: CheckForUpdate() <Main> ASF will automatically check for new versions every 24 hours
12.03.2016 00:44:32 [*] INFO: RefreshCMs() <Main> Refreshing list of CMs...
12.03.2016 00:44:32 [*] INFO: RefreshCMs() <Main> Success!
12.03.2016 00:44:32 [*] INFO: Main() <example> Not starting this instance because it's disabled in config file
12.03.2016 00:44:32 [*] INFO: Start() <first> Starting...
12.03.2016 00:44:32 [*] INFO: Main() <minimal> Not starting this instance because it's disabled in config file
12.03.2016 00:44:32 [*] INFO: OnConnected() <first> Connected to Steam!
```

You can check yourself that there is no logical reason why request would not be sent: **[source](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs#L1065-L1094)**. There's no error or exception, program just stays stuck without progressing further with logging in.

I asked user to make a debug log (which adds ```DebugNetworkListener``` to the process), to perhaps check what is going wrong. I launched NetHookAnalyzer2, but I couldn't find anything suspicious in the log:

![image](https://cloud.githubusercontent.com/assets/1069029/13719164/2498b080-e7f2-11e5-862d-38c0300f08e9.png)

Normally ```ClientLogon``` should happen next:
![image](https://cloud.githubusercontent.com/assets/1069029/13719171/3bbbdf4e-e7f2-11e5-93eb-3411dcee7328.png)

I'm clueless what the root issue might be. It's not global issue, as ASF works for majority of users - including me, on both my PC and my server. It doesn't make any sense to me why process would be stuck AFTER connecting to CM server. If callback manager was off - ```OnConnected()``` would not happen. If there was an error while trying to connect to steam CM - ```OnConnected()``` would return an error (and ```OnDisconnected()``` would happen too). If that issue was affecting more users than 1-2, especially me, I'd probably fix it myself.

Have you ever seen something like that? I'd be grateful for any tips or potential solutions to that issue, as I'm going through my own code for 7th time not being able to spot any race condition, logical problem or anything else that could cause such issue. Thank you in advance.

**Comment by azuisleet** [comment]
The only way we can diagnose this is with a DebugLog output. It will tell us where exactly the message is being discarded, if it is.

A shot in the dark is that your connection is being closed shortly after connecting. Normally this should be picked up and reported, but without a debuglog there's no way to tell.

**Comment by JustArchi** [comment]
I'm on it. Will let you know ASAP about the results. Thank you!

**Comment by JustArchi** [comment]
Got the debug log from affected user.

```
ServerList | Next server candidiate: 162.254.197.42:27021
TcpConnection | Connecting to 162.254.197.42:27021...
TcpConnection | Connected to 162.254.197.42:27021
CMClient | <- Recv'd EMsg: ChannelEncryptRequest (1303) (Proto: False)
CMClient | Got encryption request. Universe: Public Protocol ver: 1
CMClient | Sent -> EMsg: ChannelEncryptResponse (Proto: False)
CMClient | <- Recv'd EMsg: ChannelEncryptResult (1305) (Proto: False)
CMClient | Encryption result: OK
```

It's strange.

I compared it with mine and next should be:

```
CMClient | Sent -> EMsg: ClientLogon (Proto: True)
```

Is there anything else I could attach to perhaps help you with this issue?

Thank you in advance, I appreciate a helpful hand.

**Comment by azuisleet** [comment]
You're going to need more instrumentation around your call to SteamUser.LogOn. In particular, I would wrap the entire block in an exception handler, if by chance an exception is being missed.

**Comment by JustArchi** [comment]
I have **[unhandled exception handler](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Program.cs#L418)** which logs any unhandled exception to the log file before aborting the process. If there was any exception being thrown I'd see it in the log and fix myself prior to creating an issue here, as I always make sure that the issue is not in my code before I start searching for a culprit somewhere else. I'll however add a try catch and some extra debug as you suggested, just in case.

**Comment by JustArchi** [comment]
I didn't believe it myself but we got it.

```
14.03.2016 20:08:06 [*] INFO: OnConnected() <first> Logging in with default behaviour...
14.03.2016 20:08:06 [!] EXCEPTION: OnConnected() <first> One or more errors occurred.
14.03.2016 20:08:06 [!] StackTrace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at SteamKit2.HardwareUtils.GetMachineID()
   at SteamKit2.SteamUser.LogOn(LogOnDetails details)
   at ArchiSteamFarm.Bot.OnConnected(ConnectedCallback callback)
14.03.2016 20:08:06 [!] EXCEPTION: OnConnected() <first> The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (Exception from HRESULT: 0x80070422)
14.03.2016 20:08:06 [!] StackTrace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at SteamKit2.WindowsInfoProvider.WmiQuery(String queryFormat, Object[] args)
   at SteamKit2.WindowsInfoProvider.GetDiskId()
   at SteamKit2.HardwareUtils.GenerateMachineID()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

How the hell is it possible that try catch caught that exception while my unhandled exception handler did not? No idea, you learn something new every day using C#.

Any idea what to do now? I see that the issue is deep in SK2 library.

**Comment by Netshroud** [comment]
You probably need to listen for `TaskScheduler.UnobservedTaskException` as well as the event on `AppDomain`, considering that you're using a `Task` around this function for fire-and-forget [here](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs#L395).

Looks like the Windows service that powers WMI is stopped and/or disabled. @VoiDeD?

**Comment by JustArchi** [comment]
Just wanted to let you know that as an experimental bugfix I removed ```GenerateMachineID()``` from LogOn, and everything works fine. Of course, I understand that it works fine because Steam does not yet enforce checking MachineID, and SK2 uses it as a bulletproofing for future, so I consider it experimental hack rather than any proper fix.

If you need tests, just compile ```SteamKit2.dll``` for me, and I'll include it in my project and send to affected user to confirm if the issue is fixed or not.

Thank you guys very much for everything what you're doing here. I'm happy that one of my projects helped somehow to spot library bug, and I'm happy that I didn't waste your time with bug which might be related only to my own code :+1:

**Comment by Netshroud** [comment]
This should be fixed in 32c1a6f and therefore the next release.

**Comment by JustArchi** [comment]
Thanks!

Would be really nice if next release was released soon, as this is somehow important bugfix for me, although it's up to you however you want to schedule your releases :+1:

**Comment by Tsunamical** [comment]
https://github.com/JustArchi/ArchiSteamFarm/blob/2.1.0.7/ArchiSteamFarm/GlobalConfig.cs#L107

Still needed?

**Comment by JustArchi** [comment]
Needed, SK 1.8.0+ solves the issue, and latest stable released one is 1.7.0. I could in theory compile latest master myself, but I don't want to do that and prefer to keep SK2 dependency fully on Nuget.

**Comment by Tsunamical** [comment]
Okay, my bad. Sorry for the notification. Thanks!

**Comment by Netshroud** [comment]
Yeah, @JustArchi, not need to spam @Netshroud about it. 😄 

I'd like to release 1.8.0 after #293 is merged, so whenever Azuisleet finishes and merges that.
