### ISSUE TITLE
Get Steam Notifications

### ISSUE THREAD

**Issue by Jakky187** [SteamRE/SteamKit#257]
How can I get Notifications like trade , comments etc?
Would be nice if I get some help with it^^

**Comment by JustArchi** [comment]
You need to implement them yourself.

A good starting example is in my ASF - https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiHandler.cs#L62

**Comment by Jakky187** [comment]
@JustArchi  Thank you !

**Comment by VoiDeD** [comment]
Closing since I believe this was resolved.
