### ISSUE TITLE
Is it possible to send GCRemoveItemName (1030) message?

### ISSUE THREAD

**Issue by TarasDev** [SteamRE/SteamKit#259]
Thats what I want to reproduce http://imgur.com/65dkINr. But unfortunately NetHook Analyzer don't show "Game Coordinator Message" in right column(outdated protobufs?)

**Comment by VoiDeD** [comment]
The GC message itself is present within the `payload` field of the body. I believe that NetHookAnalyzer will try to deserialize the payload most of the time, but it's not foolproof.

You may need to inspect that manually with a hex editor, or write some quick code that creates a `ClientGCMsgProtobuf<T>` from that byte stream. See https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/Handlers/SteamGameCoordinator/Callbacks.cs#L47.

**Comment by TarasDev** [comment]
I found a similar in dota protobuf https://github.com/SteamRE/SteamKit/blob/9367a602eec59783ab8e4bb70b64aa985f629058/Resources/Protobufs/dota/econ_gcmessages.proto#L645 but for some reason this message removed...

**Comment by psychonic** [comment]
The message in question isn't a protobuf message. SteamKit doesn't currently have any of the structures for any of these non-protobuf GC messages built-in.

**Comment by yaakov-h** [comment]
Closing as this has been answered (months ago).

**Comment by MakcStudio** [comment]
Hello everyone, I have a similar problem, I also can not understand how I should send this request?
![image](https://user-images.githubusercontent.com/41212099/69730509-43693d80-1139-11ea-89f2-23a8dc58af94.png)
