### ISSUE TITLE
Static server list?

### ISSUE THREAD

**Issue by paralin** [SteamRE/SteamKit#263]
Shouldn't this variable here:

https://github.com/SteamRE/SteamKit/blob/32c1a6f3794ba61554a3a38c94e339068b2633d3/SteamKit2/SteamKit2/Steam/CMClient.cs#L27

Be static?

That way the server connection information can be shared between clients, especially regarding the confidence values.

**Comment by Netshroud** [comment]
`public static SmartCMServerList Servers { get; private set; }`

It already is static.

**Comment by paralin** [comment]
@Netshroud I'm f*cking blind, forget it.
