### ISSUE TITLE
[HELP] How To Send Request / Get Response

### ISSUE THREAD

**Issue by Zaid-ED** [SteamRE/SteamKit#267]
Hello, i'm kind of new to the whole SteamKit, i need some help

so far i found how to initialize a request

``` C#
static void Main(string[] args)
{
ulong Param_S = 76561197960266237;
ulong Param_M = 0;
ulong Param_A = 5865522568;
ulong Param_D = 2657940228772002535;
var MyRequest = new SteamKit2.GC.CSGO.Internal.CMsgGCCStrike15_v2_Client2GCEconPreviewDataBlockRequest { param_s = Param_S, param_m = Param_M, param_a = Param_A, param_d = Param_D };
Console.WriteLine($"S: {MyRequest.param_s}\nM: {MyRequest.param_m}\nA: {MyRequest.param_a}\nD: {MyRequest.param_d}");
}

```

my question is How to send it ? and even if i do send it how do i get the response (iteminfo) ?

REALLY appreciate it if you would help me :)

**Comment by VoiDeD** [comment]
Check out the [Dota Match Request](https://github.com/SteamRE/SteamKit/tree/master/Projects/DotaMatchRequest/DotaMatchRequest) sample project for an idea of how to interact with a game coordinator server.

**Comment by Zaid-ED** [comment]
Thank you :D i will see if i ever any questions thanks :)
