### ISSUE TITLE
[Question] Using SteamKit2 while logged in

### ISSUE THREAD

**Issue by Rottweiler** [SteamRE/SteamKit#273]
Is there any way to use SteamKit2 to spoof what games you are in while you are logged into your regular Steam?

**Comment by JustArchi** [comment]
Yes - https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiHandler.cs#L191

**Comment by Rottweiler** [comment]
Thanks archi♥
