### ISSUE TITLE
can't get SteamID from username

### ISSUE THREAD

**Issue by saidaniwael** [SteamRE/SteamKit#279]
how to get steamID from just username
i tried everything but cant find solution
just i want to said if this not include in this project 
please add it
thinx all for this and hope you help me :)

**Comment by Netshroud** [comment]
There's no public mapping. The only way AFAIK is to log on as the user.

(Please don't do that.)

**Comment by saidaniwael** [comment]
then i need both username and password to get steam id ???

**Comment by Netshroud** [comment]
If you log in to Steam successfully, Steam tells you what your own SteamID is. So username, password, steam guard, authenticator, etc.

If you have a handful of your own accounts, you can find out your own SteamIDs programmatically, but it would be easier just to log into Steam and write them down.

If you have anybody else's account, the answer is no.

**Comment by saidaniwael** [comment]
ok thinx

**Comment by Rob--** [comment]
You could make a request to http://steamid.co, however I'm not sure if this is against their ToS:

Host: `http://steamid.co/`
Url: `/php/api.php`
Query: `{action: 'steamID', id: 'example'}`

`http://steamid.co/php/api.php?action=steamID&id=example`

**Comment by saidaniwael** [comment]
no im just have my email of my steam and want just to know my steamid because i give account for someone else and i dont want to make recovery

**Comment by JustArchi** [comment]
Then log in to that account using SK2-based ways and get steamID from ```OnLoggedOn``` callback.

**Comment by saidaniwael** [comment]
the problem is i dont have the password i just give my account to my friend but didnt change email and i dont remember steam id of the account and i want to cantact him 
im programmer and they tell me steamkit2 can help me with that

**Comment by saidaniwael** [comment]
if you can guys some one can help me or cantact me on my email saidaniwael265@gmail.com

**Comment by ardaozkal** [comment]
SteamKit can't help with this. Try this: https://help.steampowered.com/en/wizard/HelpWithLogin
