### ISSUE TITLE
Getting nothing from Interface

### ISSUE THREAD

**Issue by FindedLine** [SteamRE/SteamKit#280]
Hello,

I'm trying to get the current gameid of a player who is playing. (the code is only executed when player have a launched game).

`            
```
using (dynamic steamUserGetStats = WebAPI.GetInterface("ISteamUser", "MYDEVAPI"))
            {
                KeyValue steamUserStats = steamUserGetStats.GetPlayerSummaries( steamids: 76561198003752192);

                foreach (KeyValue appid in steamUserStats["players"].Children)
                {
                    Console.WriteLine("Playing: {0} .", appid["appid"].AsString());
                }
            }
```

But I have nothing... This code display: Playing . 
My dev API KEY is set (just delete it for the post).

Regards

**Comment by xPaw** [comment]
The field is `gameid`, not `appid`

**Comment by Netshroud** [comment]
You're looking for `"appid"`, but if you look at the actual API response, the key is `"gameid"`.

There's also an additional level of hierarchy for `GetPlayerSummaries/v0001`: response -> players -> player -> 0.

**Comment by FindedLine** [comment]
Replace with gameid, it's the same result.
If i'm trying this: steamUserStats["response"]["players"].Children) , nothing is shown.
