### ISSUE TITLE
Setting LogonDetails.LoginID

### ISSUE THREAD

**Issue by jammerxd** [SteamRE/SteamKit#281]
Hello,
if I set the LoginID, the sentury file fails to be created and the OnMachineAuth fails to be called.

**Comment by JustArchi** [comment]
Then you screwed something up because it works perfectly fine for me and thousands of users in ASF.

**Comment by jammerxd** [comment]
I did manage to get the sentury file made, however, it seems to be rejected every time and forces me to enter the steam guard key every time regardless if the file is made or not. Here is the source code for my script:
http://pastebin.com/yZkiGVWJ

**Comment by JustArchi** [comment]
Sentry file won't make you skip 2FA, use login key for that. And refer to my ASF if you need code sample. https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs

**Comment by jammerxd** [comment]
Perfect, thank you for your help!
