### ISSUE TITLE
NetHookAnalyzer2 compile error

### ISSUE THREAD

**Issue by nikitavondel** [SteamRE/SteamKit#283]
I am unable to compile NetHookAnalyzer2 within Visual Studio 2015 Community Edition as it gives me the following errors:

- _Error CS0400 The type or namespace name 'ProtoBuf' could not be found in the global namespace (are you missing an assembly reference?)_
- _Error CS0246 The type or namespace name 'Name' could not be found (are you missing a using directive or an assembly reference?)_
- _Error CS0246 The type or namespace name 'Value' could not be found (are you missing a using directive or an assembly reference?)_

I have cloned SteamKit via GitHub onto my own computer and opened NetHookAnalyzer2.sln with Visual Studio. I have then used NuGet to install the missing dependency which is protobuf-net version 2.0.0.668. Yet it still gives me errors and it seems like NuGet didn't install the proper depedencies.
[The SteamKit installation guide](https://github.com/SteamRE/SteamKit/wiki/Installation) tells me I should download this project via NuGet, however when I do , I end up not having a folder called NetHookAnalyzer2 , hence why I have used GitHub.

I am a complete newbie when it comes to C# and C++ projects, any sort of help would be extremely appreciated!

**Comment by svhero658** [comment]
You should change the compile order.

**Comment by stil** [comment]
Open SteamKit2/SteamKit2.sln solution first, build it.
Now, open NetHookAnalyzer2.sln and try buidling it again. The problem is because of this path:
https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/SteamKit2.csproj#L68
```xml
<HintPath>..\packages\protobuf-net.2.0.0.668\lib\net40\protobuf-net.dll</HintPath>
```

**Comment by nikitavondel** [comment]
Worked like a champ, cheers!
