### ISSUE TITLE
Steam says connection lost after nethook2.dll injected

### ISSUE THREAD

**Issue by svhero658** [SteamRE/SteamKit#284]
![connectionfailer](https://cloud.githubusercontent.com/assets/13400521/15784406/ee33ce1e-29e4-11e6-8765-875206be47ba.jpg)
I have tried Steam's both udp and tcp mode,but the error still occurs.Why?

**Comment by VoiDeD** [comment]
Possibly a regression from #282?

If you're building nethook2 from the current tip, try updating to the Steam client beta.

**Comment by svhero658** [comment]
Thank you for your help.Works great!

**Comment by rossengeorgiev** [comment]
@VoiDeD can confirm tip working on both release and beta
