### ISSUE TITLE
Getting SteamID64 From FriendMsgCallback?

### ISSUE THREAD

**Issue by Arefu** [SteamRE/SteamKit#286]
I'm trying to get a SteamID64 from the FriendMsgCallback, I have noticed you can go 

X.Sender.AccountID
or 
X..Sender

But neither of those return the ID I want the ID that you use to send a message out. E.G mine is: 76561198120XXXXXX (Cut out for "privacy") but I want a way to get it. Or how can I parse the Sender or AccountID to get that as a result

**Comment by Arefu** [comment]
Figured it out by using  SteamID User = new SteamID(Convert.ToUInt64(X));

**Comment by Netshroud** [comment]
What's `X` in the above? You shouldn't need to convert a `SteamID` to `ulong` and back.

**Comment by JustArchi** [comment]
Conversion can be done automatically, when you have a function accepting ```ulong``` then you can use either ```function(callback.Sender)``` or ```function(callback.Sender.ConvertToUint64())``` but first one is much cleaner.

**Comment by Arefu** [comment]
I found out how I can get my code to work doing it the way I want, it might not be clean, it might not be right. But it works. All is well again.

**Comment by Netshroud** [comment]
@Arefu It might not be clean, it might not be right, but we'd like to improve SteamKit so that it's easier for you and other developers do the right thing.

**Comment by Arefu** [comment]
SteamID User = new SteamID(Convert.ToUInt64(Miscellaneous.ARGS[1]));

Is how I converted the 64bit version, Args[1] is the SteamID in string format (to hard to explain as to why it's not originally uint)

Although it would be nice to have a SteamKit.SteamID.Parse(uint here)
