### ISSUE TITLE
Windows 10 Mobile compatible

### ISSUE THREAD

**Issue by hypixus** [SteamRE/SteamKit#290]
Hello

I am planning to create a project of unofficial Steam client for Windows Phone 10. Your SteamKit handles all tasks on computers, but I am not exactly sure of its behavior on phones. I heard of problems and exceptions caused by making connections with non-async methods. Is that true? If it is, what changes are indeed to make it work correctly?

**Comment by Netshroud** [comment]
Try it and see. Last time I tried, Windows Phone didn't have a close enough API surface.

**Comment by ObsidianMinor** [comment]
There's a Steam client now for Windows Phones.

But if you still need to make it, [SteamAuth](https://github.com/geel9/SteamAuth) has you covered.

**Comment by hypixus** [comment]
Thanks for help, closing.
