### ISSUE TITLE
Unhandled WinIOError (File Not Found) on ProtobufDumper

### ISSUE THREAD

**Issue by theokyr** [SteamRE/SteamKit#295]
Crashes violently when I pass a non existing file as an argument

**Comment by Netshroud** [comment]
Please define "violently". It should deal with it's own violence and exit cleanly [as per the `catch` clause here](https://github.com/SteamRE/SteamKit/blob/master/Resources/ProtobufDumper/ProtobufDumper/Program.cs#L28-L33).

**Comment by theokyr** [comment]
I'm a moron. Didn't notice it printed the stacktrace on the catch clause
