### ISSUE TITLE
unidentified emsg to GC?

### ISSUE THREAD

**Issue by salacryl** [SteamRE/SteamKit#298]
Hi,

I tried to get the data for chatcommands, but I get an wierd GCM ClientToGC:
[screenshot](https://i.imgsafe.org/558ca22107.jpg)

How to handle this?

**Comment by DoctorMcKay** [comment]
https://github.com/SteamRE/SteamKit/blob/2d2b2e420553710dfa3e774ca19450cf82452c14/Resources/Protobufs/dota/dota_gcmessages_msgid.proto#L590

**Comment by salacryl** [comment]
Ok ty for link me to the definition. But, the nethook2.dll injection does not told me that. Seems to be a Bug, isn't it?

**Comment by rossengeorgiev** [comment]
Recompile analyzer from master branch

**Comment by salacryl** [comment]
Ok, I did recompile from Master now. placed the new compiled Nethook2.dll on place. The ClientToGC vanished now, instead there is a ClientClanState and the response still is an unidentified ClientFromGC emsg 8091.

**Comment by rossengeorgiev** [comment]
You need to recompile SteamKit2.dll and NetHookAnalyzer2

**Comment by salacryl** [comment]
I did. The project of NetHookAnalyzer2 has a dependency compilation on SteamKit2.dll and I started NetHookAnalyzer2 from the release folder.

**Comment by rossengeorgiev** [comment]
Have you pulled the latest source from the repo?

**Comment by Netshroud** [comment]
Try the following:
1. Update code from master
2. Rebuild SteamKit2
3. Rebuild NetHookAnalyzer2
4. Open the same NetHook dump from your original screenshot

**Comment by san7550** [comment]
I have the same problem with csgo: [screen](https://cloud.githubusercontent.com/assets/5160391/16595503/e30156c8-4308-11e6-88d7-feee0c596d55.png)

**Comment by rossengeorgiev** [comment]
@san7550 did you complete the steps @Netshroud listed?

**Comment by san7550** [comment]
@rossengeorgiev yes

**Comment by Netshroud** [comment]
@san7550 9180 is `k_EMsgGCCStrike15_v2_GlobalChat`, but we don't have it in our protobufs yet. Hang tight...

**Comment by san7550** [comment]
@Netshroud Thanks!

**Comment by VoiDeD** [comment]
Closing as I believe this was addressed in 431fc347698de4bc2c36a2254ed691bd1bc6a6df.
