### ISSUE TITLE
IServerListProvider MemoryStorage suggestion

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#300]
From what I see currently we have ```FileStorageServerListProvider```, ```IsolatedStorageServerListProvider``` and ```NullServerListProvider``` server list providers. This is really cool, but I miss one more provider - ```MemoryStorage``` or similar, which would have public field of ```HashSet<IPEndPoint>``` or similar, and ```ServerListUpdated``` or similar event. This would allow developers to use it with serialization of their choice, and implement own logic for saving the state.

Background story: I like to keep everything related to my projects in one file, and I use JSON serialization for all fields. I coded something like **[this](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/JsonStorageServerListProvider.cs#L35)** and it works nicely, but you probably would like to implement that event globally for all ```IServerListProvider``` providers, and not only for that selected one, if at all.

If you're fine with my suggestion, I could create pull request with that I guess. Let me know what you think about that. Basically it'd be the same, just with public fields + non-sealed class (as SK2 is a library) and global event.

**Comment by Netshroud** [comment]
> This would allow developers to use it with serialization of their choice, and implement own logic for saving the state.

This is why you can create your own `IServerListProvider`. :smile: 

Why do you want to globally merge data from multiple SteamClient instances? I can't see it being that useful to most consumers.

(I'd say something about how Steam does it now, but as it stands now, Steam can only have one client anyway. I don't know what it does with gameserver accounts.)

**Comment by JustArchi** [comment]
> This is why you can create your own IServerListProvider. :smile:

And I'm grateful for that, I'm just wondering if my code can be useful for other devs too.

> Why do you want to globally merge data from multiple SteamClient instances?

Servers are chosen mostly based on localization (```CellID```) so it makes sense to me to reuse the list for all created ```SteamClient```s, although this is not that important - extra suggested provider would work the same as currently implemented ones, and whether it should be reused or not is up to consumer to decide.

Basically I thought it would be cool to add a target that could be further extended or reused for various different serializations, while not enforcing file location, which happens with ```FileStorageServerListProvider``` and ```IsolatedStorageServerListProvider```. But as I said that's only my idea and whether it's useful or not is up to you to decide :+1:

**Comment by Netshroud** [comment]
I take back what I said about merging data - it's been that way since day one in SteamKit.

So we have one global `IServerListProvider` already. All you've done then is translate our function calls into HashSet+event.

Why not just write a `JsonConfigServerListProvider` that updates your configuration directly? This seems a bit indirect.

(Also, `HashSet<string>` is already IEnumerable, your `.Select` call is wasteful. And why not make it `readonly`, why suppress the warning?)

**Comment by JustArchi** [comment]
> Why not just write a JsonConfigServerListProvider that updates your configuration directly? This seems a bit indirect.

Mostly because my configuration contains this + **[other](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/GlobalDatabase.cs#L58)** fields, The way it's implemented right now allows me to put it as extra field in my database, catch the event and issue my own ```Save()``` logic, which in my case is JSON serialization, but in other cases can be protobuf, binary one or anything.

> (Also, HashSet<string> is already IEnumerable, your .Select call is wasteful. And why not make it readonly, why suppress the warning?)

I agree, thanks for reminding me to correct **[this](https://github.com/JustArchi/ArchiSteamFarm/commit/02d3454d1b5d31c45b2043ca5a10b3c22bb91429)**. I'm still wondering why the cast must be implicit, as VS doesn't allow to just return Servers directly, but this is still better than enumerating.

Regarding readonly - ```JsonConvert``` requires ```setter``` to fill field with deserialized value, ```readonly``` field won't be deserialized and will keep it's default value, that's the only reason.

**Comment by JustArchi** [comment]
BTW, I should probably rename the class as it indeed was ```JsonStorageServerListProvider``` when I started coding it, but now it should probably be something like ```InMemoryServerListProvider``` or similar, as I moved JSON-specific logic outside of the class to make it more general and possible to add to SK2, hence this issue.

**Comment by Netshroud** [comment]
Explicit, not implicit. You need either a cast, or to explicitly call `Task.FromResult<IEnumerable<IPEndPoint>>(Servers)`, since `Task<HashSet<IPEndPoint>>` is not a implicitly convertible to `Task<IEnumerable<IPEndPoint>>`.

**Comment by JustArchi** [comment]
https://github.com/SteamRE/SteamKit/pull/304
