### ISSUE TITLE
Occasionally run into 100% CPU usage

### ISSUE THREAD

**Issue by stackia** [SteamRE/SteamKit#309]
I have a bot service running 50+ bots in a process. Every several days it runs into 100% CPU usage and no longer respond to any commands. I can only kill the process and restart it to bring bots back online.
This situation has been lasted for months, I carefully checked my program and every library I use, wondering if it hangs at SK2 library level. If I run fewer bots (5 bots in a process), the service can keep running for a long time without a restart.
I checked the logs, the problem doesn't seem to be related with any specific SK2 callback. I don't have an obvious way to reproduce this problem. The process just hangs every two or three days.
I reuse SteamClient instance to reconnect on unexpected disconnection.

Here is another ASF issue mentioning a somewhat similar situation:
https://github.com/JustArchi/ArchiSteamFarm/issues/318

**Comment by Netshroud** [comment]
Can you take a memory dump or otherwise inspect the stack to see what part of the process is being so CPU-intensive?

**Comment by stackia** [comment]
Looking into memory dump, found out this is not a SK2 related problem. Thanks for memory dump advice :+1:
