### ISSUE TITLE
Changing EMail Address via SteamKit?

### ISSUE THREAD

**Issue by awillinger** [SteamRE/SteamKit#31]
I have recently ran into the Problem that my old domain expired (to which my Bot's Account is linked to) and when logging in on a new Computer, I can't receive the Code-Email.

Since my current instance still got a valid sentry hash, I tried to change the EMail of the Account via SteamKit2 itself, but it doesn't work (I don't get an EMail)

That's what I have tried so far:

```
var msg = new ClientMsgProtobuf<CMsgClientEmailChange>(EMsg.ClientEmailChange4);
msg.Body.email = "mail@domain.com";
msg.Body.final = false;
msg.Body.password = "mypassword";
msg.Body.newmethod = true;
msg.Body.code = "";
client.Send(msg);
```

(email & password are correct, client is an instance of SteamClient)

Is this actually "intended" to work and if yes, what am I doing wrong?

**Comment by Leystryku** [comment]
It actually is possible http://i.imgur.com/tVU6vNQ.png

**Comment by Leystryku** [comment]
woops, late
