### ISSUE TITLE
Failing to connect on Mono

### ISSUE THREAD

**Issue by JamesTheCoder** [SteamRE/SteamKit#310]
I have written some code using SteamKit to connect to Steam and listen for updates. It runs fine on the Windows 10 PC I developed it on. However, on transferring it to a Raspberry Pi running Mono, it launches fine, but never actually connects to Steam. I get disconnection callbacks at regular intervals, suggesting they are timeouts, but that is all.

I have tried updating the SteamDirectory at launch, but to no avail.

**Comment by rossengeorgiev** [comment]
Does your Pi have internet access?

**Comment by JamesTheCoder** [comment]
Yes, it does. I can browse the internet with IceWeasel and other mono programs that require access to the internet are running okay.

**Comment by JustArchi** [comment]
Can you check if you can run something based on SK2, like my **[ASF](https://github.com/JustArchi/ArchiSteamFarm)**? That would definitely tell you if it's your own mistake or something SK2-based.

**Comment by JamesTheCoder** [comment]
Here's [some code that doesn't connect](https://gist.github.com/JamesTheCoder/adee3a1b76278bd2b6fb67844d9f7d18). I'll try out ASF now, and edit with results.

**Comment by JustArchi** [comment]
```
            if (callback.Result != EResult.OK)
            {

                return;
            }
```

Do:

```
Console.WriteLine("OnConnected(): " + callback.Result);
```

Or something similar.

**Comment by JamesTheCoder** [comment]
Still only get disconnect callbacks, nothing from the connect one.

**Comment by JustArchi** [comment]
If ASF works then it can't be your machine-specific issue, as it's based on SK2 as well.

**Comment by JamesTheCoder** [comment]
I'll close and look at my code then. Thanks.

**Comment by JamesTheCoder** [comment]
I can find no problems with the code. I'm going to leave this closed, as it clearly doesn't pertain to SteamKit2, but if anyone can see a solution, please do say. Thanks,

**Comment by JustArchi** [comment]
The only thing which comes to my mind is unhandled exception happening in SK2 code, like WMI query being broken.

Implement **[those](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Program.cs#L283)** **[two](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Program.cs#L284)** lines and check if no exception is being thrown during your program running.

**Comment by JamesTheCoder** [comment]
I've updated the gist to show the code changes for your suggestion. Nothing seems to have happened, it just hits the disconnect callbacks.

**Comment by VoiDeD** [comment]
@JamesTheCoder, what's the output in the [DebugLog](https://github.com/SteamRE/SteamKit/blob/master/Samples/3.DebugLog/Program.cs)?

**Comment by JamesTheCoder** [comment]
For whatever reason, it started working when I tried it again this morning. Thanks for your help.
