### ISSUE TITLE
Crash with Unhandled Exception

### ISSUE THREAD

**Issue by KenBeanNet** [SteamRE/SteamKit#311]
An exception of type 'ProtoBuf.ProtoException' occurred in protobuf-net.dll but was not handled in user code  Additional information: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354

You can replicate by sending 

var requestProfile = new ClientGCMsgProtobuf<CMsgClientToGCGetProfileCard>((uint)EDOTAGCMsg.k_EMsgClientToGCGetProfileCard);
            requestProfile.Body.account_id = accountId;

And during the response, the error occurs.  I checked GameTracker and I did not notice any proto updates that would cause this.

Thanks.

**Comment by KenBeanNet** [comment]
Resolved by updating Proto.  I think with TI around the corner, there is a lot of new changes.  SteamKit Dota side is a bit buggy.  Would suggest updating ASAP.

**Comment by VoiDeD** [comment]
We don't make a huge effort to keep our GC protobufs up to date, you can always generate and make use of your own in a separate assembly if needed.

**Comment by KenBeanNet** [comment]
This can be closed.  Updating Protos fixed issue.

**Comment by JustArchi** [comment]
You can close it yourself.
