### ISSUE TITLE
Bot is offline

### ISSUE THREAD

**Issue by luk27official** [SteamRE/SteamKit#315]
I have created a simple bot, i can log in but the bot is still offline. My code is
`steamFriends = steamClient.GetHandler<SteamFriends>();`
`manager.Subscribe<SteamUser.AccountInfoCallback>(OnAccountInfo);`
`static void OnAccountInfo(SteamUser.AccountInfoCallback callback)
        {
            steamFriends.SetPersonaState(EPersonaState.Online);
        }
`

**Comment by Arefu** [comment]
Have you made sure that the call back has fired?
Add a MessageBox or WriteLine before this, if that never shows up it means it hasn't got to this point.

Try adding SteamDirectory.Initialize().Wait(); before the RunWaitCallBacks()

**Comment by VoiDeD** [comment]
Closing this as this is a stale issue. Feel free to reopen if you're still having issues with setting persona state to online.
