### ISSUE TITLE
Using SteamKit to check if server needs updates

### ISSUE THREAD

**Issue by FreezinG117** [SteamRE/SteamKit#316]
Hi!

How can i get the latest version to my CS:GO servers?

**Comment by VoiDeD** [comment]
The [ISteamApps/UpToDateCheck](https://wiki.teamfortress.com/wiki/WebAPI/UpToDateCheck) WebAPI is generally the way to accomplish this.

**Comment by VoiDeD** [comment]
Closing this as I believe it's been addressed.
