### ISSUE TITLE
Add EResult value 106

### ISSUE THREAD

**Issue by bartico6** [SteamRE/SteamKit#322]
Value 106 is "GLSTExpired/GLSTInvalid".
If you use an expired gameserver token gotten from [Steam's website](http://steamcommunity.com/dev/managegameservers) and it's expired (not logged in to for __SOME__ time) the server will spam "__enum_names.cpp (136) : Assertion Failed: Missing String for EResult (106)__" - happens in both CS:GO and TF2 - said error is either a) token invalid or b) token expired.

I don't know the exact codename, however it needs to be added. It seems Valve themselves forgot to add it to their server software...

*How to reproduce*:
1. Start a TF2 server
2. Add an outdated GSLT token to autoexec.cfg / cmdline parameters
3. Watch the server console spam "__enum_names.cpp (136) : Assertion Failed: Missing String for EResult (106)__"
<!!> CONSOLE SPAM COULD BE LINUX-ONLY, I AM NOT SURE.

**Comment by DoctorMcKay** [comment]
Adding it to SteamKit won't fix your game servers.

**Comment by bartico6** [comment]
I want it added for public knowledge, not my servers.
So other people, (like me) who have [this](https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd) bookmarked to check eresult on the fly can see what's wrong as it's not entirely clear.
I am not stupid, @DoctorMcKay, I know SteamKit won't fix a TF2 server lmao

**Comment by Netshroud** [comment]
elordid has it automatically reverse-engineered from steamclient as `k_EResultGameserverLoginTokenExpired`

The string for it appears to be `"Gameserver login token expired"`.

There's a high chance it'll be `GSLTExpired`, but I wouldn't bet money on that.

**Comment by DoctorMcKay** [comment]
This will be the one where they call it a "gameserver account" instead of a "GSLT" just to screw with us.

**Comment by DoctorMcKay** [comment]
I confirmed the name `GSLTExpired` with Valve, so I've opened #323.
