### ISSUE TITLE
How to create steam server

### ISSUE THREAD

**Issue by cristiansori2** [SteamRE/SteamKit#332]
Hello friends,please,really i need help.With the SteamKit,how can i make a steam server???i mean,a steam server offline,and them,if is possible,how can i integrate a dota coordinator.I need this,because i live in cuba,and here we dont have acces to internet ,but we have a lan network,more than 9k people and  the most played game is dota 2.I really appreciate help.Thanks in advance

**Comment by garciabruno** [comment]
You can't.
Research for Source Dedicated Server if thats what you're looking into.

**Comment by cristiansori2** [comment]
Thanks for your answer.The problem is that the dota reborn dont have source dedicated server.

**Comment by VoiDeD** [comment]
Steam server emulation isn't something we support. SteamKit is only an implementation of the client networking.
