### ISSUE TITLE
Add the ability to add custom callbacks to CallbackManager

### ISSUE THREAD

**Issue by michaelvdnet** [SteamRE/SteamKit#333]
Add the ability to add custom callbacks to the CallbackManager, so libraries built on top of Steamkit2 do not need to have an additional event/callback system.

**Comment by VoiDeD** [comment]
Unless I'm misunderstanding this issue, this is exactly how callbacks are designed. You can implement your own callback object deriving from `CallbackMsg`, and then post it via `SteamClient.PostCallback`. If your code is using `CallbackManager`, you can subscribe to that callback and handle it however you like.

**Comment by michaelvdnet** [comment]
I'm the one misunderstanding, misunderstanding the callback system that is.
Was looking for ways to somehow add CallbackMsg's to the system, overlooking `PostCallback`.

Closing issue
