### ISSUE TITLE
Logged in with SteamKit and playing on that account

### ISSUE THREAD

**Issue by Qwiq973** [SteamRE/SteamKit#336]
Hello, I got a problem with when I use my program with SteamKit and with that program it will start a game and I have read through the open/closed issues here on SteamKit and on google and I found that you need to put a loginID to 0 if I'm not mistaken. But with that I have a problem were when I will start a game on that account it says that I'm logged in on another computer playing a game and it will disconnect my session with the bot.

**Comment by michaelvdnet** [comment]
I think the steam network doesn't allow 2 clients on 1 account.
What you want is not possible i'm afraid.

**Comment by Netshroud** [comment]
You need to set loginID to a non-zero value if you have another client connected from the same account, the same public IP address and the same private IP address.

If the IP addresses differ or the account differs, no action is needed.

**Comment by Qwiq973** [comment]
@Netshroud What should I put the loginID to? 
And how do I so the bot gets the same IPs?

**Comment by JustArchi** [comment]
> You need to set loginID to a non-zero value

Zero value is fine too, I use it since I stumbled upon some broken Linux steam clients that apparently under some circumstances use my previously preferred ```MsgClientLogon.ObfuscationMask``` value.

**Comment by Qwiq973** [comment]
If I use the `MsgClientLogin.ObfuscationMask` will it work so I can play games and so on with that account I'm logged in with the bot?

**Comment by JustArchi** [comment]
Only one session from the same account can play the game. You can have any amount of logged in session though. Check out how my ASF works in this regard.

**Comment by Qwiq973** [comment]
Okay, Thanks! I will
