### ISSUE TITLE
EResult.TryAnotherCM

### ISSUE THREAD

**Issue by Logxn** [SteamRE/SteamKit#337]
Hello,
so my bot reconnects to steam, and trys to log in but I am keep getting "TryAnotherCM" Error.
Now first of all I dont know what they mean by "CM" and second, I didn't change a singe line of code, it worked before but stopped to work now.

How can I resolve this?

**Comment by Logxn** [comment]
Current source here: https://ghostbin.com/paste/9qs7n

**Comment by rossengeorgiev** [comment]
CM is the server you connect to. Sometimes it will advise you to connect to another, so you simply retry to a different CM.

**Comment by Logxn** [comment]
Now this might sound stupid.
But how can I change the CM I want to connect?

**Comment by Netshroud** [comment]
SteamKit will temporarily [de-prioritise](https://github.com/SteamRE/SteamKit/blob/d9a1da3513e2747dbe2c3d752aebf7464e2d900b/SteamKit2/SteamKit2/Steam/CMClient.cs#L580-L583) a server that returns `TryAnotherCM`. If you just call `Connect()` again, you should land up on a different CM.
