### ISSUE TITLE
Receiving EMsg 24 instead of MsgClientToGCGetLeagueSeriesResponse.

### ISSUE THREAD

**Issue by TimotheeJeannin** [SteamRE/SteamKit#345]
I'm sending this message

    k_EMsgClientToGCGetLeagueSeries CMsgClientToGCGetLeagueSeries 

and expect to receive a 

    k_EMsgClientToGCGetLeagueSeriesResponse  MsgClientToGCGetLeagueSeriesResponse 

but instead I get a message with a value `24` as the `EMsg`.

From the [SteamLanguageInternal.cs](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Base/Generated/SteamLanguageInternal.cs#L674) file, it looks like it is matching `ProtocolVerMinorMinForServerAvailablityMsgs = 24`. 

So it's telling me that the version of the protocol I'm using is lower than the minimum version required for server availability messages. 

Is it possible to receive those messages ? What do I need to understand so I can make this work ? 

Thank you for your amazing work on SteamKit ! 

Tim

**Comment by rossengeorgiev** [comment]
24 is `k_ESOMsg_CacheSubscribed`

**Comment by TimotheeJeannin** [comment]
Ha ok ! Thank you. 
How am I supposed to use this ?

**Comment by rossengeorgiev** [comment]
I don't think that message is related to your request, so my guess is your code is doing something wrong. If you post code someone might be able to help. Dota 2 GC is kinda outside the scope of this project.

**Comment by VoiDeD** [comment]
Closing this one due to inactivity. Feel free to reopen if you still need assistance with Dota GC messages, but keep in mind that while most of the SteamKit maintainers aren't familiar with the specifics of the GC, a brave soul may be able to help out.
