### ISSUE TITLE
Masterlist Question

### ISSUE THREAD

**Issue by Headline22** [SteamRE/SteamKit#347]
I'm struggling to query the master list to get all CS:GO servers containing a certain tag in sv_tags. Here's what I have so far, but I feel like I am way off. Any help?

http://pastebin.com/ix1HBXGN

**Comment by VoiDeD** [comment]
"\\gametype\\csco\\"; ?

**Comment by psychonic** [comment]
If you're trying to find all servers running the CS:CO mod, checking the gamedir is going to be more accurate since tags can be more easily changed.

\gamedir\csco

**Comment by Headline22** [comment]
This is my first time using any sort of Steam API, so I apologize for inexperience.

Thanks for the tip, psychonic. I'm just confused about where I move next, and how to handle the results of the server query

**Comment by Headline22** [comment]
Alright, I made some good progress today. I figured out how to instantiate the _SteamMasterServer_ type and studied up some about async and await. However, I don't seem to be receiving a response back. Not sure exactly what I'm doing wrong, but I'm sure it has to do with how I am using await.

**Screenshot (Gif)**
https://i.gyazo.com/d971fbfc7d7166f7cd36cf18639dd95b.gif
**Current code**
http://pastebin.com/WsbcDuHj

Thanks

**Comment by Netshroud** [comment]
You don't appear to be connecting to Steam, logging in, or pumping the callback manager.

Check out the various SteamKit Samples for how to achieve this.

**Comment by Headline22** [comment]
Still seems like a no go....

I grab user information correctly and StartServerListGrab gets called once the user is logged in and authenticated.

http://pastebin.com/H8Qtegst

**Comment by VoiDeD** [comment]
I'm fairly certain you still need a filter, have you tried "\gamedir\csco" as suggested?

**Comment by Headline22** [comment]
Yeah, doing this yields the same results assuming this is correct..
`        querydetails.Filter = "\\gamedir\\csco";`\
If it's not I don't understand how I can do just "\gamedir\csco" without escaping the backslash

**Comment by JustArchi** [comment]
you can do ```@"\gamedir\csco"``` but using standard method with escaping backslashes should not affect anything.

**Comment by Headline22** [comment]
It didn't affect the outcome. I even set MaxServers = 5 just to see if it was grabbing so many, but that didn't change anything. Changing the filter to "\gamedir\csgo" also yielded no change.

**Comment by Headline22** [comment]
Oh wow... Changing the AppID to 730 did it. Except I only got one result back which confuses me because there definately should be more than one CS:CO server running

**Comment by psychonic** [comment]
I completely missed the 740 in your first bit of code. At runtime, servers use the game client's app id, so 730 is indeed correct.

It looks like CS:CO servers don't get listed on the master being they're sending an out of date version number from steam.inf. It needs to at or newer than CS:GO's current required version to be listed. You're best off contacting the mod author and having them just add an extra digit to the version number or something, ex. 11.35.x.x instead of CS:GO's current 1.35.xx. This way it can keep its own versioning, avoiding mismatched servers and clients, and without having to keep track of whatever CS:GO's current version is.

**Comment by Bluscream** [comment]
@Headline22 what do I need for the authcode msgbox?
![](https://i.imgur.com/xecR2Kz.png)

**Comment by VoiDeD** [comment]
Closing since I think this is resolved. Feel free to reopen if needed.
