### ISSUE TITLE
callback.OtherName on SteamTrading.TradeProposedCallback not working?

### ISSUE THREAD

**Issue by kadumedim** [SteamRE/SteamKit#348]
Code : 
```
 static void OnTradeProposed(SteamTrading.TradeProposedCallback callback)
        {
            Console.WriteLine("{0} ({1}) nos enviou uma proposta de troca!",callback.OtherName,callback.OtherClient);
        }
```

it doesn't seens to be writing callback.othername, just callback.otherclient 
` (STEAM_0:0:49878188) nos enviou uma proposta de troca!`

**Comment by VoiDeD** [comment]
Any chance you could run [NetHook](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) and verify Steam's behavior? It might be possible that field is no longer sent from the server.

**Comment by kadumedim** [comment]
@VoiDeD i never used NetHook and i'm still learning about SteamKit, i think it would be better if another person verify that field :/

**Comment by shravan2x** [comment]
I'll check up on this within a day or two.

**Comment by kadumedim** [comment]
@shravan2x Thanks!
