### ISSUE TITLE
callback.EmailDomain not showing on SteamUser.LoggedOnCallback

### ISSUE THREAD

**Issue by kadumedim** [SteamRE/SteamKit#351]
When i try to get the email domain string it just doesn't show what i expected
Code:
` Console.WriteLine("Test : " + callback.EmailDomain);`

Output: 
`Test :`

**Comment by Netshroud** [comment]
`callback.EmailDomain` is probably null or empty.

I believe Steam only sets this field when the logon response requires a Steam Guard email code.

**Comment by kadumedim** [comment]
Yeah, i was thinking about this and when it need the SteamGuard email code the parameter just looks fine
Gonna close this thread.
TY anyways @Netshroud
