### ISSUE TITLE
Allow overriding WebAPI endpoint

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#352]
If overwritten, it would also contain the protocol (making the secure option do nothing).

Use cases include forcing http for easier proxying, or using another domain (like community.steam-api.com).

**Comment by JustArchi** [comment]
IIRC WebAPI allows us already to specify whether we want to use http or https, by ```secure``` option. Would it make sense to make protocol override possible? I mean, I'm not sure if we ever want to send requests over something else anyway...

Overriding domain is valid suggestion, but I guess it'd matter only if you need to proxy requests, and despite of claiming to be rate-limited, I couldn't get to that limit during my tests, so I'd quite safely state that it's actually relaxed to the point that proxying should not be needed.

Although those are only my thoughts, I'm not against this change, as I'm pretty sure you have good reasoning for that - I'm just wondering what exactly.

**Comment by yaakov-h** [comment]
Probably the biggest (legitimate?) use-case would be the ability to change the domain to partner.steam-api.com.

**Comment by JustArchi** [comment]
Ah yes, I totally forgot about publisher API. Then even +1 more argument for overriding domain, but do we need to override protocol as well?
