### ISSUE TITLE
How to get SteamID64 from callback.sender

### ISSUE THREAD

**Issue by Eanna5** [SteamRE/SteamKit#353]
I am trying to get the 76561198086xxxxxx ulong from callback.sender but when I write it to my database it writes a STEAM_0:0:6326xxxx. This does not work when I need to take the value and use it in the SendChatMessage method and the steamID32 does not work there for some reason. I have looked around but can't figure out how to set a var to the SteamID64 version.
Thanks!

**Comment by VoiDeD** [comment]
If you have an instance of `SteamID`, you can either explicitly cast to ulong or call `ConvertToUInt64()`

**Comment by Eanna5** [comment]
Thank you! Works perfectly.
