### ISSUE TITLE
CS:GO Protobuf question

### ISSUE THREAD

**Issue by Menter32** [SteamRE/SteamKit#356]
Hello.
I wanted to send commendations in cs:go.
![image](https://cloud.githubusercontent.com/assets/24800141/21913325/0bce3b0c-d92c-11e6-867e-0be7f1c877e3.png)
As in dump analyzer, i think that i should send **ClientCommendPlayerQuery** first
`var msg = new ClientGCMsgProtobuf<XXX>((uint)ECsgoGCMsg.k_EMsgGCCStrike15_v2_ClientCommendPlayerQuery);`
I am not sure what should i insert in "XXX".
is this "message" missing? If so, how can i add it?
Thanks

**Comment by kainode** [comment]
@Menter32 did you solve this? also looking for it.
