### ISSUE TITLE
Can't connect to Steam

### ISSUE THREAD

**Issue by jurzer** [SteamRE/SteamKit#358]
Connect to Steam from a console application in C#, runs good, everything works. But when I put the code in a WinForm C# application, no callback is not working. Code is transferred one to one. Example code taken from Sample 5. What's the problem?

**Comment by jurzer** [comment]
I partially figured out what the problem is. Function Connect class TcpConnect. Call endPointTask.ContinueWith() returns nothing no matter how much I was not expecting. 
I replaced endPointTask.ContinueWith() on

`destination = new IPEndPoint(IPAddress.Parse("155.133.242.9"),27019);`
`TryConnect(timeout); `

and it worked. 

Can you explain how to get rid of unresponsiveness when you call endPointTask.ContinueWith() or maybe there is an alternative?

**Comment by VoiDeD** [comment]
Can you elaborate on how you're using TcpConnection directly? None of that is exposed via the public API.

My best guess is that you're stalling your winform's message loop (most likely by blocking with our callback API), and thus deadlocking your application.

**Comment by jurzer** [comment]
No, I connected the project SteamKit2 to your project that I could find the error during debug. Going into the debugger on the code found what is described above. Code using Sample 5 did not change it.

**Comment by VoiDeD** [comment]
Sample 5 is the SteamGuard sample, not sure how that's related.

Can you show how you're managing the SteamKit callback loop as I asked before?

**Comment by jurzer** [comment]
My initial assumption that the callback are not working correctly. 
Describe the problem again given that I know. I take the example 5 Sample, create a console application in C#, copy the code of the example. Run example works. 
Then create a WinForms C# project, copy there example code Sample 5. Add 
`[DllImport("Kernel32.dll")]` 
`static extern bool AllocConsole();` 
 to see the console, nothing more doublea to the code example. Start example does not work. 
You begin to understand what the problem is, is added to the solution to the SteamKit2 project, put a breakpoint on the Connect function class TcpConnect project SteamKit2 and see what method endPointTask.ContinueWith() returns nothing, neither error nor result. Remove the call to this method assigns a destination ip address and cause TryConnect(timeout); like endPointTask.ContinueWith() worked well. Run example works, it becomes obvious that the problem is in the call to endPointTask.ContinueWith();
Lead code don't see the point, as it is identical to the code Sample 5. In addition to displaying console I there add nothing.

**Comment by jurzer** [comment]
The solution to the problem in https://github.com/SteamRE/SteamKit/issues/360.
