### ISSUE TITLE
Perform browser actions

### ISSUE THREAD

**Issue by LiteOnE** [SteamRE/SteamKit#373]
Is that possible to perform browser actions, like a avatar changing, posting comments (in two words -submitting a from with sessionID and other parametres)

**Comment by LiteOnE** [comment]
Beep

**Comment by JustArchi** [comment]
This is out of the scope of SK2, as everything you linked is done on Steam Web and not in the Steam Network.

**Comment by Netshroud** [comment]
What Archi said.
