### ISSUE TITLE
WebAPI calls broken since 2.0.0

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#378]
Try to run **[Sample 6](https://github.com/SteamRE/SteamKit/tree/master/Samples/6.WebAPI)** with SK2 2.0.0-alpha:

```
System.NullReferenceException exception occurred
   HResult = 0x80004003
   Message = An object reference was not set to an object instance.
   Source = SteamKit2
   Stack trace:
    In SteamKit2.WebAPI.Interface.TryInvokeMember (InvokeMemberBinder binder, Object [] args, Object & result)
    In System.Dynamic.UpdateDelegates.UpdateAndExecute2 [T0, T1, TRET] (CallSite site, T0 arg0, T1 arg1)
    In Sample6_WebAPI.Program.Main (String [] args) in Program.cs: line 33
```

Line 33 in my project is **[line 37](https://github.com/SteamRE/SteamKit/blob/8a76ec693ed11102d1d7379b34fa75b47a975192/Samples/6.WebAPI/Program.cs#L37)** in SK2.

BTW, I target .NET 4.6.2 (not .NET core, maybe it works when targetting .NET core, I didn't check that).

As you can guess, similar thing happens to all old projects that were based on SK2 1.X and worked just fine, after update to 2.0.0.

Unless this is intended major breaking change (that should be corrected in samples and documented in changelog), it looks like a regression to me. Thanks!

**Comment by Netshroud** [comment]
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamKit2.WebAPI.Interface.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) in SteamKit/SteamKit2/SteamKit2/Steam/WebAPI/WebAPI.cs:line 164
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at CallSite.Target(Closure , CallSite , Object , Int32 )
```

Looks like [this case](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/WebAPI/WebAPI.cs#L160) failed. I'll dig into it a bit later.
