### ISSUE TITLE
SK 2.0.0 questions/issues

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#379]
Basically I have three concerns for now:

1. Base dependencies for .NET 4.6+ projects - It can be problematic to include .NET core System.* libraries when running SK2 with Mono, since many of those libs are incompatible with Mono (System.Net is just one example I found in a hard way when half of my app stopped working). Could it be possible to release two versions of SK2, one for .NET core with those dependencies in, and second one for .NET 4.6+, like until now, just with protobuf dependency? This is very important for me, since basically right now using SK2 on Mono with .NET 4.6+ is close-to-impossible, unless you're running hello world app.

This is pretty much what `protobuf-net` library is doing already.

2. SK2 is now copying 5 txt files (3rdparty, changes, gpl, lgpl and license) to root project dir. I don't have anything against that, but if that is intended then names should be more unique - you probably can imagine what would happen if every single library included its own `license.txt` in project dir.

~~3. Async interface returned by `WebAPI.GetAsyncInterface()` doesn't have `Timeout` property like its non-async version. Since it uses `HttpClient` under the hood, and that one can have custom `Timeout` property, I think it should be added.~~ #381

Those are 3 questions/issues for now, last 2 are rather misc but first one is important for me, thanks!

**Comment by Netshroud** [comment]
1. My understanding is that the package should be providing reference libraries, which the runtime substitutes with it's own libraries - for .NET Core I think it might use the package, but on .NET Framework it it should be using the normal classes. I'll have to check what's going on with the SDK.

2. Not sure what we should be doing here.

3. Can you open a new issue for this? The pre-existing timeout code was a bit complex and explicitly didn't use the Framework's `Timeout` property, but I don't recall why.

**Comment by JustArchi** [comment]
1. I'm targetting .NET 4.6.1 right now, and sadly SK2 "requires" all packages in both .NET and .NET core versions:

![1](https://cloud.githubusercontent.com/assets/1069029/24481543/3756ece2-14eb-11e7-9741-bd26f87de85c.png)

At the same time I'm 100% sure that it's possible to omit .NET core packages on .NET, this is what `protobuf-net` is doing:

![2](https://cloud.githubusercontent.com/assets/1069029/24481552/48868482-14eb-11e7-89d6-2e79a14d97be.png)

(No extra dependencies for .NET 4.5)

3. Done in #381 👍

**Comment by JustArchi** [comment]
Regarding second question - maybe it'd make sense to add a prefix such as `sk2-` in front of txt files, so it won't cause a mess if some other library uses one of the currently being used names. I'm not sure how "legal" it is, but if you're sure that you want to copy those txt files to project dir using SK2 library, then you should ensure it won't conflict with some other library doing the same. This is only a suggestion though.

**Comment by Netshroud** [comment]
Hmm, it looks like I might need to modify the csproj for the .NET references to something like `<ItemGroup Condition="'$(TargetFramework)'=='netstandard1.3'">`

@VoiDeD what do you think of the text files? I think it makes sense to include them in the package (somehow), but not necessarily copy to the consumer's bin directory. Alternatively we could just set the properties for the URLs, and not ship the full text files.

**Comment by VoiDeD** [comment]
@Netshroud Not sure, the licenses require us to include at least the `3rdparty.txt` file. The rest of the licensing files can likely be replaced with the license URL, and changes.txt just needs to be the readme.

**Comment by Netshroud** [comment]
@JustArchi Can you try the 2.0.0-Alpha3 build? I believe this should resolve items 1 and 2.

**Comment by JustArchi** [comment]
I re-checked the situation with alpha3 build of 2.0.0 and I can confirm that both first and second problems got entirely solved, which automatically closes this issue.

Thank you **a lot** @Netshroud, especially for the nuget dependency fix, that one just made maintaining my projects a lot easier and didn't result in a broken structure like previously ❤️.
