### ISSUE TITLE
Get users in a chat from ChatMsgCallback?

### ISSUE THREAD

**Issue by KraXarN** [SteamRE/SteamKit#384]
Is there a way to get all current users in a chatroom from the ChatMsgCallback or is it only possible from ChatEnterCallback?

**Comment by JustArchi** [comment]
Steam is sending incremental updates regarding chat updates, so no - you can't get it just like that. However, you can easily make use of `SteamFriends.ChatMemberInfoCallback` and `SteamFriends.ChatEnterCallback` and keep data for future. This is what I'm doing in ArchiBoT - I get initial list on enter, then I'm listening for all events, and I update my list accordingly.

**Comment by KraXarN** [comment]
That's what I thought I had to do, but then I know for sure. In the NodeJS port of this you can, so that's why I wasn't fully sure if I had to or not.
But thanks anyway!
