### ISSUE TITLE
NuGet Dependencies

### ISSUE THREAD

**Issue by slemsvamp** [SteamRE/SteamKit#386]
If I update to the newest version of SteamKit2 it depends on protobuf-net version 2.0.0.668 and will update to this version. When you run it, it will nag you that you're not running the required protobuf version of 2.1.0.

I, manually, changed to the correct reference in my own project but you might want to update the nuget dependencies to require the correct version of protobuf, unless I'm doing something wrong and misunderstood the whole thing.

**Comment by shravan2x** [comment]
I believe the protobuf reference has been updated in the latest beta. You can see this [in the csproj](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/SteamKit2.csproj). Switch to this version or just wait for the stable release.

**Comment by JustArchi** [comment]
You can't update protobuf-net to 2.1 in SK 1.8.3 or below - it won't work. However, latest SK2 in version 2.0+ already depends on protobuf-net 2.1+, so you won't only be able to update, but forced to.

**Comment by Netshroud** [comment]
What @JustArchi said is correct. SteamKit2 1.x is locked to protobuf-net 2.0.668.

If you're getting a runtime error requiring protobuf-net 2.1, it's not from us. Similarly, if you managed to fix it by modifying the reference in your own project, SteamKit2 is likely not the source of the error.

However, if you really want to use protobuf-net 2.1.0, you should be able to do this with [Assembly Binding Redirection](https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx).
