### ISSUE TITLE
[Question] Check if a user has VAC ban / Game ban on record

### ISSUE THREAD

**Issue by Marc3842h** [SteamRE/SteamKit#389]
I'm trying to find out if a user has a VAC ban / Game ban on record. This is what I already tried:
```c#
public static bool HasBansOnRecord(uint steamId)
{
    using(dynamic steamUser = WebAPI.GetInterface("ISteamUser", "API key"))
    {
         KeyValue pair = steamUser.GetPlayerBans(steamids: steamId.ToString());

         foreach(var bans in pair["players"].Children)
         {
             if(bans["SteamId"].ToString() == steamId.ToString())
             {
                 var hasVacBan = bans["VACBanned"].AsBoolean(); // VAC Bans
                 var gameBansCount = bans["NumberOfGameBans"].AsInteger(); // OW Bans

                 return hasVacBan || gameBansCount > 0;
             }
         }
    }

    return false;
}
```

but I couldn't get a response when trying it out with [STEAM_0:0:208017504](https://steamcommunity.com/id/TopKekTux/). Anyone got an idea? I appreciate it.

Also am I allowed to share my API code with a program (I made open-source on GItHub) & provide it with a already pre-compiled binary?

**Comment by VoiDeD** [comment]
You probably need to use the 64bit representation of the SteamID. Try `steamids: steamId.ConvertToUInt64()`.

**Comment by Marc3842h** [comment]
Worked, thank you.
One quick question, am I allowed to share my API key in a pre-compiled binary?

**Comment by VoiDeD** [comment]
API keys are meant to be private. If your application needs to make webapi requests you may want to consider a design where you have your own web application that does the requests with the key.

**Comment by Marc3842h** [comment]
Alright, thank you.
