### ISSUE TITLE
Missing Reference on newest Build

### ISSUE THREAD

**Issue by STRATZ-Ken** [SteamRE/SteamKit#393]
Missing Dependency : System.Runtime.Serialization.Formatters (Wont compile without it).

**Comment by Netshroud** [comment]
More info, please.

Travis, AppVeyor and my local build environments all disagree.

**Comment by STRATZ-Ken** [comment]
So I downloaded VS2017.  Downloaded a Zip of your contents.  Opened the main sln file and went to rebuild.  The rebuild failed with about 400 errors all about serialization.  I had to manually add the reference above and then the build succeeded.  Windows 10 Pro machine.

**Comment by Netshroud** [comment]
Can you please provide the full build output?

**Comment by STRATZ-Ken** [comment]
Was not able to replicate a 2nd time.  I downloaded a clean folder, extracted and it built.  Maybe it was because I over-wrote a version from about Aug of last year.  Closing ticket.

**Comment by Netshroud** [comment]
You probably had some older protobuf-generated C# files lying around on disk that are no longer part of SteamKit2. The new project system includes all `.cs` files by default.
