### ISSUE TITLE
SharpDevelop/NuGet Error

### ISSUE THREAD

**Issue by BoberMod** [SteamRE/SteamKit#397]
When I try add SteamKit to project I get error
![image](https://cloud.githubusercontent.com/assets/8740496/26766350/c416924a-4998-11e7-8196-a1243b1ce900.png)
How to fix it?

**Comment by JustArchi** [comment]
Target .NET 4.5 or above. I suggest .NET 4.6+ if you want to have project compatible with SK2 2.0.

**Comment by Netshroud** [comment]
>= 4.6.1 if we end up going `netstandard2.0`-only.
