### ISSUE TITLE
The analog of Steamkit-csgo

### ISSUE THREAD

**Issue by BoberMod** [SteamRE/SteamKit#398]
I'm looking for .NET library, which can interact with cs: go
This [library](https://github.com/michaelvdnet/SteamKit-CSGO) hasn't been updated for a long time and has many bugs.

**Comment by Netshroud** [comment]
Ask around or build your own.

Whilst sending messages to the GC and receiving messages from the GC are in the scope of SteamKit, that is the extent of our GC interactions. Any GC-specific stuff (Dota, CS:GO, etc.) is out of scope for SteamKit2, and loosely in scope for NetHook Analyzer.
