### ISSUE TITLE
Game key

### ISSUE THREAD

**Issue by KamushekORIGINAL** [SteamRE/SteamKit#403]
How can I activate a game with a license activation key by your lib?

**Comment by Netshroud** [comment]
This is intentionally left as an exercise for the reader.

**Comment by KamushekORIGINAL** [comment]
Okay, but can u help me. :c Or give some info about that?

**Comment by psychonic** [comment]
No.

**Comment by KamushekORIGINAL** [comment]
:c But.... *cry*

**Comment by JustArchi** [comment]
With ASF being around it's a true shame that you even ask for that here.
