### ISSUE TITLE
How to get CSODOTALobby object?

### ISSUE THREAD

**Issue by AndBoh** [SteamRE/SteamKit#409]
Maybe it is stupid question, but i can no to find any answer. When I have recieved k_ESOMsg_CacheSubscribed message from GC what I should to do to get CSODOTALobby object? As I understud it contained in msg.body.objects, but i don't know how to transform it to CSODOTALobby.

**Comment by rossengeorgiev** [comment]
`CSODOTALobby` is a `SharedObject` and you have to handle the SO related messages, and then deserialize the objects from there.

I have a reference implementation of a SO manager that handle all that in python

https://github.com/ValvePython/dota2/blob/master/dota2/features/sharedobjects.py

**Comment by yaakov-h** [comment]
Closing as this has been answered.
