### ISSUE TITLE
Getting dota 2 game coordinator events

### ISSUE THREAD

**Issue by muc1** [SteamRE/SteamKit#411]
is itprossible to read dota 2 game coordinator events like party invites wihtout injecting into the steam proccess?

**Comment by yaakov-h** [comment]
I doubt it.

**Comment by rossengeorgiev** [comment]
@muc1 maybe. Check out the this file `Steam\steamapps\common\dota 2 beta\game\dota\server_log.txt`

It should contains info about parties and lobbies. The client writes that file, so all you have do is read it.

**Comment by yaakov-h** [comment]
Closing as answered, even though it's probably not the answer you wanted to hear.
