### ISSUE TITLE
What body should i use for "ClientRequestValidationMail" client message?

### ISSUE THREAD

**Issue by LiteOnE** [SteamRE/SteamKit#413]
I'd like to be able to request a validation mail for new accounts, but i can't find the body it needs. Or do I do something wrong?

var CMsg = new ClientMsgProtobuf<*?*>(EMsg.ClientRequestValidationMail);
steamClient.Send(CMsg);

**Comment by ObsidianMinor** [comment]
The request is a MsgBase<ExtendedClientMsgHdr> (you must this implement yourself because MsgBase<T> is abstract) and the response is a ClientMsg<MsgClientGenericResponse>

**Comment by yaakov-h** [comment]
> `MsgBase<ExtendedClientMsgHdr>`

This looks wrong. Isn't that just `ClientMsg<SomeCustomMessageStructYouHaveToImplementYourself>`?

**Comment by LiteOnE** [comment]
Yep, it seems to should be implemented by myself. Any tips how I could do this?

**Comment by ObsidianMinor** [comment]
I think it's right. CClientJobRequestValidateMail::BYieldingRunAPIJob() uses CMsgBase<ExtendedClientMsgHdr> [as seen in IDA](https://i.imgur.com/tlTSBOY.png)

**Comment by VoiDeD** [comment]
Hexrays isn't super accurate, but gives you enough information:

```
  pClientMsgProbably = (int)&off_FC5904;
  v1->eMsg = 5448;                              // k_eMsgClientRequestValidationMail
  v1->dword1C = 0;
  v1->dword18 = 0;
  v1->dword20 = 0;
  LOBYTE(v1->dword4) = 36;
  BYTE3(v1->dword14) = -17;
  *(_WORD *)((char *)&v1->dword4 + 1) = 2;
  *(_DWORD *)((char *)&v1->dword10 + 3) = -1;
  *(_DWORD *)((char *)&v1->dwordC + 3) = -1;
  *(_DWORD *)((char *)&v1->dword8 + 3) = -1;
  *(_DWORD *)((char *)&v1->dword4 + 3) = -1;
  if ( (unsigned __int8)CBaseAPIJob::BYldLoginAndSendMessageAndGetReply(
                          this,
                          (int)&pClientMsgProbably,
                          1,
                          20,
                          (int)&pMsgReply) )
  {
    if ( (*(int (__cdecl **)(_DWORD))(*(_DWORD *)pMsgReply + 36))(pMsgReply) == 5449 )// k_eMsgClientRequestValidationMailResponse
    {
      CClientMsg<MsgClientGenericResponse_t>::CClientMsg(&v7, pMsgReply);
      *(_DWORD *)v23 = *(_DWORD *)(v8 + v9);
      CMsgBase_t<ExtendedClientMsgHdr_t>::~CMsgBase_t(&v7);
    }
```

At `off_FC5904` is:

```
__data:00FC58FC ; `vtable for'CClientMsg<MsgClientRequestValidationMail_t>
__data:00FC58FC __ZTV10CClientMsgI32MsgClientRequestValidationMail_tE db    0
__data:00FC58FD                 db    0
__data:00FC58FE                 db    0
__data:00FC58FF                 db    0
__data:00FC5900                 dd offset __ZTI10CClientMsgI32MsgClientRequestValidationMail_tE ; `typeinfo for'CClientMsg<MsgClientRequestValidationMail_t>
__data:00FC5904 off_FC5904      dd offset __ZN10CClientMsgI32MsgClientRequestValidationMail_tED1Ev
__data:00FC5904                                         ; DATA XREF: CClientJobRequestValidateMail::BYieldingRunAPIJob(void)+114o
__data:00FC5904                                         ; CClientMsg<MsgClientRequestValidationMail_t>::~CClientMsg()
__data:00FC5908                 dd offset __ZN10CClientMsgI32MsgClientRequestValidationMail_tED0Ev ; CClientMsg<MsgClientRequestValidationMail_t>::~CClientMsg()
__data:00FC590C                 align 10h
```

So the request struct you're looking for is `MsgClientRequestValidationMail_t` and the response is `MsgClientGenericResponse_t`, both sent with `ClientMsg`. However, getting the body of these is an exercise left to the reader.

**Comment by ObsidianMinor** [comment]
I just tested it, MsgClientRequestValidationMail is just an implementation of MsgBase<ExtendedClientHeader> without a body. So you could do it with an empty class called "Empty" that doesn't write any data. The return type is correct.

**Comment by ObsidianMinor** [comment]
[Proof](https://cdn.discordapp.com/attachments/144457700930093056/335907119033221120/ohno.png)

**Comment by LiteOnE** [comment]
@ObsidianMinor Could you send a sample code please? And thank you very much you all for the response :)

**Comment by ObsidianMinor** [comment]
Uh I guess. It's not that hard.

`
public class Empty : ISteamSerializableMessage
{
   public EMsg GetEMsg => EMsg.Invalid;
   public Serialize(Stream stream) { }
   public Deserialize(Steam stream) { }
}
`

`
public class ValidationMailCallback
{
   public EResult Result { get; }

   internal ValidationMailCallback(MsgClientGenericResponse response)
   {
      Result = response.Result;
   }
}
`

In the request

`
public AsyncJob<ValidationMailCallback> RequestValidationMail()
{
   var request = new ClientMsg<Empty>(EMsg.ClientRequestMail);
   request.SourceJobID = Client.GetNextJobID();

   Client.Send(request);

   return new AsyncJob<ValidationMailCallback>(Client, request.SourceJobID);
}
`

I don't know if this is completely correct because I tested in my own kind of SteamKit called Steam.Net which is very different.

**Comment by LiteOnE** [comment]
Thank you very much again! Here's my working code: 
```c#
public class RequestValidateMail : ISteamSerializableMessage
{
    public EMsg GetEMsg() => EMsg.ClientRequestValidationMail;
    public void Serialize(Stream stream) { }
    public void Deserialize(Stream stream) { }
}
```

```c#
var CMsg = new ClientMsg<RequestValidateMail>();
CMsg.SourceJobID = steamClient.GetNextJobID();
steamClient.Send(CMsg);
```
Well, it was really not so hard as I thought. I'm closing the issue
