### ISSUE TITLE
Make SteamConfiguration immutable, somehow

### ISSUE THREAD

**Issue by yaakov-h** [SteamRE/SteamKit#415]
Left-over from #405.

A few options:

1. The Builder Pattern - i.e. `new SteamConfigurationBuilder().WithBlah(...).Build()`
2. The `System.Windows.Freezable` pattern, i.e. `configuration.Freeze()`
3. Truly immutable, every set method returns a copy of the object i.e. `SteamConfiguration SetBlah(Blah value)`

Anything else?

**Comment by ObsidianMinor** [comment]
Don't make it immutable but copy all properties from the config to the client during construction. That way if someone modifies the config it won't change the client.

**Comment by VoiDeD** [comment]
I'm partial to the builder pattern, it's most likely the easiest way to not shoot yourself in the foot.

**Comment by yaakov-h** [comment]
@ObsidianMinor tradeoff there is memory usage. I don't want to have to clone everything.

@VoiDeD I'll give that a shot then.

**Comment by JustArchi** [comment]
Builder pattern is probably the best choice here, freezable pattern is confusing, while truly immutable has memory tradeoff, especially when modifying several things at once - returning new object multiple times isn't very efficient, while extra functions would make a mess in the code for the sake of completion.

Although I'm not sure if we want to make entire thing immutable - I like how I can update `CellID` of `SteamConfiguration` already being used in steam clients, once I know which one is appropriate. This makes it possible for steam clients to use that cellID in future connections.

**Comment by yaakov-h** [comment]
`CellID` on login still belongs to `SteamUser.LogOnDetails`/`SteamUser.AnonymousLogOnDetails`, and I guess maybe we should also add it to `SteamGameServer` logon. I'm not 100% sure what it's used for though, because by the time you connect to a server it's logically too late to pick a cell.

Either way, at this point in time `SteamConfiguration.CellID` is only used for retrieving the server list from the directory, which is done before you connect to Steam. Once you've connected to Steam, you'd need to take the current CellID and refresh the server list, though once you've connected Steam will give you a new list of servers anyway.

So logically, there are two flows here. The first is:
1. You don't specify a Cell ID.
2. You refresh the server list. Steam gives you the servers it feels like. This might be by GeoIP on the server side, I'm not 100% sure.
3. You connect to a server.
4. The server tells you your Cell ID.
5. The server gives you a new list of servers, ordered for your cell.
6. We replace the contents of the current server list with this cell-specific list.

The second is:
1. You specify a Cell ID.
2. You refresh the server list. Steam gives you the servers for your Cell.
3. You connect to a server.
4. The server tells you your Cell II.
5. The server gives you a new list of servers, ordered for your cell.
6. We replace the contents of the current server list with this cell-specific list.

In either case, after logging in, we now have a cell-specific list of servers in the Steam Configuration. You don't need to update `SteamConfiguration.CellID`, because the server list is already populated.

**Comment by JustArchi** [comment]
I thought `SteamConfiguration.CellID` would be used in `SteamUser.LogOn()` if we don't specify `cellID` in the request itself. In this case you're correct, it doesn't have to be modified after being initialized in a single `SteamClient`, so everything is fine 👍
