### ISSUE TITLE
ServerRecord does not implement a default constructor

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#416]
**[ServerRecord](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/Discovery/ServerRecord.cs)** currently does not have a default contructor, which is problematic if we decide to serialize/deserialize server list e.g. in JSON.

> 2017-07-21 01:52:27|dotnet-3980|ERROR|ASF|Load() Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type SteamKit2.Discovery.ServerRecord. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'ServerList.Servers[0].EndPoint', line 1, position 84.

Could we get a default (private) constructor that takes no arguments for the sake of deserialization? I'd appreciate it a lot, thank you!

**Comment by yaakov-h** [comment]
The issue with a default constructor is that it only makes sense if the object has a sensible default state. `ServerRecord` doesn't have a sensible default state. If we made an empty default constructor, then we could have `ServerRecord` object flying around with null `EndPoint`s etc.

As a general rule, I prefer to separate the object model from the serialised representation, unless it makes sense for the two to be the same. The supplied implementations of `IServerListProvider` back onto a separate protobuf object, which only required minor tweaks to update from `IPEndPoint` to `ServerRecord`. If we change it again, and you are (de)serializing `ServerRecord` object directly, then you're more or less up the creek without a paddle, as you may not be able to deserialise your older data.

I'd recommend creating your own serialisation model, similar to `BasicServerListProto`.

**Comment by JustArchi** [comment]
I went with your idea and created my own model. You're right that it's much better that way. Thanks 👍.

As a side note, do we have a proper logic for handling protocol-incompatible endpoints when connecting? Let's say our saved server-list includes `TCP`, `UDP, and `WebSocket` servers, and those servers are returned by `FetchServerListAsync()`. Is SteamClient smart enough to filter on its own "invalid" servers and connect to the one that matches `ProtocolTypes` in newly-introduced `SteamConfiguration`? If not, it might be a good idea to add it - I didn't find any logic for that in default server list providers, so I assume you have logic somewhere above.

Thanks a lot.

**Comment by yaakov-h** [comment]
`SteamClient` will only fetch servers from the list that match at least one of the `ProtocolTypes` specified in `SteamConfiguration`. The logic for that is not in `IServerListProvider`, but in `SteamClient` and `SmartCMServerList`.

In the current setup you can have one `IServerListProvider` shared by three `SteamClients`, where each client has a different exclusive protocol type. 😄

**Comment by JustArchi** [comment]
> In the current setup you can have one `IServerListProvider` shared by three `SteamClients`, where each client has a different exclusive protocol type.

Lovely, thank you! 👍
