### ISSUE TITLE
ClientPlayingSessionState regression

### ISSUE THREAD

**Issue by rossengeorgiev** [SteamRE/SteamKit#418]
https://github.com/SteamRE/SteamKit/blob/8407eb61e58964b2efbe49c08503f0cf0b2aee9b/Resources/SteamLanguage/emsg.steamd#L1891-L1892

Noticed that 9600 has been mapped as base, but that seems incorrect. `EMsg.ClientPlayingSessionState` corresponds to https://github.com/SteamRE/SteamKit/blob/8407eb61e58964b2efbe49c08503f0cf0b2aee9b/Resources/Protobufs/steamclient/steammessages_clientserver_2.proto#L1147-L1150

NHA2 also fails to deserialize the message

![image](https://user-images.githubusercontent.com/2720787/28498709-8ba23abc-6f9b-11e7-9e9d-cf9ecc6be8a2.png)

**Comment by yaakov-h** [comment]
If you know the matching message type we can add it to `NetHookAnalyzer2.MessageTypeOverrides`.

We should probably also update `NetHookAnalyzer2.MessageTypeFinder.FilterProtobufMessageBodyType` to find multiple enum members with the same value and prefer the ones that don't end in `Base`.

**Comment by rossengeorgiev** [comment]
If you look on the screenshot the right pane is recognizing it as `ClientConcurrentSessionBase`. While the correct should be `ClientPlayingSessionState`, which is also the name of the proto message, see links.

**Comment by yaakov-h** [comment]
Not sure we can do much about that, that would be up to how .NET handles integer-to-Enum casts when there are duplicate enum members.

@VoiDeD do we actually need to emit enum members for the -Base EMsgs, or can we just make them comments?

**Comment by JustArchi** [comment]
Personally I'd recommend a compromise between both - why not comment base enum member when there exists another specific enum member with the same ID? This sounds like the best idea since we can make use of specific message when we know how to treat it, while we still have base members in case we don't, for example when Steam network suddenly starts using one we're missing due to outdated protobufs.

Alternatively we could declare another enum just with base members, but first approach sounds much better to me.

**Comment by yaakov-h** [comment]
If you rely on the generated code for the base enums (for some reason), then it would be inconsistent - some are there, but some are missing.

IMO, it should be all or nothing.

**Comment by JustArchi** [comment]
In this case why not fix what is broken? https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#enum-members

> Multiple enum members may share the same associated value.

I don't know what particular issue @rossengeorgiev is referring to here - the pure existance of those values do not affect C# code directly as comparing enum value to enum members that match exactly the same value yields in proper `true` result. NHA2 would probably require a misc fix that would either prefer to treat message as non-base, or override `ToString()` and include all enum members that match the ID, maybe with multiple bodies where appropriate.

**Comment by rossengeorgiev** [comment]
Doesn't `Enum.GetName` return the first member name, when multiple members share a value?

**Comment by yaakov-h** [comment]
> If multiple enumeration members have the same underlying value, the GetName method guarantees that it will return the name of one of those enumeration members. However, it does not guarantee that it will always return the name of the same enumeration member. As a result, when multiple enumeration members have the same value, your application code should never depend on the method returning a particular member's name.

**Comment by VoiDeD** [comment]
>@VoiDeD do we actually need to emit enum members for the -Base EMsgs, or can we just make them comments?

We _probably_ don't need to emit them. Especially if `Enum.GetName` will function poorly because of it.

>while we still have base members in case we don't, for example when Steam network suddenly starts using one we're missing due to outdated protobufs, while we have a base one for it.

That still sounds like it would end up being just as confusing since Steam will never use a Base emsg directly, and I don't think we'd ever have the Base name without the names of  at least one actual EMsgs in that block.

**Comment by yaakov-h** [comment]
Another case to consider is when Valve rename an EMsg and we keep the old and new ones around.

Perhaps we should just changed the body message heuristic to include all EMsgs with the same value, and ignore the .ToString() issue outright, or replace it with a custom implementation to find the first non-Base non-Obsolete name.

**Comment by yaakov-h** [comment]
This appears to be the only case at the moment where we have a `Base` message sharing a value with a regular message, and we have known protobuf body types.

There are technically two others - `RemoteClientBase`/`RemoteClientAuth` and `ClientBroadcastBase`/`ClientBroadcastInit`, but as far as I am aware you will never see those in NetHook as they are sent over different channels.
