### ISSUE TITLE
Steam network limits

### ISSUE THREAD

**Issue by rossengeorgiev** [SteamRE/SteamKit#42]
Hello,
This is more of a question than an issue. Are you guys aware of any rate limits on the steam network? Is there a list available anywhere?

For example, friend/group invites, messages etc.

**Comment by VoiDeD** [comment]
Going to close this one for inactivity and the difficulty in determining the answer. Generally we're not aware of any rate limits on the network, and Valve doesn't make this information available.

That isn't to say there is no limits, however, as Valve does keep statistics on various actions (such as group invites), and has disabled various friends-related features on accounts in the past.
