### ISSUE TITLE
No callback on steamUserStats.GetLeaderboardEntries

### ISSUE THREAD

**Issue by mitchelvk** [SteamRE/SteamKit#421]
Hello everyone,

I'm trying to obtain the leaderboard entries for Age of Empires II: HD Edition. I used Nethook2 Dump Analyzer to find out what the game does. When you launch the game, it retrieves a few leaderboard entries as well, as you can see here:

https://pasteboard.co/GD5Asfu.png

After logging in on Steam, I call this method to retrieve the leaderboard ID for the RM leaderboard. This name is also being used by the game, and I do receive a callback on this:

`steamUserStats.CreateLeaderboard(221380, "LEADERBOARD_RM", ELeaderboardSortMethod.Ascending, ELeaderboardDisplayType.Numeric);`

Then I handle the callback as follows:

`static void OnFindOrCreateLeaderboard(SteamUserStats.FindOrCreateLeaderboardCallback callback)
        {
            steamUserStats.GetLeaderboardEntries(221380, callback.ID, -4, 4, ELeaderboardDataRequest.Global);
        }`

The strange thing is, when I change any of the GetLeaderboardEntries arguments in a way that it will result in 0 entries, I do get a response. This for example does give me a response

`static void OnFindOrCreateLeaderboard(SteamUserStats.FindOrCreateLeaderboardCallback callback)
        {
                steamUserStats.GetLeaderboardEntries(221380, callback.ID, 0, 0, ELeaderboardDataRequest.Global);
        }`

As soon as there are more than 0 entry results, I don't get a callback anymore. Do any of you know why this is and if/how I can solve that?

This is how I handle the callback:

`static void OnLeaderboardEntries(SteamUserStats.LeaderboardEntriesCallback callback)
        {
            Console.WriteLine("LB entries response");
        }`

**Comment by yaakov-h** [comment]
> Do any of you know why this is and if/how I can solve that?

Now we do. 😄 

If you enable `DebugLog` (see sample 3), there was an exception occurring when building the callback object. This was caught and logged, but no callback could be posted.
