### ISSUE TITLE
JavaGen up-to-date for port?

### ISSUE THREAD

**Issue by revidee** [SteamRE/SteamKit#423]
I'm currently developing a up-to-date port of SteamKit2 for Java, since the existing is quite outdated. (It doesn't even had Win10 in the EClientOs Enum).

I'm using VS17 to run the SteamLanguageParser and building the java files, but the question that still remains: Is the JavaGen up-to-date so every message in the steamd files gets processed?

I ran into some integer casting problems, but avoided them pretty quickly, is there anything else out-of-date?

**Comment by yaakov-h** [comment]
Every message should get processed, but what's done with them may or may not be what you want. I think we've added some features to the generator since the last time anyone used the Java generator.

**Comment by revidee** [comment]
In that case, I'm gonna try to translate the C# Generator to an equivalent JavaGen, if successful, I'm gonna let you know.

**Comment by yaakov-h** [comment]
Let us know how it goes.
