### ISSUE TITLE
[Suggestion] CallbackManager.RunWaitAllCallbacks() should have async variant

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#425]
This is something I stumbled upon lately. Since this method will block for given timespan in synchronous `Monitor.Wait()` call, I believe there should be a way to schedule that wait asynchronously, for example with `TaskCompletionSource<bool>`. It's not like a thread is frozen for some expensive number of miliseconds, as that timeout is usually pretty low (half a second in my case), but it could still result in free thread while we're waiting for a callback to arrive, especially since people might want to use longer timespans such as several seconds, and in this case this is becoming more serious problem. This is quite visible when people decide to run multiple steam clients with multiple callback managers, all of them taking at least one dedicated thread each, while it could potentially be handled with just a few instead.

Just random thoughts and suggestion, feel free to discuss.

**Comment by VoiDeD** [comment]
I think we _could_ look into replacing our callback queue management with something like a `BufferBlock<T>`. It exposes both a `ReceiveAsync` for the new TPL pattern, and a regular `Receive` with a timeout so we can keep supporting the existing code.

**Comment by yaakov-h** [comment]
I've never heard of `BufferBlock<T>`.

If something exposes a wait handle you can asynchronously wait for it with `ThreadPool. RegisterWaitForSingleObject`.

Could we maybe signal an automatically-resetting `EventWaitHandle`?

Another option - if the problem is the O(N) amount of threads and not the fact that we have said threads in the first place - is that we could perhaps have a `CallbackManager` be one-to-many with `SteamClient` instead of one-to-one. This would reduce the amount of dedicated callback threads to 1.

**Comment by JustArchi** [comment]
Making `CallbackManager` handle multiple `SteamClient`s sounds good at first, but I'm afraid that it can be too much for a single thread to handle in long-run - we might have extra delay when dozen, or even hundreds of `SteamClient`s will all have a massive queue of pending callbacks to deal with. It doesn't necessarily have to be a problem since callbacking handling is quite cheap operation, but it still involves delay that could otherwise be avoided, as each `SteamClient` can have its callbacks handled at the same time as all other ones.

I like how threadpool can perfectly balance itself in terms of active threads when doing asynchronous operations. If our `CallbackManager` did work in asynchronous way then threadpool could nicely balance number of active threads in comparison with the work that has to be done at given moment, resulting in a very low number of threads when things are pretty quiet/idle, but at the same time pushing number of threads even back to O(N) if situation will need those extra threads to handle busy callback queues of all `SteamClient`s at the same time.

In general I think we should try to limit number of frozen threads handling callbacks, so even multiple `SteamClient`s for one `CallbackManager` sounds good to me, but if we're changing it already then we can probably do better than that 👍.
