### ISSUE TITLE
Join/Leave a Steam group?

### ISSUE THREAD

**Issue by aj22r** [SteamRE/SteamKit#427]
Is there any way to join and leave a steam group with steamkit2 on c#? I have searched for this and seen that steamkit2 recognises groups as friends, but when i try to do `steamFriends.AddFriend(groupID)` it doesnt work? I really need to be able to join and leave groups with steamkit2, please reply as soon as possible. Thanks

**Comment by JustArchi** [comment]
It is possible to accept/reject group invite with SK2 alone (`AddFriend()` as you found out), but for joining/leaving on your own you'll probably need steam community web, unless there is some undocumented network request for that.

If you browse through my **[ArchiWebHandler](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiWebHandler.cs)** you'll easily see at least one of your wanted methods reverse-engineered and ready for use.

**Comment by aj22r** [comment]
I'm a beginner at this, could you give me an example piece of code of the steam community web thing or something that allows me to join a group that i could put into Visual C#?

**Comment by JustArchi** [comment]
I already gave you far more than you should get as a help. If you know how to connect pieces together and actually put effort in it instead of blindly copy-pasting then you'll know what to do with that, otherwise you need to wait for somebody else to do your homework 🙂

**Comment by aj22r** [comment]
I found this in your ArchiWebHandler thing:

`internal async Task<bool> JoinGroup(ulong groupID) {
			if (groupID == 0) {
				Bot.ArchiLogger.LogNullError(nameof(groupID));
				return false;
			}

			if (!await RefreshSessionIfNeeded().ConfigureAwait(false)) {
				return false;
			}

			string sessionID = WebBrowser.CookieContainer.GetCookieValue(SteamCommunityURL, "sessionid");
			if (string.IsNullOrEmpty(sessionID)) {
				Bot.ArchiLogger.LogNullError(nameof(sessionID));
				return false;
			}

			string request = SteamCommunityURL + "/gid/" + groupID;
			Dictionary<string, string> data = new Dictionary<string, string>(2) {
				{ "sessionID", sessionID },
				{ "action", "join" }
			};

			return await WebBrowser.UrlPostRetry(request, data).ConfigureAwait(false);
		}`
But i have no idea how to use that, could you please help me?

**Comment by VoiDeD** [comment]
>EDIT: Something is wrong with the code thing, but you can still make out what it is

You can use three backticks to format larger blocks of code, rather than one. I've fixed that for you now for clarity though.

**Comment by aj22r** [comment]
I tried opening ArchiWebHandler.cs in visual studio but it was full of errors, yes, i did install the newtonsoft.json thing but it still is full of errors

**Comment by yaakov-h** [comment]
I get the feeling you don't understand C#/.NET...

**Comment by aj22r** [comment]
you are absolutely right

**Comment by aj22r** [comment]
So anybody has any idea how to do it?

**Comment by yaakov-h** [comment]
I'm going to close this issue.

Archi has helpfully provided not only his entire open-source project as an example, but also pointed out the relevant portions. If that's not enough, then this appears to be a bit too advanced for where you currently stand.

We're not going to spoonfeed you. I suggest you get some more experience in .NET before trying this again. Start smaller, and learn some of the underlying concepts before tackling something this large and complex.
