### ISSUE TITLE
Create WebSocket version of NetHook

### ISSUE THREAD

**Issue by yaakov-h** [SteamRE/SteamKit#432]
Should be doable at just a protocol level with something like FiddlerCore, though licensing looks sketchy.

**Comment by VoiDeD** [comment]
Mirroring some notes from IRC, in case we want to expand NetHook to just hook more methods without fiddler/proxies/etc.

For sending: `CWebSocketConnection::BBuildAndAsyncSendFrame(EWebSocketOpCode,uchar const*,int)` might be a good starting point. This will be called after the `CWebSocketConnection` has fully assembled the data that will be in a frame, but before it's encoded into an actual web socket frame (and before it gets piped through the `COpenSSLConnection`). Data is passed right through the params, so we've got everything we need here.

Receiving is a bit more fun... `CWebSocketConnection` handles incoming data through `CWebSocketConnection::DecodePktAndDispatch(uchar *,uint)`. This method will handle decoding the frame and dumping it into a `m_sFrameCur` member, which is at the very least a struct with the first member being a `void *m_pubPayload`.

Once `CWebSocketConnection::DecodePktAndDispatch` is done decoding, it will call into `CWebSocketConnection::DispatchCurrentFrame(void)`, where it will create a `CNetPacket` from the data in `m_sFrameCur.m_pubPayload`.

Hooking `CWebSocketConnection::DispatchCurrentFrame` is probably the best option, but we'd need to maintain an offset to `m_sFrameCur`, which wouldn't be super fun going forward.

Another option might be hooking `CWebSocketConnection::RecvPkt(CNetPacket *)` , which will be called by `DispatchCurrentFrame`. Maintaining the structure of `CNetPacket` would likely be much easier.

**Comment by VoiDeD** [comment]
Implemented via #439.
