### ISSUE TITLE
How do you do XXX when the client sends a message?

### ISSUE THREAD

**Issue by Carnage555** [SteamRE/SteamKit#433]
Hey, I've been making a (sort of) Steam self bot, and I can't seem to find a callback for when the client sends a message. This is a issue for me as I'm looking for the bot to do commands when I type them out, e.g. if I send to someone "/help" it will list out all the commands of my bot. I'm aware of how to do receiving messages from friends but there doesn't seem to be one for sending them, and if so, how would I go about it?

Any help would be greatly appreciated, thanks! 👍

**Comment by JustArchi** [comment]
`SteamFriends.ChatMsgCallback` and `SteamFriends.FriendMsgCallback` depending whether you want to catch group chat messages, private chat messages, or both. In appropriate function handling the callback you should have extra logic, such as replying with `SteamFriends.SendChatRoomMessage()` or `SteamFriends.SendChatMessage()`.

**Comment by Carnage555** [comment]
Hm, I thought ChatMsgCallback only works in group chats and FriendMsgCallback only gets triggered when a friend sends you a message? I'm looking for a callback that triggers when you send a message, not receive one. Thanks, sorry for the trouble, I'm a bit new to this wrapper!

**Comment by JustArchi** [comment]
Correct, I misunderstood what you wanted to do.

Unless you need to specifically catch your Steam client messages from bot side, I suggest to drop that idea and instead add proper routine for handling sent messages from SK2 code itself. This is much more reliable.

However, there is a callback that is being used for Steam echo that is executed e.g. when you have Steam client opened while chatting from your mobile. This is `ClientFriendMsgEchoToSender (5578)`.

![image](https://user-images.githubusercontent.com/1069029/29764411-4983d9a8-8bd7-11e7-8656-9da4144e957b.png)

However, you'd need to implement it yourself, e.g. in a way how I implemented **[SharedLibraryLockStatusCallback ](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiHandler.cs#L401)**

**Comment by yaakov-h** [comment]
If you want a bot that listens to your own chat messages, EchoToSender is what I'd suggest too. I believe though that it only works for individual messages, but not for groups - neither ad-hoc 3+ group chats nor Steam Community groups.

Otherwise, the standard approach is to give the bot it's own account, and handle incoming chat messages.

**Comment by Carnage555** [comment]
Okay, thanks. I'm fine with it working with individual messages only but I'm a bit confused as to how I would go about implementing it and there seems to be no documentation for this.

**Comment by yaakov-h** [comment]
The Steam client protocol is not documented - partly because nobody could be bothered, and partly because it's continually changing.

In this case, you would need a custom `ClientMsgHandler` (see Sample 2 for an example on how to do this) which handles incoming `EMsg.ClientFriendMsgEchoToSender` messages.

**Comment by JustArchi** [comment]
Like yaakov-h pointed out above, take a look at sample 2 from SK2 which shows perfectly how to code your own handler with your own callbacks and make use of them. If you need more practical examples, you can always peek into my ArchiHandler and ASF, although SK2 example is far better in teaching than plain code being used by somebody else.

Just keep in mind that this callback is not magical solution to all problems. I can confirm that this doesn't work for group/multi-user chats, and there is no way to simulate that even over Steam web, ale Steam web does not handle those chats either. If you can create an account for your bot and implement responses with proper callbacks that I recommended in my first response, then that'll be much better solution than relying on `ClientFriendMsgEchoToSender `.

**Comment by Carnage555** [comment]
Thanks for all the help guys, appreciate it, I figured it out and got it working! The samples really helped, so yeah, thanks again.

I'll take that into account, and I already have callbacks implemented for receiving messages from others and so on, I just wanted to find a way to do this callback as well so that I could use a Steam self bot if ever necessary.
