### ISSUE TITLE
Sometimes NetHook2 dumps no logs

### ISSUE THREAD

**Issue by ThorConzales** [SteamRE/SteamKit#438]
I built a tool that relies on NetHook2 injection to provide data for it: https://github.com/ThorConzales/AoE2HDLobbyCompanion. It has been reported and I have witnessed it too that sometimes no logs are being intercepted and dumped once the injection is complete. It seems to happen randomly and mostly restarting steam client helps, sometimes multiple restarts are required. No unusual logs are being displayed in the console once it happens. Is this a known issue?

**Comment by azuisleet** [comment]
This may be related to the use of WebSocket CM connections

**Comment by ThorConzales** [comment]
Do you also know why and when Steam decides to use WS connection? Currently it seems to be pretty random. More importantly will you guy support WebSocket interception in the future?

**Comment by azuisleet** [comment]
WebSocket is currently done at random when connecting. I believe there are some command line options like -udpforce or -tcp that you can use to steer it.

I don't see any reason we wouldn't also intercept the functions for WebSocket in NetHook, so it's likely going to be supported in the future.

**Comment by ThorConzales** [comment]
Great, will eagerly wait for the WS interception. Based on the that documentation https://support.steampowered.com/kb_article.php?ref=5623-QOSV-5250 there is -tcp flag. However I'm concerned how much of a performance impact it will yield once it is downgraded from UDP in terms of latency. Have you guys played with this flag, are there any performance problems to be concerned about?

**Comment by asherkin** [comment]
`-udpforce` is a recent addition and documented for game servers, so almost certainly also exists for the client.

**Comment by JustArchi** [comment]
SK2 has been working in TCP mode by default since ages if not the first version. Valve's UDP mode is actually more like "tcp over udp" because it still has e.g. packets retransmission.

I doubt it'll result in any major difference.

**Comment by DoctorMcKay** [comment]
There is zero performance difference. And voice chat is independent of the CM connection protocol.

**Comment by VoiDeD** [comment]
#432 for some more discussion of how we might add websocket support for NetHook.

**Comment by VoiDeD** [comment]
@ThorConzales please try the latest version of NetHook.

**Comment by ThorConzales** [comment]
Tested 10 times and worked flawlessly. Did also release it now in my tool, will see if anyone complains. Thanks!
