### ISSUE TITLE
WebAPI throws InvalidDataException on server error

### ISSUE THREAD

**Issue by yaakov-h** [SteamRE/SteamKit#446]
If the server reports an error, the result is usually not a valid VDF document.

WebAPI unconditionally tries to parse this, fails, throwing an InvalidDataException.

Consider checking the status code first, e.g. `HttpResponseMessage.EnsureSuccessStatusCode()`

**Comment by xPaw** [comment]
As far as I know, this does not happen in 1.x releases. I checked my logs, and I only see this exception after upgrading to 2.x. So this maybe needs to be fixed in 2.0 release instead of 2.next.

**Comment by yaakov-h** [comment]
Good point. I've checked the diff, and we used to use `WebClient.DownloadData`, which would throw a `WebException` instead.

With the new APIs, this should translate to a `HttpRequestException`.
