### ISSUE TITLE
Can't use SteamKit

### ISSUE THREAD

**Issue by Rottweiler** [SteamRE/SteamKit#449]
It seems like I cannot use SteamKit2 anymore. It's telling me it's missing netstandard, and System.Runtime, I have no idea what's going on

Is there an alternative library that works?

**Comment by yaakov-h** [comment]
What are you doing?

**Comment by Rottweiler** [comment]
Referencing the project

**Comment by yaakov-h** [comment]
Does it work if you:
1. Reference the NuGet package instead
2. Reference the assemblies instead
?

I assume you have a legacy-style csproj (copious amounts of XML) and not a new-style csproj (a few bits of XML)?

If so, (1) should work with no issues, I think (2) should work in VS2017 15.3.... if project references don't work that sounds like a bug for dotnet/sdk.

**Comment by Rottweiler** [comment]
I think it worked changing target framework to 4.6 if you install it through nuget
