### ISSUE TITLE
Making it possible for using custom HttpClient in WebAPI?

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#450]
This is a random idea I thought about for a second. Since new async WebAPI interface uses HttpClient under the hood, how about making it possible to re-use already initialized and ready HttpClient that is being used by the consumer?

Microsoft recommends to re-use HttpClient as much as possible, going as far as using a single `static readonly` instance across entire program's lifetime. I don't think this is appropriate for our case, as it still takes resources and there is no need to have SK2-dedicated HttpClient if there are no requests happening, but being able to pass `HttpClient` to `GetAsyncInterface()` would be a really nice thing to do in order to re-use existing sockets and entire client initialization. Of course, in such case the client can't be disposed as consumer probably expects it to be used further.

I'm mainly looking at my own use case here, where I already have `HttpClient` being initialized and used for sending requests, so I can re-use it in its current state in order to save memory and overhead of creating another one. Creating a new HttpClient for a single request most of the time is wasted effort, and it can even become **[a serious problem](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/)** in some cases.

Thoughts? I even wanted to send a PR with this right away, but noticed that it'd require more changes (such as base URL rewrite), so I decided to create issue first.

**Comment by yaakov-h** [comment]
This is definitely something to consider.

I saw this same behaviour at work - each `HttpClient` meant a new set of SSL/TLS connections. We moved to a singleton instance and performance drastically improved.

I'm quite tempted to (post-2.0) revisit the entire WebAPI... well, API.

I'm not sure I like the idea of allowing custom `HttpClient`s, since a custom `HttpMessageHandler` could screw with things in subtle ways, then we get blamed for it - but you should definitely be permitted to somehow share an `HttpClient` between multiple `Interface` or `AsyncInterface` objects. We could probably hack that together today by adding it to the `SteamConfiguration` object...

Alternatively, we could make WebAPI a set of extensions to `HttpClient`/`HttpRequestMessage`, and drop the custom dynamic object invocations.

**Comment by VoiDeD** [comment]
`SteamConfiguration` sounds like it may grow to be unwieldy in the future. Wonder if we'll want to have sub-configuration objects or something in the future.

**Comment by yaakov-h** [comment]
That sounds like a good idea.

With `SteamConfiguration` I tried to extract various common settings and static state. I didn't realise there was quite so much of it 😅 

We could possibly subdivide the config with #415.

**Comment by JustArchi** [comment]
I thought about re-using existing `HttpClient` and not necessarily moving to SK2 singleton instance mainly because of the cost. Created and not disposed `HttpClient` takes resources, actually plenty of them, apart from obvious managed memory you have e.g. idle TCP sockets opened in waiting state in case of new request arriving. Since consumer might already have `HttpClient` for his own use case, re-using it gives a lot of benefits.

Singleton instance means that `HttpClient` would be either always allocated, or allocated at first API request, which is both bad as it'll stay in this state until end of the process, which might not be desired if consumer is e.g. sending only one single request across lifespan of his program. I guess the same thing would happen with `SteamConfiguration`, unless you actually want to make it possible for consumer to pass `HttpClient` there, then it's OK and nice (but doesn't solve faulted `HttpMessageHandler` problem).

> Alternatively, we could make WebAPI a set of extensions to HttpClient/HttpRequestMessage, and drop the custom dynamic object invocations.

This is the idea I like the most, but it still suffers from `HttpMessageHandler` problem.

If you ask me, I think that both set of extensions as well as passing `HttpClient` to `SteamConfiguration` is nice, since it's the best solution in terms of performance and the overhead. I just don't like singleton approach for SK2 in this case, as it can result in undisposed `HttpClient` being around, which is negotiable to be even worse than current approach of disposable `HttpClient` per each request, if application is strongly after memory.

**Comment by JustArchi** [comment]
Do multiple `HttpClient`s using the same handler share all initialized ports, sockets and everything else?

If no then I don't see how this would solve the issue of initialization - it'd be probably the same thing, just in different matter. However if yes, then I don't see anything against it - in my original post my objective was to avoid unnecessary resources allocation if consumer is already using `HttpClient` for his own app.

**Comment by yaakov-h** [comment]
> Do multiple `HttpClient`s using the same handler share all initialized ports, sockets and everything else?

I believe so. `HttpClient` is just a thin wrapper around the inner handler.

**Comment by JustArchi** [comment]
Then sure thing, although `HttpClient` does not expose the handler from what I see, so it'd require from consumer a bit of extra logic of initializing his own and SK2 WebAPI with the same handler. Not necessarily a bad thing, it just depends how you look at it. Passing `HttpClient` allows for a bit better tuning, e.g. setting custom `Timeout` without being forced to what SK2 is configured to work with, or exposing extra properties that allow modifying that.

**Comment by JustArchi** [comment]
`HttpClient` seems fine to me, I mean, it's the one that requires least code from SK2, as all properties, the object creation, initialization and everything else is upon consumer, so SK2 won't need to do something like `Timeout => HttpClient.Timeout` just because it created `HttpClient` itself. It's probably the most intuitive approach, as the consumer can also share its own `HttpClient` instead of having two (self and SK2), just with the same handler.

**Comment by yaakov-h** [comment]
The biggest problem with that is that some properties cannot be changed after the first request is made. So if, say we have 3 different `SteamConfigurations` using different WebAPI base domains, we can't request a `HttpClient` from the consumer and then set `HttpClient.BaseAddress` if they decide to re-use instances. We would require a _new_ `HttpClient` to be created, and we can't really enforce that except by creating our own, or throwing exceptions if consumers goof.

Perhaps we need two configuration points - `Func<HttpMessageHandler>` and either `Func<HttpMessageHandler, HttpClient>` or `Action<HttpClient>`.

**Comment by JustArchi** [comment]
That's valid point, although there is also second problem of wanting to use particular `HttpClient` for particular request. For example I might have custom `HttpClient.DefaultRequestHeaders` that I actually want SK2 to use (project identifier), if SK2 decided to create its own `HttpClient` then it'd probably be nice if we somehow could share those properties too, and not just the handler alone. Maybe it could be possible with some hacks like `MemberwiseClone()` but I don't even want to check what could possibly go wrong.

If it was me I'd just ditch `BaseAddress` and use fully qualified URLs, but I'm not sure how nice that solution sounds to you.

**Comment by JustArchi** [comment]
Perhaps it'll be better to consider that initial idea with extension methods, that sounds like it'd be the best solution, and it'd be a consumer that needs to ensure validity of his `HttpClient`. We wouldn't need to jump through hoops like above in this case, while still providing a nice API to call Steam web requests. This also has its own disadvantages though.
