### ISSUE TITLE
SteamID, GroupID..

### ISSUE THREAD

**Issue by Rottweiler** [SteamRE/SteamKit#451]
How can I get the name of the group I'm chatting in? Do you have to somehow translate ChatID to GroupID?

**Comment by yaakov-h** [comment]
You can translate between a chat SteamID and a "clan" (group) SteamID fairly directly. See `SteamFriends.JoinChat` for an example of clan-to-chat. For the other way around, reverse the formula.

We should probably add helper methods to `SteamID` for this.

Note that you can only do this with group chats for a clan. Ad-hoc group chats (i.e. just adding more users into a regular chat) cannot be translated to a clan/group.
