### ISSUE TITLE
Add helper methods to convert chat IDs

### ISSUE THREAD

**Issue by yaakov-h** [SteamRE/SteamKit#453]
See #451.

**Comment by xPaw** [comment]
You want one method that converts `clan -> chat` and other method that does it the other way?

**Comment by yaakov-h** [comment]
I'd think one method in each direction, then `SteamFriends` can just dogfood.

**Comment by JustArchi** [comment]
I'm wondering if we shouldn't take one step further and implement something like `SteamClanID` and `SteamChatID` both inheriting from `SteamID` class.

**Comment by JustArchi** [comment]
Then we can easily convert one to another with something like `SteamChatID chatID = new SteamClanID(12345).ToChatID()`.

**Comment by yaakov-h** [comment]
@JustArchi That would ruin my dream of converting `SteamID` to a struct. 😅 

But implicit conversion operators could make that fairly seamless if we stick with classes.

**Comment by JustArchi** [comment]
TBH this seems like a really good idea to me, in the future those two classes could do something more if we want them to. I like it much more than some generic `public static ulong ClanIDToChatID(ulong clanID)` and vice-versa.

**Comment by yaakov-h** [comment]
I was thinking probably just be `class SteamID { public SteamID ToChatID() }` and vice-versa, given the code required:

            if ( chatId.IsClanAccount )
            {
                // this steamid is incorrect, so we'll fix it up
                chatId.AccountInstance = ( uint )SteamID.ChatInstanceFlags.Clan;
                chatId.AccountType = EAccountType.Chat;
            }

but point taken nonetheless.

(We could even make it an extension method.)

**Comment by JustArchi** [comment]
I just like strong-typing I guess, there is no way to know whether ID is chat or clan without checking `IsChatAccount()` and `IsClanAccount()`. Making it explicit could also aid developers.

In same fashion we could further extend it to `IndividualSteamID` for steam users and so on.

Somebody stop me before this goes too far 😅

**Comment by yaakov-h** [comment]
You'd make a great ObjC or Swift developer. 😄 

https://developer.apple.com/library/content/documentation/General/Conceptual/CocoaEncyclopedia/ClassClusters/ClassClusters.html
