### ISSUE TITLE
Obtaining info about in-game state

### ISSUE THREAD

**Issue by LiteOnE** [SteamRE/SteamKit#454]
I can't seem to find how I can obtain whether a user is in-game or not. Or is it out of scope of SK2?

**Comment by DoctorMcKay** [comment]
If you just want to know if a particular user is playing a game, SteamKit is a bit overkill. You could just use [the WebAPI](https://lab.xpaw.me/steam_api_documentation.html#ISteamUser_GetPlayerSummaries_v2). It will also tell you the IP and SteamID of the gameserver they're on, if that information is available.

**Comment by LiteOnE** [comment]
Thank you, i didn't know that _GetPlayerSummaries_ shows what game user is playing, but it seems to be useless if user is playing non-steam game

**Comment by JustArchi** [comment]
No clue why you'd want non-steam info if user is allowed to put whatever he wants there, including fake info.

**Comment by LiteOnE** [comment]
I don't need non-steam info, I needed only info wether user is in-game or not.
And since the Web API doesn't show any info when person is playing non-steam game, I've not found better way than parsing profile page html code (it's needed only for user's account, so that profile page is always obtainable)

Any better ideas? :)

**Comment by DoctorMcKay** [comment]
I'm fairly certain that the WebAPI does show non-Steam games.

**Comment by LiteOnE** [comment]
That becomes strange, because at least for me it does not show non-Steam games. Could you, please, give me any proofs?

**Comment by DoctorMcKay** [comment]
Weird. I swear it used to, but I guess it doesn't anymore.

**Comment by LiteOnE** [comment]
Found one request (exactly what I need lol) that is used in Web Browser chat: https://steamcommunity.com/chat/friendstate/[SteamID32]
And it returns json that contains info I need and even more ..."m_bInGame":true,"m_nInGameAppID":"","m_strInGameName":""...

So I think I can close it now
