### ISSUE TITLE
Dota 2 send ready bot state

### ISSUE THREAD

**Issue by AncientiCe** [SteamRE/SteamKit#46]
Hello,

I've managed to create a bot that creates a lobby within dota 2 and it launches it.
But didn't figure out how to pass the Failed to load thing. Closed spectators/Moved bot to broadcasting/tried to ReadyUp method after launching the game/Told the bot to quit the game after launching by Abandon etc..
How do i get the lobby_id dinamically? CMsgReadyUpStatus might do the trick.

Is there any other solution or a workaround for the Failed to load when the game launches?

Thanks,
iCe

Off-topic: Where can i find the nethook software so i can investigate things myself?

**Comment by kevelbreh** [comment]
Any updates?

**Comment by chriscapetown** [comment]
Hi - did you have any luck with this?

**Comment by psychonic** [comment]
My understanding is that, for a while now, spectators (and broadcasters) are no longer required to load into a lobby match for it to be able to proceed.

**Comment by AncientiCe** [comment]
Well, i've got the issue fixed as a game bug. So as Nicholas said : the game doesn't fail if spectators don't connect.
But the node app doesn't connect to the server in order to get game info.

**Comment by andertsk** [comment]
@AncientiCe do you solve problem with lobby creation?

**Comment by AncientiCe** [comment]
@andertsk no, and i lost interest in doing that.
However, i believe it's fixed now, since bots can connect to custom games.

**Comment by andertsk** [comment]
@AncientiCe hello, what CMsg* you using for lobby creation?

**Comment by AncientiCe** [comment]
I'm past this project and can't help atm.
You should consider using existing repos:
https://github.com/Arcana/node-dota2
