### ISSUE TITLE
Can't install the alpha packages 1.8.3 is the last i can grab ...

### ISSUE THREAD

**Issue by cyborg-nation** [SteamRE/SteamKit#466]
Could not install package 'SteamKit2 2.0.0-Alpha10'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not 
contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Do I need a later framework or am I just retarded?

**Comment by yaakov-h** [comment]
You might need a newer VS/SDK/NuGet. What are you using to write your code?

**Comment by cyborg-nation** [comment]
Visual studio 2017

**Comment by ObsidianMinor** [comment]
You need the [.NET Core 2.0 SDK](https://www.microsoft.com/net/download/core) to use a .NET Standard 2.0 package in .NET Framework 4.6.1

**Comment by cyborg-nation** [comment]
it's installed even tried it with .net 4.7 still same error.

**Comment by yaakov-h** [comment]
Are you using VS2017 v15.3?

**Comment by cyborg-nation** [comment]
Okay using v15.2 I'll google where i can update and report back sorry missed that thanks.

**Comment by cyborg-nation** [comment]
fixed it for anyone interested alpha 8 and above require an updated version of visual studio which means it's not compatible with the community edition.

Thanks for the real fast support.

**Comment by yaakov-h** [comment]
Community Edition works fine, assuming you use a newer version...
