### ISSUE TITLE
Unified Messages might be broken on netcore

### ISSUE THREAD

**Issue by yaakov-h** [SteamRE/SteamKit#469]
> [05:51:11]  <DuckyC>	im calling this "await cloudService.SendMessage(cloud => cloud.Delete(request));" and it says its not a MethodCallExpression ...
> [06:12:58]  <DuckyC>	i changed this line https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/Handlers/SteamUnifiedMessages/SteamUnifiedMessages.cs#L47 to expr.Body instead and now it works
> [06:13:01]  <DuckyC>	maybe someone should look at that

Might have to fix.

Check with Framework consumers as well as Core consumers... could be Roslyn changes, could be something else.

**Comment by m4dEngi** [comment]
GetISteamUnifiedMessages was marked as DEPRECATED in recent client beta, maybe it's somehow related ... 
https://bitbucket.org/m4dengi/steamclient_tracker/commits/b864d10bd4339d29e1e15895162943011aa639a0#chg-ISteamClient017.h

**Comment by ObsidianMinor** [comment]
It is also marked as deprecated in the [Steamworks API docs](https://partner.steamgames.com/doc/api/ISteamUnifiedMessages)

**Comment by Ne3tCode** [comment]
>marked as deprecated

Not related at all, I suppose.

**Comment by yaakov-h** [comment]
This appears to be purely a SteamKit issue with the way we translate LINQ calls into method names.

I would bet that it's deprecated for SteamWorks consumers, but (a) still used internally by private SDKs (e.g. the OAuth code that Dota 2 used to use) and/or (b) still used internally by the Steam client.

**Comment by yaakov-h** [comment]
This looks more like a compiler change than a runtime change.

On both .NET Framework 4.7 and .NET Core 2.0 I'm now seeing a `LambdaExpression` containing a `MethodCallExpression`, whereas previously we saw just a `MethodCallExpression`.
