### ISSUE TITLE
Get list of library locations

### ISSUE THREAD

**Issue by Foxtrek64** [SteamRE/SteamKit#479]
I need to get a list of Steam Library locations. I've crawled the code but this doesn't seem to be something that exists or I missed it. What's the best way to go about this?

Edit: This should probably return a `List<string>` of paths.

**Comment by xPaw** [comment]
Are you looking for `Steam\steamapps\libraryfolders.vdf`?

SteamKit is an independent implementation of Steam protocol, so you won't find things like this here.

**Comment by Foxtrek64** [comment]
Ah, I see. I was directed towards this library. I think I was able to get it handled though-

    private List<string> GetSteamLibraryLocations()
    {
        List<string> locations = new List<string>();

        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            locations.Add(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), @"Steam\steamapps\sourcemods"));

            List<KeyValue> libraryLocations = ReadLibraryFolders(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), @"Steam\steamapps\libraryfolders.vdf"));
            libraryLocations.ForEach(x => locations.Add(x.Value));
        }
        else
        {
            locations.Add("~/.local/share/Steam/steamapps/sourcemods");
             List<KeyValue> libraryLocations = ReadLibraryFolders("~/.local/share/Steam/steamapps/libraryfolders.vdf");
            libraryLocations.ForEach(x => locations.Add(x.Value));
        }
        return locations;
    }

    private List<KeyValue> ReadLibraryFolders(string filePath)
    {
        if (!File.Exists(filePath)) return new List<KeyValue>();

        KeyValue kv = new KeyValue();
        kv.ReadFileAsText(filePath);
        return kv.Children.Where(x => int.TryParse(x.Name, out _)).ToList();
    }


Not the most elegant code, but it works.

**Comment by JustArchi** [comment]
On Windows I'd use registry, since user could've installed Steam in other file or on different hard drive.

`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Valve\Steam` - `InstallPath`.

**Comment by m4dEngi** [comment]
>  I was directed towards this library

Maybe they meant osw library...
https://github.com/SteamRE/Steam4NET/blob/master/Steam4NET/Autogen/IClientAppManager.cs#L118

But it's dead and abandoned.

**Comment by yaakov-h** [comment]
Also on macOS it’s somewhee under `~/Library/Application Support/`.
