### ISSUE TITLE
Is dumping all networks packets from my program possible?

### ISSUE THREAD

**Issue by MedvedewEM** [SteamRE/SteamKit#486]
I write program with SteamKit2 to connect and logon in steam and get some information about friends, users and etc.
Now I want to dump all networks packets which is sent (and got) by this program to (or from) steam server to know exact order of messages, callbacks and etc.
I find section "Injecting into other executables" in Readme of NetHook2 and follow to instructions but injecting NetHook2 to program's runnig process is failed with error "Invalid process: Target process does not have steamclient.dll loaded".

Do I not understand this section of readme.md or doing something wrong?
Can somebody explain purpose of this section and what I can do with it?
And is there way to dump all networks packets from my program with NetHook2?

**Comment by JustArchi** [comment]
You can do that by attaching listener to SK2 Client `DebugNetworkListener`. Example can be found **[in my ASF](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs#L176)**.

**Comment by MedvedewEM** [comment]
Thank you, I got it!
