### ISSUE TITLE
Get remote IP for current connection

### ISSUE THREAD

**Issue by leonard-thieu** [SteamRE/SteamKit#487]
I'd like to report the remote IP for telemetry purposes. I'm connecting through TCP. Is it possible to get the remote IP for the current connection? From looking through the code, it doesn't appear to be publicly exposed.

**Comment by yaakov-h** [comment]
Not currently.

In theory we could expose this for TCP and UDP connections, but for WebSocket we actually don't know what IP we're connected to - name resolution is handled internally through WinHTTP on Windows, and is similarly done through the CoreFX implementations on .NET Core Linux/macOS.

**Comment by leonard-thieu** [comment]
Okay, so if I wanted to expose this in my own fork, I just need to expose [`CurrentEndPoint`](https://github.com/SteamRE/SteamKit/blob/9677726a829df25b4ebb9febb8e8048fc5cec8dc/SteamKit2/SteamKit2/Networking/Steam3/IConnection.cs#L25) on https://github.com/SteamRE/SteamKit/blob/9677726a829df25b4ebb9febb8e8048fc5cec8dc/SteamKit2/SteamKit2/Steam/CMClient.cs#L99
and expose https://github.com/SteamRE/SteamKit/blob/9677726a829df25b4ebb9febb8e8048fc5cec8dc/SteamKit2/SteamKit2/Networking/Steam3/TcpConnection.cs#L19
through [`CurrentEndPoint`](https://github.com/SteamRE/SteamKit/blob/9677726a829df25b4ebb9febb8e8048fc5cec8dc/SteamKit2/SteamKit2/Networking/Steam3/TcpConnection.cs#L43).

Does that sound about right?

**Comment by yaakov-h** [comment]
Sounds about right. 

The second part *should* have already been done here...

**Comment by xPaw** [comment]
This issue was closed incorrectly, #704 added `PublicIP` which is not the same thing as the remote ip of the server you're connected to.
