### ISSUE TITLE
Could not load Microsoft.Win32.Registry

### ISSUE THREAD

**Issue by Lersubem** [SteamRE/SteamKit#489]
I could install the nuget package of steamkit2 to my solution just like normal, but when i start the app and click login button it gives an error
System.AggregateException: 'One or more errors occurred. (Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040))'
and the error excute in this line
Me.SteamUser.LogOn(New SteamKit2.SteamUser.LogOnDetails With {.Username =Me.Credentials.UserName, .Password = Me.Credentials.Password})
I am trying to build a .net standard 2.0 library in windows 10 fall creator update

**Comment by yaakov-h** [comment]
Sounds like a problem with how you're building your project.

What's your structure?

**Comment by Lersubem** [comment]
This problem occur when using steamkit2 in a . net standard library and use that library in a uwp application, but this problem doesn't occur when using that library in wpf application, this happen because uwp apps doesn't have access to windows registry but wpf apps does.
I have checked the source of steamkit2 and found that steamkit2 tries to get the machine id during the login.

**Comment by yaakov-h** [comment]
It looks like Microsoft.Win32.Registry might not actually support UWP.

I suggest opening a bug at https://github.com/dotnet/corefx

**Comment by Lersubem** [comment]
Its possible for uwp apps to access the with does registry because they are sandboxed apps. Syeamkit2 should not try o access the registry on uwp apps because this is the only way o support uwp apps.

**Comment by yaakov-h** [comment]
We target .NET Standard 2.0.

Registry is part of .NET Standard 2.0.

UWP Fall Creators supports .NET Standard 2.0.

We’re not doing anything wrong, as far as I can tell, this is purely a Microsoft issue.

**Comment by Lersubem** [comment]
Check this https://social.msdn.microsoft.com/Forums/vstudio/en-US/51f12da0-ce81-4dbf-bafe-1cba5af2fb15/how-to-read-registry-in-windows-10-universal-app?forum=wpdevelop

**Comment by yaakov-h** [comment]
Yeah, that’s from two years ago from a very different from of UWP. It predates .NET Standard.

**Comment by Lersubem** [comment]
Ok then check this https://social.msdn.microsoft.com/Forums/vstudio/en-US/be1cb242-4293-4d1e-9b85-0cac692ae1a4/microsoftwin32registry-not-working-in-net-standard-20-library?forum=netfxbcl

**Comment by Lersubem** [comment]
And if its a Microsoft issue then we have to wait for an update to fix it

**Comment by yaakov-h** [comment]
Either way that would result in a native error or exception, not a missing DLL.

See what dotnet/sdk and dotnet/corefx have to say about registry on UWP, then come back.
