### ISSUE TITLE
Own SetPersonaState (like = "In Game = 1 Key for ....")

### ISSUE THREAD

**Issue by TwoCrime** [SteamRE/SteamKit#490]
How can i set SetPersonaState to like "1 Key for 16 Sets" or something like that.
So how can i set currently playing for my own text?

**Comment by Logxn** [comment]
You cant.
People add non-steam games/applications to Steam (ex. their Webbrowser, Spotify) and change the name in the steam library settings to "1 Key for 16 Sets" for example

**Comment by JustArchi** [comment]
Or they just use appropriate reverse-engineered function, like my ASF does.

**Comment by Logxn** [comment]
what do you mean? 
I cant find the line in your ASF where you set the name of the online state...

You only seem to be setting the PersonaState to online

**Comment by JustArchi** [comment]
**[If you say so](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiHandler.cs#L97)** 😉

**Comment by Logxn** [comment]
Yeah well, this is in the current steamkit build either way.
Just add extra_info "1 Key for 16 Sets" and app id = 730 and it will start csgo with that name tho.

**Comment by JustArchi** [comment]
Then maybe you should take a closer look, because ASF doesn't require specifying any game for custom status.

**Comment by Logxn** [comment]
string gameName = null
game_extra_info = gameName,

I am confused

**Comment by JustArchi** [comment]
You're confused about **[named and optional arguments](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments)** of C#? 😉

**Comment by Logxn** [comment]
So if this is an optional parameter, you must have the custom name set in the proto itself, because its not getting set in that function

**Comment by JustArchi** [comment]
Or maybe you're trying to read entire thing too fast instead of slowly analyzing the function and how ASF makes use of it, because I'm no longer sure if you lack basics of C# or you don't want to understand what is happening inside - I just said that you can use this function for setting yourself to custom in-game status without specifying any gameID being played, which is correct.

**Comment by Logxn** [comment]
Sorry I misunderstood - it's been a long day.
What you tried to tell me is that I can specify a custom name in extra_info, without specifying an app_id, correct? 😅

**Comment by JustArchi** [comment]
**[Correct](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiHandler.cs#L115-L121)**, and that's also what I'd suggest to use if somebody just wants to display custom status - I don't see a need to hardcoding any gameID at all 🙂
