### ISSUE TITLE
SteamFriends.SetPersonaState() task never returns?

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#491]
Consider following code in `async OnLoggedOn()`:

```
try {
	await SteamFriends.SetPersonaState(EPersonaState.Online);
} catch (Exception e) {
	Console.WriteLine(e);
}
```

`SetPersonaState()` returns awaitable `AsyncJob`, but compared to other async jobs I'm awaiting, this one seems to never return. I suspect this is because in fact there is no Steam Network response in `SetPersonaState()`, so despite of request succeeding, `TaskCanceledException` is always raised in 10 seconds since request being sent.

I reproduced this more than dozen of times already, even adding `await Task.Delay(10000).ConfigureAwait(false)` before call just to ensure it's not some packet disappearing when callback manager is busy handling other things immediately after logging in, no luck. Perhaps it was already fixed in #481 and I just coincidentally reproduced it just now?

Thing is, I reproduced it in console app, and my understanding is that there should be no issue like #481 in my case, so maybe it's just false logic of `SetPersonaState()` returning `AsyncJob` when it should just return `void` instead.

Thank you in advance.

**Comment by ObsidianMinor** [comment]
That must have been a very recent change. Normally I've seen Steam respond to those types of jobs with ClientPersonaChangeResponse (5584) but it looks like it doesn't anymore.

**Comment by JustArchi** [comment]
It's good that you were able to reproduce it too, so I'm not alone with this 🙂. I've noticed this issue since a longer while, so we can assume it's permanent and not something temporary - I just silently ignored this exception before as I thought that it was just some temporary quirk. But now after a longer while I decided to report this so maybe we should correct it.

**Comment by yaakov-h** [comment]
Steam sends `ClientChangeStatus` and receives `ClientPersonaState`, but neither of them have Job IDs.

**Comment by yaakov-h** [comment]
`PersonaChangeResponse` hasn't been removed from Steam, and Steam doesn't set JobID on the `ClientPersonaState` corresponding to the `ClientChangeStatus`.

I wonder if it's an accidental change on Valve's end or an intentional protocol change.
