### ISSUE TITLE
Unknown notification types

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#493]
I'm currently trying to reverse-engineer `CMsgClientUserNotifications.Notification`'s `user_notification_type` and map it to proper event. I managed to find out that `uint32` of `1` should be mapped to number of trade notifications, could somebody check out what other values are currently being used by official Steam client? I'm especially interested in value of `10`. Perhaps @VoiDeD? I noticed you're already **[familiar](https://github.com/SteamRE/SteamKit/issues/413#issuecomment-315553230)** with this 🙂.

I'd do that myself but I have zero knowledge about Steam client decompilation, and rather poor knowledge about asm/C/C++ in this regard. I guess that info could be also helpful in future SK2 implementation of this, perhaps I'll even port it myself from my WIP part in ASF. Thanks!

**Comment by Ne3tCode** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/blob/eacb85c711232ed72b30e8dccaabd147f48a5c63/index.js#L324-L336
`10` is a reply from [Steam Support](https://help.steampowered.com/en/wizard/HelpRequests)

**Comment by JustArchi** [comment]
Thanks! ❤️

**Comment by yaakov-h** [comment]
For the record, the function is quite confusing to disassemble, but the code in Steam Client appears to be:

```
1. Trade Offers
2. Async Games
3. Moderator Messages
4. and 8. are handled the same.
7. Looks like a no-op of some kind
9. My Help Requests
10. Help Request Replies
```

I lost 5 and 6 somewhere.

That's close enough to what's above that I'd trust it. 😄 

Also if you're after the name, Steam calls the enum `EUserNotification`.
