### ISSUE TITLE
reportbot

### ISSUE THREAD

**Issue by qp1990** [SteamRE/SteamKit#494]
Hi;

I have a problem with my reportbot, this is the next error;

gc_msg_src: 'GCProtoBufMsgSrc_Unspecified' } }
{ msg: 9194,

**Comment by yaakov-h** [comment]
Okay, and...?

**Comment by qp1990** [comment]
Do you know what error is and how to fix it?

**Comment by yaakov-h** [comment]
You haven't even described an error yet.

Would you like to start again?

**Comment by qp1990** [comment]
When starting the report bot, i report with the accounts and in doing so, that error comes out

**Comment by yaakov-h** [comment]
I'm going to need more information or I'll just close this.

1. What's this "report bot" you speak of?
2. What does "report with the accounts" mean?
3. What's the error? You've posted what appears to be a snippet of JSON without any context.

**Comment by JustArchi** [comment]
I don't recall SK2 having any "report bot" functionality, are you sure you're in the correct project in the first place?

**Comment by qp1990** [comment]
is the famous reportbot node js by askwrite, its function is to report with own accounts of the game CS: GO to people who are cheats, and when being reported goes directly to Overwatch, since there has been an update this error comes out

this is the error:

https://i.gyazo.com/acf5d82899ed87241aa9640f6425628e.png

**Comment by qp1990** [comment]
reportbot: https://github.com/Askwrite/node-csgo-reportbot

**Comment by yaakov-h** [comment]
Ask there, then. This is clearly not that.

**Comment by JustArchi** [comment]
> reportbot
> node js

And you have even entire issues section of the project you've linked, yet you decided to post issue in completely irrelevant place that has nothing to do with your app 😕

**Comment by qp1990** [comment]
No one answers in that section, and I see that here you know the subject, I just wanted to know if you can lend me a hand

**Comment by yaakov-h** [comment]
You haven't even managed to explain the problem clearly.... no we cannot lend you a hand, given the circumstances.

**Comment by qp1990** [comment]
I do not know what you want to know more, when reporting that error comes out that i put in the photo
