### ISSUE TITLE
Which callbacks should be registered in given connection states?

### ISSUE THREAD

**Issue by leonard-thieu** [SteamRE/SteamKit#499]
There are obvious callbacks that should be registered when calling something that can change connection state (`ConnectedCallback` for `Connect`, `LoggedOnCallback` for `LogOn`). However, there seems to be less obvious callbacks that should be registered along with these. For example, `DisconnectedCallback` is used to communicate connection failures, so it should be registered while connecting. 

I'm interesting in knowing which callbacks should be registered in different connection states.

### Connecting

* `ConnectedCallback` - Listening for connect success
* `DisconnectedCallback` - Listening for connect failure
  * `ConnectionTimeout` elapsed (?)
  * Disconnected by server (?)

### Connected

* `DisconnectedCallback` - Listening for disconnect

### Logging on

* `LoggedOnCallback` - Listening for log on complete
* `LoggedOffCallback` (?)
* `DisconnectedCallback` (?)

### Logged on

* `LoggedOffCallback` (?)

**Comment by yaakov-h** [comment]
It all depends what you're doing.

`ConenctedCallback` tells you when the connection has opened.

`DisconnectedCallback` tells you when the connection has been closed, or has failed to open.

There are two of the above, one for `SteamClient` and one for `UFSClient`.

`LoggedOnCallback` - well, we have a couple of those, for individual accounts versus game server accounts. These tell you when logon is complete - either successfully, or failed with an `EResult`.

`LoggedOffCallback` in my experience is only fired when the servers log you off, e.g. another machine logs in and this results in your current session being forcibly ended.

When you call `SteamUser.LogOff` yourself, IIRC Steam just closes the connection, which gives you a `DisconenctedCallback`.

These can all change at any time subject to Valve though, so don't go carving anything into stone.

**Comment by JustArchi** [comment]
`LoggedOffCallback` happens rarily, but I've seen some of those with `EResult` of `Fail`, I'm not entirely sure why. The best thing is how those happened **without** actual disconnection of the client, just popped up like this without any reason.

I'd say this one can be easily ignored. If you lose session for any reason then `DisconnectedCallback` will arrive regardless.

**Comment by leonard-thieu** [comment]
To clarify, yes, I am indeed referring to the callbacks on `SteamClient` and `SteamUser`. I'm trying to ensure that my async wrappers around `Connect` and `LogOn` are written correctly. Going off [this comment](https://github.com/SteamRE/SteamKit/issues/496#issuecomment-349027066) by @VoiDeD, it seems that it's worth registering `LoggedOffCallback` for diagnostic purposes.

**Comment by JustArchi** [comment]
Diagnostic purposes such as writing received callback to the log is OK, but you should not have any logic that would normally be triggered if you're logged off - that's what disconnected callback is for.

**Comment by yaakov-h** [comment]
@JustArchi only if you actually get disconnected... I don't remember if you can get logged off without being disconnected. If so, and you don't handle the logged off callback, you'll be stuck in limbo.

**Comment by JustArchi** [comment]
Tell that to Steam network fuckup I've experienced when `LoggedOffCallback` arrived with `EResult` of `Fail` but bot was perfectly operative and logged on 😆

**Comment by JustArchi** [comment]
I'm just saying that I'd not trust this callback because of the above, finding out if it's indeed possible to have a **valid** logged off callback that doesn't trigger disconnected callback afterwards could be interesting, since in this case indeed it'd make sense to handle it, although I did not experience one just yet. And I've experienced enough of those `Fail` ones that don't seem to trigger anything specific.

**Comment by yaakov-h** [comment]
It's probably best to just disconnect and reconnect when you get that callback, just to be safe.
