### ISSUE TITLE
hello how to get Steam2Ticket

### ISSUE THREAD

**Issue by fanld2007** [SteamRE/SteamKit#504]
excuse me, when i use the sdk, i want to get the Steam2Ticket value, and i set the RequestSteam2Ticket to true,but when login callback ,the Steam2Ticket  is still null,can you tell me how to get this value ? thank you

**Comment by yaakov-h** [comment]
What on earth do you need a Steam2 ticket for? Steam2 is long dead.

**Comment by fanld2007** [comment]
hi:
    i want the ticket to get a player statistics data from pubg game, do you know
how to get the ticket?


thank you 
On 12/25/2017 14:03，Yaakov<notifications@github.com> wrote：

What on earth do you need a Steam2 ticket for? Steam2 is long dead.

**Comment by yaakov-h** [comment]
Whatever PUBG is using, it's not Steam2.

**Comment by fanld2007** [comment]
hi:
  https://github.com/SteamRE/SteamKit/releases/tag/2.0.0-Beta.1,the latest version steamkit is version2.0, i use this version 
On 12/25/2017 14:07，Yaakov<notifications@github.com> wrote：

Whatever PUBG is using, it's not Steam2.

**Comment by yaakov-h** [comment]
What?
