### ISSUE TITLE
How to get api key?

### ISSUE THREAD

**Issue by StasBalia** [SteamRE/SteamKit#505]
Hello, can you tell me, how did you get api key for your application?

**Comment by yaakov-h** [comment]
Please clarify.

**Comment by StasBalia** [comment]
I need to provide domian name. Is it domain name for site or for app?

**Comment by VoiDeD** [comment]
What are you trying to accomplish? A web API key is only necessary for interacting with Steam's web API.

If you're using SteamKit to interact with the web API, the domain you provide when registering for an API key is the domain of your site that will be using the key (or the name of your application).

**Comment by StasBalia** [comment]
> (or the name of your application).
That is exactly what i'm talking about. I'm new in web API so i confused when saw domain name. I thought it work only with site.Thank you.

**Comment by VoiDeD** [comment]
It's also worth mentioning that we're not affiliated with Valve, in case
that wasn't clear. So your mileage may vary with any recommendation given
here.
