### ISSUE TITLE
Undocumented breaking change in WebAPI

### ISSUE THREAD

**Issue by RudeySH** [SteamRE/SteamKit#516]
Because `HttpClient` is being used instead of `WebClient`, exceptions thrown are now of type `HttpRequestException` instead of `WebException`. That should be documented somewhere, people who update SteamKit have to double-check their catch blocks now.

**Comment by xPaw** [comment]
That's documented in release notes for 2.0 under breaking changes. https://github.com/SteamRE/SteamKit/releases/tag/2.0.0

**Comment by RudeySH** [comment]
Oh my, totally missed that. Sorry!
