### ISSUE TITLE
How to get the (bad) status code that was returned in WebAPI?

### ISSUE THREAD

**Issue by RudeySH** [SteamRE/SteamKit#517]
Before 2.0.0, SteamKit used `WebClient` which throws `WebException`. That exception allowed us to find the corresponding response status code.

Now, it uses `HttpClient` which throws `HttpRequestException`, which is purposely designed not to expose a status code. The consensus is that when using `HttpClient`, we are supposed to use the response object to determine the status code ourselves. This response object is not exposed by SteamKit, unfortunately.

I hoped the `InnerException` of `HttpRequestException` would be of type `WebException`, but unfortunately it seems to be `null` all the time.

I need the status code to determine if a failed request was either forbidden (403) or bad request (400).

**Comment by RudeySH** [comment]
This issue is preventing me from using 2.0.0.

For example calling ISteamUserStats/GetPlayerAchievements could result in a 400, which can safely be ignored because that just means the given appid has no achievements. However, any other status code could indicate there was a real problem, such as reaching the request limit.

**Comment by yaakov-h** [comment]
Unfortunately the standard .NET behaviour only puts together a string-based error message. As you can see [here](http://source.dot.net/#System.Net.Http/System/Net/Http/HttpResponseMessage.cs,4e37ee74287ee7df), the status code itself only makes it into the call to `string.Format`, but not into the exception's constructor itself.

The only standard way I have found - across many projects - is to figure out why it failed is to parse the exception message. Yes, this is an awful hack.

Alternatively, we could throw our own exception type, but this would be yet another breaking change.

Perhaps we could shove the status code into the `Exception.Data` dictionary...

**Comment by xPaw** [comment]
This was fixed by #603

**Comment by RudeySH** [comment]
When will a new SteamKit NuGet package be released? (are there pre-release MyGet feeds available?)
