### ISSUE TITLE
Nethook dumps nothing on Steam beta client

### ISSUE THREAD

**Issue by rossengeorgiev** [SteamRE/SteamKit#518]
![image](https://user-images.githubusercontent.com/2720787/35016580-25633b78-fb11-11e7-9929-d5849063f7cd.png)

**Comment by yaakov-h** [comment]
Are you using an old version of NetHook?

Newer builds should also detour methods in `CWebSocketConnection` - see #439.

**Comment by rossengeorgiev** [comment]
That seems to be the case. For some reason I had older version of NH, but everything else was latest.
