### ISSUE TITLE
NH2 broken on latest Steam beta client

### ISSUE THREAD

**Issue by rossengeorgiev** [SteamRE/SteamKit#520]
```
CCrypto::SymmetricEncryptChosenIV = 0x77aad800
Unable to find GetMessageList.
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x77b46c70
CCMInterface::RecvPkt = 0x0
Detoured CWebSocketConnection::BBuildAndAsyncSendFrame!
Unable to hook CCMInterface::RecvPkt: func scan failed.
Wrote 28 bytes to 001_out_703_(null)
```

**Comment by Joshgozner** [comment]
I'm getting the same message

`CCrypto::SymmetricEncryptChosenIV = 0x37976850`
`Unable to find GetMessageList.`
`Detoured SymmetricEncryptChosenIV!`
`CWebSocketConnection::BBuildAndAsyncSendFrame = 0x37a09040`
`CCMInterface::RecvPkt = 0x0`
`Detoured CWebSocketConnection::BBuildAndAsyncSendFrame!`
`Unable to hook CCMInterface::RecvPkt: func scan failed.`
