### ISSUE TITLE
Unable to hook into steam

### ISSUE THREAD

**Issue by Cr3zi** [SteamRE/SteamKit#521]
`CCrypto::SymmetricEncryptChosenIV = 0x37976850`
`Unable to find GetMessageList.`
`Detoured SymmetricEncryptChosenIV!`
`CWebSocketConnection::BBuildAndAsyncSendFrame = 0x37a09040`
`CCMInterface::RecvPkt = 0x0`
`Detoured CWebSocketConnection::BBuildAndAsyncSendFrame!`
`Unable to hook CCMInterface::RecvPkt: func scan failed.`

![st](https://user-images.githubusercontent.com/32521239/35742147-73d89688-07ee-11e8-9151-820730ec7506.PNG)

**Comment by VoiDeD** [comment]
If you're building nethook from tip, you'll want to use the latest steamclient beta. Alternatively, you'll want to build from 33997711c1996cf4e7655bc99fe0e1d4eae7205c, see #520.

**Comment by Cr3zi** [comment]
That worked, thank you!
