### ISSUE TITLE
Outdated protobufs

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#523]
Today I got **[EPurchaseResultDetail](https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/enums.steamd#L352)** with value of `69`, I'd appreciate protobufs update, thanks! 🙂

**Comment by yaakov-h** [comment]
Nice.

Any idea what that value represents?

**Comment by JustArchi** [comment]
No clue. I don't even know where original `EPurchaseResult` definition comes from. Perhaps @psychonic could help us here.

**Comment by psychonic** [comment]
If not in the protobufs, the original ones may have came from steamclient bins with DWARF data. Valve accidentally releases one somewhere every few years or so.

**Comment by yaakov-h** [comment]
Do you remember where you got them from? https://github.com/SteamRE/SteamKit/commit/afda0753a3894c5c1fc4056aaf27ecc3f83426cb

There's a much older list in open-steamworks... https://github.com/SteamRE/open-steamworks/blob/master/Open%20Steamworks/BillingCommon.h#L99

**Comment by Ne3tCode** [comment]
https://github.com/SteamDatabase/SteamTracking/blob/master/Scripts/Store/checkout.js#L917

**Comment by JustArchi** [comment]
```
error_text = 'Your order cannot be completed because your cart contains items that are reserved for commercial use only.';
```

... what? 😆

Still, would be cool to get official names for those.

**Comment by yaakov-h** [comment]
.... do I want to know why Valve's switch statement is not in numerical order? ಠ_ಠ
