### ISSUE TITLE
NetHook2 does not work with the Steam client Update from March 19

### ISSUE THREAD

**Issue by psikorski** [SteamRE/SteamKit#529]
`CCrypto::SymmetricEncryptChosenIV = 0x38564940`
`Unable to find GetMessageList.`
`Detoured SymmetricEncryptChosenIV!`
`CWebSocketConnection::BBuildAndAsyncSendFrame = 0x385fde10`
`CCMInterface::RecvPkt = 0x38150040`
`Detoured CWebSocketConnection::BBuildAndAsyncSendFrame!`
`Detoured CCMInterface::RecvPkt!`

**Comment by yaakov-h** [comment]
```
CCrypto::SymmetricEncryptChosenIV = 0x37884940
Unable to find GetMessageList.
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x3791de10
CCMInterface::RecvPkt = 0x37470040
Detoured CWebSocketConnection::BBuildAndAsyncSendFrame!
Detoured CCMInterface::RecvPkt!
Wrote 144 bytes to 001_in_766_(null)
Wrote 49 bytes to 002_in_822_(null)
Wrote 49 bytes to 003_in_822_(null)
Wrote 22 bytes to 004_out_703_(null)
```

GetMessageList has either changed again, or reverted to the old implementation.

Either for the functions that we did find, something's changed as well - either we're finding the wrong function, or the message bytes have changed, etc.

**Comment by yaakov-h** [comment]
It looks like the new `GetMessageList` is `sub_385D4B40`, but `makesig.idc` doesn't work for me in IDA Freeware 7.0.

```
Warning
C:\Temp\makesig.idc.txt: Runtime error on C:\Temp\makesig.idc.txt:54: No such attribute: object.dtyp
[ OK ]
```
