### ISSUE TITLE
How to get games and achievements using SteamKit

### ISSUE THREAD

**Issue by jurzer** [SteamRE/SteamKit#531]
Good afternoon, everybody! 

Help please deal in SteamKit, desirable examples. On Steam, I logged in as I get a list of games on my account and achievements. I probably just don't understand how to use SteamKit functions. 

I can get games and account achievements without using SteamKit, via the Web API, but it only works for public accounts. I assume that logging into your account through SteamKit privacy settings are ignored and I will get a list of their games and achievements even if my profile is hidden on the Internet.

**Comment by azuisleet** [comment]
On login, you are given a callback LicenseListCallback which gives you the list of packages owned by an account. Here's an example of that:
https://github.com/SteamRE/DepotDownloader/blob/6552734faf021ae37b7602e7c4896f5a7c23b98b/DepotDownloader/Steam3Session.cs#L573

Once you have a list of packages, you need to use PICS to resolve the packages and the apps of interest. Here's an example of enumerating the packages and caching app ids:
https://github.com/SteamRE/DepotDownloader/blob/6552734faf021ae37b7602e7c4896f5a7c23b98b/DepotDownloader/Steam3Session.cs#L205

Finally, you can resolve the app info by requesting access tokens with PICSGetAccessToken for the apps of interest and retrieving them with PICSGetProductInfo. An example of this is available here, but you would batch together a single PICSGetAccessToken call and as many PICSRequests into one call as necessary:
https://github.com/SteamRE/DepotDownloader/blob/6552734faf021ae37b7602e7c4896f5a7c23b98b/DepotDownloader/Steam3Session.cs#L148

**Comment by azuisleet** [comment]
Achievements look like they come from CMsgClientGetUserStats and CMsgClientGetUserStatsResponse (EMsg.ClientGetUserStats and EMsg.ClientGetUserStatsResponse). I don't have any examples of these so you'll have to construct and parse the protobuf messages for the two classes: https://github.com/SteamRE/SteamKit/blob/7640dfe40323d4b64e0eb562b43a6108535b9ef4/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L578

**Comment by jurzer** [comment]
Thank you for the answer!
With these examples figured it out. Achievements user, like, too, received. But the enumeration uses the achievement_id, I do not know what to associate these identifiers with. WebApi GetPlayerAchievements returns only the name, without numeric identifiers. Possible schema (message CMsgClientGetUserStatsResponse ) contains a description, but it is in bytes. How to read?

https://github.com/SteamRE/SteamKit/blob/7640dfe40323d4b64e0eb562b43a6108535b9ef4/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L585

**Comment by azuisleet** [comment]
You'll have to inspect it, but the most likely candidate is binary KV (KeyValue.TryReadAsBinary), here's an example:
https://github.com/SteamRE/SteamKit/blob/5fbf66012ffb8914475037c8859acc465c8b719a/SteamKit2/SteamKit2/Steam/Handlers/SteamApps/Callbacks.cs#L486

**Comment by jurzer** [comment]
Yes, it works. Thank you very much for your help! 
Question can be closed.

**Comment by jurzer** [comment]
I went into a dead end, open the question again. 

All that is described above happened, I get the time to open the achievement but do not get any identifiers to find out what it refers to. In some games in the parameter "scheme" there are fields on which you can at least identify something, but this is a rarity, and besides the set can be very individual. 

![2018-04-30_15-34-21](https://user-images.githubusercontent.com/16665920/39427362-226523d8-4c8c-11e8-87d3-5be039ae2e86.png)

Any ideas how to achieve a given app? Can you get a page and parse it?

Everything works through the Web Api, but only for public profiles.

**Comment by jurzer** [comment]
Still wanted to clarify. Using SteamKit2 violates any Steam user agreement? I want to write those in the official Steam support, maybe they can help with the answer to my question.

**Comment by yaakov-h** [comment]
It probably does, I am not a lawyer and this is not legal advice, but Valve don't seem to mind unless you do something malicious or stupid.

I don't think Steam Support will be able to help in anything beyond the Steam Web APIs.

**Comment by jurzer** [comment]
Yes, Valve technical support did not help. I am still trying to resolve this issue, if you have any ideas, please write.

**Comment by yaakov-h** [comment]
Closing as stale. I still don't know the answer, and it doesn't seem to have bugged you enough to ask again in the last year. 😄.
