### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by niemand-sec** [SteamRE/SteamKit#535]
Hi there,

I have tried to compile the last version of NetHook2 but I'm getting the following message when I try to run `rundll32 NetHook2.dll,Inject`: 
```
There was a problem starting NetHook2.dll
The specified module could not be found. 
```
I used VS2015 with v140 build tools as you recommend. I'm using the dll on w7 x64 SP1.

I tried to use the last release but due to this issue it didn't work: https://github.com/SteamRE/SteamKit/issues/520

When are you planning to release a new version including those fixes? Any suggestion that could solve this problem?

**Comment by psychonic** [comment]
If you compiled with VS2015, you need to make sure the machine you run it on has the VC++ 2015 redistributable installed (the 32-bit version since NetHook2 is a 32-bit dll).

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by niemand-sec** [comment]
Thank you so much, it seems that I had the VC++ 2015  redistributable for x64 but not for x32.

I'm closing the issue.
