### ISSUE TITLE
Getting a list of non-friend users?

### ISSUE THREAD

**Issue by Earu** [SteamRE/SteamKit#538]
Well, everything is in the title. How would you go about getting a list/collection of steam users/steam ids that are not friends of the current account used?

**Comment by VoiDeD** [comment]
By non-friends, do you mean users related to the current user in other sources (steam groups, current game, etc)?

**Comment by Earu** [comment]
No you are right but I'm not sure how steam does it for its webpage either.

**Comment by yaakov-h** [comment]
They probably index everything on the backend.

I'll close this as it's now out of scope for SteamKit.
