### ISSUE TITLE
The Steam client disconnects from the network when SteamKit2 connects

### ISSUE THREAD

**Issue by jurzer** [SteamRE/SteamKit#540]
Good day! 
There was a problem when a connection is established with Steam by means of SteamKit2, the official Steam client is disconnected from the network (account one). On the computer on which I develop, such a problem is not observed, but on the other, which tested the problem is. 

I assumed that when a device is added to the list of allowed devices, it is given a name and apparently it coincided with the one already added by the same computer. But this assumption. 

How can I solve this problem, it is critical, as both my application and the Steam client should work in the same account?

**Comment by JustArchi** [comment]
Check `LoginID` property of `SteamUser.LogOnDetails`.

**Comment by jurzer** [comment]
Thank You! 
I suspect that it will be quite simple, but could not clearly determine the desired property.
