### ISSUE TITLE
WebAPI should support proxy option

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#541]
Currently WebAPI offers no way for accessing `Proxy` and `UseProxy` properties of internal `HttpClient`, making it impossible to supply those. Such option can be beneficial for people behind firewalls (e.g. in China) that can't access several Steam web-services, especially `steamcommunity.com` in a normal way. I'm not sure if API is restricted itself, but it definitely won't hurt to have such possibility.

This issue will be entirely resolved "by the way" while working on https://github.com/SteamRE/SteamKit/issues/450, therefore it might make sense to get down to that one instead and achieve 2 in 1.

**Comment by yaakov-h** [comment]
Yep, #450 should cover this. I’m hoping to start tackling that in the coming weeks.

**Comment by yaakov-h** [comment]
Done in #605.
