### ISSUE TITLE
StreamHelpers does not appear to be thread-safe

### ISSUE THREAD

**Issue by yaakov-h** [SteamRE/SteamKit#553]
All read operations share the same buffer.

I'm surprised this hasn't caused a bug yet.

**Comment by yaakov-h** [comment]
Also, `ReadAndDiscard` appears to be dead code.

**Comment by yaakov-h** [comment]
The whole class is dead code. Delete.

**Comment by xPaw** [comment]
It's not dead code, as these are added as extension methods to `Stream`, which are used.

**Comment by yaakov-h** [comment]
Ugh. You're right, it is used, Visual Studio just appears to suck at finding references to extension methods.
