### ISSUE TITLE
SteamGuard sample doesn't work

### ISSUE THREAD

**Issue by rtm516** [SteamRE/SteamKit#555]
I have cloned the repo and when trying to use the SteamGuard example I get a successful login first time.
```
Connecting to Steam...
Connected to Steam! Logging in 'rtm516'...
This account is SteamGuard protected!
Please enter your 2 factor auth code from your authenticator app: FNFHK
Disconnected from Steam, reconnecting in 5...
Connected to Steam! Logging in 'rtm516'...
Successfully logged on!
Updating sentryfile...
Done!
```
Then after restarting it askes me for the code again.
```
Connecting to Steam...
Connected to Steam! Logging in 'rtm516'...
This account is SteamGuard protected!
Please enter your 2 factor auth code from your authenticator app:
```

Version: https://github.com/SteamRE/SteamKit/commit/49c61b615970a0ea5ca73fe6f6ab0eb78be9565c

**Comment by xPaw** [comment]
Using authenticator app means you have to enter the code every time. This only works for email steamguard.

**Comment by rtm516** [comment]
So there anyway of getting it to work? As I believe ArchiSteamFarm allows this to work with mobile auth using this library.

**Comment by yaakov-h** [comment]
I believe ASF stores a copy of the second-factor secret key and generates a code on each login attempt.

**Comment by JustArchi** [comment]
@yaakov-h is correct, ASF uses **[login keys](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs#L2203)** for that.

**Comment by JustArchi** [comment]
It's also nice to note that login keys seem to never be designed to be used for more than one persistent session. They work at first, but it doesn't take a lot of days to notice that login keys are no longer accepted on Steam's part, effectively making one out of your sessions impossible to move forward - either your own Steam client, or your bot (if you use both for your account that is).

In general it's really buggy, at least from my own experience. It works at first and nothing really suggests that it'll stop working, then 2 weeks later you find out that it no longer works despite of you not doing anything special and successfully using login keys for your last 10 logins across those 2 weeks ¯\_(ツ)_/¯

**Comment by yaakov-h** [comment]
I could be wrong, but my understanding is:

- Login keys prevent users from being asked for their password again.
- Login keys do not prevent users from being asked for a second-factor authentication code again.
- Login keys combined with an existing session ID might prevent a user from being asked for second-factory authentication code again, but I'm not sure about this and haven't done much (any) testing.
- Accounts can only have one active login key at a time. If two clients log in to Steam, only the latest one gets a valid login key.

**Comment by JustArchi** [comment]
I've also thought that it should work like that, but reality is different.

- Login keys prevent users from **authorization**
- Login keys skip a need of providing 2FA code entirely
- Login keys do not depend about sessionID at all, unless you meant machine ID, as you can have valid login key for entire week with multiple sessions in the meantime.
- Accounts can have multiple active login keys at the same time - I verified it long time ago before 2FA even took place, and neither my own machine with official Steam client, nor my server with ASF powered by SK2 required a need to input a password. Moreover, I launched a 3rd app on my PC (this was after my addition of `LoginID`) and it worked as the 3rd one - all 3 had entirely different login keys.

Now whether it's supposed to work like this, that's entirely different story 😅

**Comment by rishav394** [comment]
I don't know if this is still relevant but if you manage to get the shared_secret from the steam App you can generate steam guard every single time. Profit.

```
var account = new SteamGuardAccount {SharedSecret = secure};
var loginCode = account.GenerateSteamGuardCode();
```
Of-course it requires you to use `SteamAuth` though.
