### ISSUE TITLE
No ServerRecord.CreateCreateSocketServer(string address) overload

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#557]
This is inconsistent with `CreateWebSocketServer` which has a string overload, but no IPEndPoint overload, and vice versa. This makes it harder to consume these APIs.

SK itself has to parse socket servers when using it: https://github.com/SteamRE/SteamKit/blob/5fbf66012ffb8914475037c8859acc465c8b719a/SteamKit2/SteamKit2/Steam/WebAPI/SteamDirectory.cs#L64-L77

**Comment by yaakov-h** [comment]
Hmm, good point. I thought that we got TCP/UDP servers as integers, not strings, but I think we only get that over the CM protocol, and strings over WebAPI.
