### ISSUE TITLE
ServerRecord constructor is internal

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#558]
It appears that I can't create a `ServerRecord` with `ProtocolTypes.TCP` because:

1. Can't access the constructor
2. `ProtocolTypes` is not assignable.

If I use `CreateSocketServer` it defaults to `TCP|UDP`.

**Comment by yaakov-h** [comment]
What's the use case for creating a server only available over TCP?

Typically the CM servers are available over both, or if not, Valve have no separation and expect the connection failure handling to take care of it.

**Comment by xPaw** [comment]
I monitor TCP servers (and now websocket) for steamstat.us: https://github.com/SteamDatabase/SteamMonitor/commit/136c13eb05a5125c6e6d67531d58387330aeb463

**Comment by yaakov-h** [comment]
`steamConfiguration.WithProtocolTypes(ProtocolTypes.Tcp | ProtocolTypes.WebSocket)`?

`SteamClient` only connects to the matching intersection of &lt;server available protocols&gt; and &lt;configuration-permitted protocols&gt;.

**Comment by xPaw** [comment]
Well I did `WithProtocolTypes(server.ProtocolTypes & ~ProtocolTypes.Udp)` which should accomplish the same task.

Still would be nice if `ServerRecord` could be modified to specify the protocol I want (especially if new protocols show up in the future).

**Comment by yaakov-h** [comment]
The design is that the `ServerRecord` reflects the server's potential protocols, and a client connection choice is controlled by `SteamConfiguration`.

If you really want to mess with this, then there is still the factory method `CreateServer(string host, int port, ProtocolTypes protocolTypes)` available to muck around with the `ProtocolTypes`.
