### ISSUE TITLE
Why is SteamID a class instead of a struct?

### ISSUE THREAD

**Issue by shravan2x** [SteamRE/SteamKit#559]
Just curious, is there a design reason behind this? The XML summary also reads `This 64-bit structure is used for identifying various objects on the Steam network.`, but it seems to be declared as a class.

**Comment by yaakov-h** [comment]
No idea, I do want to change it but haven't evaluated it yet.

**Comment by shravan2x** [comment]
@yaakov-h Thanks!

**Comment by yaakov-h** [comment]
Just to be clear, this was closed as not done, as there seems to be absolutely no benefit in converting them to structs. The JIT and GC are already doing a very good job of managing these objects and there seems to be no performance gains to be had in a typical SK2-based application, only in very specific unrealistic microbenchmarks

**Comment by shravan2x** [comment]
If that's the case, then the thanks was for looking into it :)

Is there a specific reason we decided not to pursue the change anyway?

**Comment by yaakov-h** [comment]
Lack of benefits. It’s complex to reengineer some of the classes, so if it doesn’t help, why bother?
