### ISSUE TITLE
Steam response are not being captured

### ISSUE THREAD

**Issue by vivekatdrive** [SteamRE/SteamKit#566]
Recently we got update from steam and suddenly steam response is not being captured,

if you check below image from Nethook2Analyzer, you will see there is no message in "in" direction

![6-14-2018 12-24-00 am](https://user-images.githubusercontent.com/25839593/41393597-2e189b82-6fc4-11e8-965d-be63c5c3e6ed.png)

**Comment by yaakov-h** [comment]
The method signature for `CCMInterface::RecvPkt` has changed in the latest client beta.

Our `steamclient-beta` branch has been updated accordingly.

You can download an updated version of the NetHook binaries from our CI [here](https://ci.appveyor.com/api/buildjobs/dcjr4rgqpf17p4ah/artifacts/NetHook2.zip).
