### ISSUE TITLE
Are "Max" values necessary in enums

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#571]
I noticed half of them don't even represent the max value because they were forgotten to be updated.

**Comment by yaakov-h** [comment]
I _believe_ `Max` is copied from Valve, who use it to loop through the enum, but never actually use `Max` as a value unto itself.

It's probably useless in a language with `Enum.GetValues(Type)` 😄

**Comment by yaakov-h** [comment]
@VoiDeD Do you want to keep them for any particular reason, or can we nuke them?

**Comment by VoiDeD** [comment]
I think they're fine to drop. The only scenario I could think they'd be useful is if we knew there was a gap between some enum values and `Max` - but I feel like that's unlikely.
