### ISSUE TITLE
Steam2 Universes

### ISSUE THREAD

**Issue by strafe** [SteamRE/SteamKit#574]
Couple of questions about the `SteamID` class.
1. Why must you supply an `EUniverse` when using the `SetFromString` method? I was under the impression the ID always contains the universe? xPaw's [PHP implementation](https://github.com/xPaw/SteamID.php/blob/master/SteamID.php#L119-L125) currently pulls the universe from the string.
1. Why does the `RenderSteam2` method automatically convert accounts that are in universe 1 to universe 0? This logic seems backwards as universe 0 is invalid and is only thought to be correct due to a bug(?). Again xPaw's [PHP implementation](https://github.com/xPaw/SteamID.php/blob/master/SteamID.php#L121-L125) corrects this the other way.

Thank you.

**Comment by bored** [comment]
> I believe (2) is for backwards compatibility, to match our old behaviour - and Steam's old behaviour, and Source's old behaviour...

I see, don't think you think it would make more sense to provide the _correct_ behaviour? Supposedly according to some posts (which I won't treat as gospel) any game that incorrectly used `0` instead of `1` now uses SteamID 3 internally instead and any games that didn't (such as CS:GO) still use it.

> I'm not sure about (1). I assume it was that way in the original C++ code that was ported, but I'd have to check.

I see, I'm not familiar with the history of SteamKit at all.
<hr>

Is the project open to changing behaviour with these things in at least some way (parameters to select behaviour) or are they too large?

**Comment by strafe** [comment]
> I believe (2) is for backwards compatibility, to match our old behaviour - and Steam's old behaviour, and Source's old behaviour...

I see, don't think you think it would make more sense to provide the _correct_ behaviour? Supposedly according to some posts (which I won't treat as gospel) any game that incorrectly used `0` instead of `1` now uses SteamID 3 internally instead and any games that didn't (such as CS:GO) still use it.

> I'm not sure about (1). I assume it was that way in the original C++ code that was ported, but I'd have to check.

I see, I'm not familiar with the history of SteamKit at all.
<hr>

Is the project open to changing behaviour with these things in at least some way (parameters to select behaviour) or are they too large?

**Comment by yaakov-h** [comment]
We tend to make breaking changes fairly regularly. 😢

**Comment by strafe** [comment]
> We tend to make breaking changes fairly regularly. cry

Ah good, not sure if this is just stalled now then. Maybe @xPaw or @asherkin could chime in.

**Comment by JustArchi** [comment]
I don't see why you can't deprecate existing function and code new one with one less argument.

**Comment by asherkin** [comment]
Gut tells me that parsing should take 0 or 1 as Public (and drop the override), and that rendering should default to emitting Public as 1 but allow overriding to 0 for only Steam2. It is a breaking change on rendering, but I doubt it'll actually break anyone's real code.

**Comment by yaakov-h** [comment]
I bet someone is using that as a DB key somewhere... but we did already break the default to render Steam3 instead of Steam2.

**Comment by yaakov-h** [comment]
Revisiting this.

We could just ignore it, or:

- Remove `EUniverse` from `SetFromString`, and infer it from the first digit.
- Drop the boolean parameter from `Render()`, only render Steam3.
- Replace `private RenderSteam2()` with `public RenderSteam2(SteamIDCompatibility)` where `SteamIDCompatibility` is either a bool, or an enum with two values along the lines of Pre2009 and Post2009.

Thoughts?

**Comment by strafe** [comment]
@yaakov-h I'm not qualified to comment on the best solution, however, it would be great if this was not ignored and SteamKit offered the objectively correct behaviour.

**Comment by xPaw** [comment]
I propose just closing this issue and leaving the behaviour as-is, you should not be using Steam2 ids.
