### ISSUE TITLE
Is there any way to connect to Dota2 game server?

### ISSUE THREAD

**Issue by sosenko1995** [SteamRE/SteamKit#575]
I am looking for a way to create a program to get real-time game data from live Dota2 games. In the official Dota2 client there are several ways of doing it. You can connect to a game server through DotaTV, you can join your friend's game or you can join a lobby as a spectator or a broadcaster before the game starts.

I think, all these ways use the same protocol to connect to a game server and to retrieve game data. Is there any workaround of doing this?

**Comment by yaakov-h** [comment]
I don't know if there is, but doing so is way out of SteamKit's scope.

**Comment by sosenko1995** [comment]
Thank you!
