### ISSUE TITLE
How does TF2 fetch a user's inventory?

### ISSUE THREAD

**Issue by shravan2x** [SteamRE/SteamKit#581]
This issue can be tagged as a `question`.

As the title suggests, how does TF2 initially fetch a user's inventory? I couldn't find any related messages using NetHook2. I found `CMsgRequestInventoryRefresh` in the SK2 source, but TF2 doesn't seem to send this message at startup. Yet its inventory is fetched correctly.

Does it do this outside the GC somehow?

**Comment by shravan2x** [comment]
I've figured it out. Closing issue.

**Comment by JustArchi** [comment]
Would be cool if you shared an answer so others possibly finding your issue could know too.

**Comment by shravan2x** [comment]
@JustArchi Good point. I'll post a write-up here when I find some time.

**Comment by ValvojaX** [comment]
> 
> 
> @JustArchi Good point. I'll post a write-up here when I find some time.

Can you tell me how?

**Comment by m4dEngi** [comment]
Initially you will receive player inventory after successfully connecting to GC with cache subscription packet.
Take a look at node-tf2 for a ~good example handler https://github.com/DoctorMcKay/node-tf2/blob/5615801b08652a3544202275ad5d7f3cbef69e1b/handlers.js#L135
