### ISSUE TITLE
Access Current Steam Client ?

### ISSUE THREAD

**Issue by PiotrKFtw** [SteamRE/SteamKit#590]
I mean access the steam client we are running on windows so that we could use this SteamKit2 for your main account. How can i do it ?

**Comment by JustArchi** [comment]
You can't, this is not what SK2 is for. You're most likely looking for something like Steamworks API.

**Comment by yaakov-h** [comment]
You can log in to SteamKit2 from the same account that is logged in to Steam, at the same time, however there is no direct interaction between SteamKit2 and the Steam Client, only the Steam backend network.

**Comment by PiotrKFtw** [comment]
How can i do it using Steamworks API then ?

**Comment by JustArchi** [comment]
Asking in appropriate place and not in the issues of entirely irrelevant project could be a good start.
