### ISSUE TITLE
Nethook2 fails to hook CCMInterface::RecvPkt

### ISSUE THREAD

**Issue by PowerGamer1** [SteamRE/SteamKit#591]
Latest release (non-beta) Steam client (package version 1535576546).
```
CCrypto::SymmetricEncryptChosenIV = 0x6ef6aaf0
pGetMessageList = 0x6eef9e20
pInfos = 0x6f3c77f0
numMessages = 466
Dumped emsg list! (466 messages)
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x6f004980
CCMInterface::RecvPkt = 0x0
Detoured CWebSocketConnection::BBuildAndAsyncSendFrame!
Unable to hook CCMInterface::RecvPkt: func scan failed.
```

**Comment by psychonic** [comment]
This is fixed now.

I'm not sure what our procedure is for updating NetHook on releases (since releases are for SteamKit), but if you are unable to compile on your own, precompile binary and pdb are here, https://users.alliedmods.net/~psychonic/nethook-591/
