### ISSUE TITLE
Dota 2 GC reponse (Player Info) stopped working after over half a year without issues

### ISSUE THREAD

**Issue by dm1989** [SteamRE/SteamKit#592]
In regards to Dota2 game coordinator,

Can anyone confirm if this has been changed? Player info call (CMsgGCPlayerInfoRequest) to GC does not receive a callback anymore (k_EMsgGCPlayerInfo).

I don't know if this request has been discontinued or what the case is. I have had no changes to my code for a very long time now and all of a sudden I stopped getting a response for this call (all other calls are working fine getting the expected responses).

**Comment by rossengeorgiev** [comment]
Its not a bug, Valve have removed it.

**Comment by rossengeorgiev** [comment]
FYI https://github.com/Arcana/node-dota2/issues/605#issuecomment-429531227
