### ISSUE TITLE
Sentry file (question)

### ISSUE THREAD

**Issue by hojjatjafary** [SteamRE/SteamKit#599]
Hi,

Why Steam stores the sentry file that seems it is a random data and send the sha1 hash of it every time trying to login?
Why does not store the hash itself? What are the security considerations of the file?

**Comment by yaakov-h** [comment]
The Steam servers can ask Steam to read back arbitrary parts of the file. I don’t think we’ve ever seen this happen in practice.

If you store just a hash, you could never do that.

**Comment by hojjatjafary** [comment]
Thank you,
But you have not seen that happened but how do you know that Steam server ask for it?

**Comment by yaakov-h** [comment]
There's code and network messages for it.

**Comment by hojjatjafary** [comment]
Ah!, thank you again...
I'm thinking about security perspectives, having a way to read the file will give hacker a way to get the file...
