### ISSUE TITLE
SteamKit2.SteamApps.PICSGetProductInfo started throwing exceptions recently

### ISSUE THREAD

**Issue by RudeySH** [SteamRE/SteamKit#609]
I have been running a script that calls `PICSGetProductInfo` for 70 thousand app IDs every 5 minutes for the past few months. I know this might sound insane, but it works.

Well, at least it did. Since 2 or 3 days, it started throwing `System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'`. Out of 70 thousand apps, only 20 thousand succeed on average.

I'm calling the function like this:

```
var appId = 927900; // random example app ID
var resultSet = await _steamApps.PICSGetProductInfo((uint)appId, null); // exception here
```

Any idea on how to avoid this exception? Did Steam introduce some kind of latency which is now causing SteamKit to run into timeouts?

**Comment by Marlamin** [comment]
> I have been running a script that calls PICSGetProductInfo for 70 thousand app IDs every 5 minutes for the past few months. I know this might sound insane, but it works.

Yeah, uh, maybe don't do that. :D

**Comment by yaakov-h** [comment]
Why do I have a sneaky feelin pg that you’re encountering thread pool exhaustion?

**Comment by JustArchi** [comment]
Task is also getting cancelled when Steam simply won't answer to your request in timely manner, and from my own experience I can say that this request is the one that doesn't have to finish in timely manner.

I don't know your upstream code (e.g. if you're asking for those apps all at once or one-by-one), but if by any chance it is possible that there are several requests for that happening at the same time, then @yaakov-h could be right, adding `SemaphoreSlim` with count of `10` or so could help narrow it down.

**Comment by RudeySH** [comment]
I was running them all at once. Not sure why it stopped working perfectly, but it was a bad idea anyway.

Running them sequentially works like a charm.
