### ISSUE TITLE
In Game Purchase

### ISSUE THREAD

**Issue by Outzzz** [SteamRE/SteamKit#617]
i want to implement in game purchase according https://dev.doctormckay.com/topic/769-clientmicrotxnauthrequest-5504/, but i can't find related type definition in steamkit,  ClientMicroTxnAuthRequest, ClientMicroTxnAuthorize, ClientMicroTxnAuthorizeResponse etc 
how should i do ?

**Comment by yaakov-h** [comment]
https://github.com/SteamRE/SteamKit/blob/730482b3323e2cf78d035e32977da93f603890b9/SteamKit2/SteamKit2/Base/Generated/SteamLanguage.cs#L1073 ?

**Comment by Outzzz** [comment]
> [SteamKit/SteamKit2/SteamKit2/Base/Generated/SteamLanguage.cs](https://github.com/SteamRE/SteamKit/blob/730482b3323e2cf78d035e32977da93f603890b9/SteamKit2/SteamKit2/Base/Generated/SteamLanguage.cs#L1073)
> 
> Line 1073 in [730482b](/SteamRE/SteamKit/commit/730482b3323e2cf78d035e32977da93f603890b9)
> 
>  ClientMicroTxnAuthorize = 5505, 
> ?

i mean protobuf class define.when i get ClientMicroTxnAuthRequest message, i can decode like that:
ClientMsgProtobuf\<ClientMicroTxnAuthRequest\> response = new ClientMsgProtobuf\<ClientMicroTxnAuthRequest\>(packetMsg);

**Comment by yaakov-h** [comment]
It seems like we don't have the message definition for these.

**Comment by wangxingzhen** [comment]
> > [SteamKit/SteamKit2/SteamKit2/Base/Generated/SteamLanguage.cs](https://github.com/SteamRE/SteamKit/blob/730482b3323e2cf78d035e32977da93f603890b9/SteamKit2/SteamKit2/Base/Generated/SteamLanguage.cs#L1073)
> > Line 1073 in [730482b](/SteamRE/SteamKit/commit/730482b3323e2cf78d035e32977da93f603890b9)
> > ClientMicroTxnAuthorize = 5505,
> > ?
> 
> i mean protobuf class define.when i get ClientMicroTxnAuthRequest message, i can decode like that: ClientMsgProtobuf<ClientMicroTxnAuthRequest> response = new ClientMsgProtobuf<ClientMicroTxnAuthRequest>(packetMsg);

Hi , Did you succeed in the end?  Can you tell me the steps? I want to do that too
