### ISSUE TITLE
Set an user-agent for all the web requests that SK2 performs

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#618]
It probably would be a good idea to set it to something like "SteamKit/x.x.x" instead of relying on whatever the runtime the user-agent to be (which would be different depending on version/type/etc).

Maybe it should be exposed in SteamConfiguration so consumers can set it too?

**Comment by yaakov-h** [comment]
We could set a default, but consumer configuration should be covered by #605.
