### ISSUE TITLE
Sample DotaMatchRequest doesn't work (stucks)

### ISSUE THREAD

**Issue by wa1one** [SteamRE/SteamKit#619]
When I'm running this Sample I got:

```
Connecting to Steam...
Connected! Logging 'wa1one1' into Steam...
Logged in! Launching DOTA...
GC is welcoming us. Version: 3309
Requesting details of match 27110133
```

With no Results! Program just hangs

**Comment by yaakov-h** [comment]
Closing as stale.

GC specifics are generally out of scope, but I would expect it to be fair that our own sample code works.

For what it's worth, the sample works for me as of right now.
