### ISSUE TITLE
Parameterized tests are not run, one fails

### ISSUE THREAD

**Issue by Longi94** [SteamRE/SteamKit#625]
`SteamIDFacts.ToChatIDOnlySupportsClans` and `SteamIDFacts.TryGetClanIDOnlySupportsClanChatRooms` are not run because the `[Theory]` attribute is missing (e.g. check the tests in this build: https://ci.appveyor.com/project/SteamRE/steamkit/builds/21449907/job/55f3rxj990xqqa71/tests).

`SteamIDFacts.TryGetClanIDOnlySupportsClanChatRooms` will fail when the parameter is `EAccountType.Chat`

**Comment by yaakov-h** [comment]
Good catch, thanks!
