### ISSUE TITLE
WebSocket server is not marked as "bad" in case of disconnection

### ISSUE THREAD

**Issue by Vital7** [SteamRE/SteamKit#626]
SteamKit tries to mark server as "bad" in method [Disconnected](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/CMClient.cs#L404), which is called by [DisconnectCore](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Networking/Steam3/WebSocketConnection.cs#L60).

The problem is that currentContext for the WebSocketConnection is null (it sets null in DisconnectCore), so CurrentEndPoint is null (because it equals to currentContext?.EndPoint), and the TryMark fails.
Solution is to rewrite DisconnectCore, so it calls Disconnected at first, and only then sets currentContext to null:
```
void DisconnectCore(bool userInitiated, WebSocketContext specificContext)
        {
            if (currentContext != null && (specificContext == null || currentContext == specificContext))
            {
                currentContext.Dispose();

                Disconnected?.Invoke(this, new DisconnectedEventArgs(userInitiated));
            }
            else
            {
                specificContext?.Dispose();
            }

            currentContext = null;
        }
```

**Comment by yaakov-h** [comment]
Doing that removes some safety around concurrency.

Ideally users wouldn't call `Connect()` unless in a known-disconnected state, but it's something we've supported for a very long time and so they do.

In a better-designed world the `EndPoint` would be made available on `DisconnectedCallback` but that's a much larger refactor than I have the patience for.
