### ISSUE TITLE
Is it possible to get a list of game servers for given AppId?

### ISSUE THREAD

**Issue by MagicTrevor** [SteamRE/SteamKit#631]
I am looking to query for a list of game servers for a given `AppId` and then query the servers in that list for players, etc. Is that possible currently? I have been trying to use the `SteamMasterServer.QueryServer` but only get 1 result.

There is a `ISteamMatchmakingServer` interface with `RequestInternetServerList` method but does not appear to be in Steamkit.

Any help and direction would be appreciated!

**Comment by Bizarrus** [comment]
Not each (third party) game has implemented the complete SteamAPI. Which game do you want to fetch?

**Comment by yaakov-h** [comment]
Closing as stale.
