### ISSUE TITLE
Dynamic HardwareId for multiple threads

### ISSUE THREAD

**Issue by killemth** [SteamRE/SteamKit#638]
Reference #394 is there a way to change the `MachineId` from the `HarwareUtils` class by using the regularly distributed package from NuGet, without having to clone and create a separate build?

The use case is running multiple threads on the same machine for a DOTA 2 bot that is incurring `ERes` errors of `RateLimitExceeded` preventing logon and normal communication with the `GC`.

Furthermore, if it isn't possible -- can you confirm that all that would be needed is changing randomized strings in the three main `MachineId` components at https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Util/HardwareUtils.cs#L291-L293

**Comment by VoiDeD** [comment]
The rate limits presumably exist for a reason - to stop abusive clients. You likely won't get much support here for bypassing this.

If you have a legitimate purpose for the data you're trying to get from the Steam servers, perhaps you might have better luck by approaching Valve directly and proposing your business case.
