### ISSUE TITLE
How i can get gc dota2 all comands

### ISSUE THREAD

**Issue by maratkh** [SteamRE/SteamKit#642]
Hi! How i can get a gc command, for create custim lobby game. I have gc cliend, but i cant make custom game lobby normally, after creating i cant start a game. 

Thnx a lot!

**Comment by yaakov-h** [comment]
The particulars of any specific Game Coordinator are out of scope of SteamKit.

You can use NetHook to see what a particular game does and try to replicate it, but that's as far as we support.
