### ISSUE TITLE
NetHook2 dont works with counterstrike globaloffensive

### ISSUE THREAD

**Issue by ImAWeebDX** [SteamRE/SteamKit#644]
I tried to dump the GameCoordinator messages from cs go using Nethook2 
after executing `rundll32 .\NetHook2.dll,Inject csgo.exe`

i get these console outputs
`CCrypto::SymmetricEncryptChosenIV = 0x5e3a3690
pGetMessageList = 0x5e310f30
pInfos = 0x5e858ef0
numMessages = 463
Dumped emsg list! (463 messages)
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x5e4200c0
CCMInterface::RecvPkt = 0x5de86cd0
Detoured CWebSocketConnection::BBuildAndAsyncSendFrame!
Detoured CCMInterface::RecvPkt!`

after this nothing gets dumped the created folder is also empty

i used the NetHook2 build from the Release page and from AppVeyor both have the same result

**Comment by yaakov-h** [comment]
Are you injecting into Steam's process, or into CS:GO's process?

**Comment by ImAWeebDX** [comment]
>`rundll32 .\NetHook2.dll,Inject csgo.exe`
I injected it into csgo.exe that was the mistake injecting into steam works as expected
