### ISSUE TITLE
is it possible to send message in dota 2 in game? or get some cooldown skill?

### ISSUE THREAD

**Issue by lintangtimur** [SteamRE/SteamKit#645]
is it possible to send message in dota 2 in game?
or why other net library can get all of information from dota2 game?(Ensage) like cd, skills, etc

**Comment by VoiDeD** [comment]
Interactions between dota clients and dota dedicated servers are out of scope for SteamKit. SK is just a library for interacting with the backend Steam servers that manage dota games/lobbies/matchmaking/etc.
