### ISSUE TITLE
How to send MSG to GroupChat(ClanChat)

### ISSUE THREAD

**Issue by Linnni** [SteamRE/SteamKit#646]
For example i have group id 103582791429521592 , how can i do send message in chat this group?

**Comment by VoiDeD** [comment]
The `SteamFriends` handler has a `SendChatRoomMessage` method that'll allow you to do that.

**Comment by JustArchi** [comment]
@VoiDeD If he's still living in the past and means old group chat, because it doesn't apply to the new one which the OP probably refers to.

See https://github.com/SteamRE/SteamKit/issues/561

**Comment by VoiDeD** [comment]
Oops, yeah - I totally forgot that entire system got reworked.

**Comment by JustArchi** [comment]
If you want some helpful resources before SK2 delivers user-friendly methods, you can check how I achieved it in **[ASF](https://github.com/JustArchiNET/ArchiSteamFarm/blob/19891c3/ArchiSteamFarm/Bot.cs#L1229)**, `Bot.cs` and `ArchiHandler.cs` should be helpful.

**Comment by Linnni** [comment]
> If you want some helpful resources before SK2 delivers user-friendly methods, you can check how I achieved it in **[ASF](https://github.com/JustArchiNET/ArchiSteamFarm/blob/19891c3f59004dd180f66190f6ae43c514b3925b/ArchiSteamFarm/ArchiHandler.cs#L542)**, `Bot.cs` and `ArchiHandler.cs` should be useful.

Bro, i see this method "SendMessage(ulong chatGroupID, ulong chatID, string message)" , how can i get this param chatGroupID and chatID from chat group?

**Comment by JustArchi** [comment]
https://github.com/JustArchiNET/ArchiSteamFarm/blob/1b0cb4136679ab781b7edd652ea6d555f4588311/ArchiSteamFarm/Bot.cs#L2128

Next time dig deeper 😉.

**Comment by yaakov-h** [comment]
Closing as kinda-of-answered-I-guess?

Not something we can address in SK2 itself until #561 is done.
