### ISSUE TITLE
CMsgRequestLeagueInfo not working?

### ISSUE THREAD

**Issue by windhelm** [SteamRE/SteamKit#647]
```
var requestLeague = new ClientGCMsgProtobuf<CMsgRequestLeagueInfo((uint)EDOTAGCMsg.k_EMsgRequestLeagueInfo);
gameCoordinator.Send(requestLeague, APPID);
```
GC not not answer,(

**Comment by yaakov-h** [comment]
GC specifics are out of scope for SteamKit. We provide a channel to the GC, but as to what each individual GC does with messages is not really our concern.

I've left it open in case somebody does know the answer, but apparently they don't.

Closing now as out of scope.
