### ISSUE TITLE
CDNClient no longer throws exceptions

### ISSUE THREAD

**Issue by azuisleet** [SteamRE/SteamKit#650]
Beyond HttpRequestException for network exceptions, WebException isn't being thrown. Instead, the status code is available in HttpResponseMessage. The status code is currently being lost.

**Comment by yaakov-h** [comment]
For WebAPI we preserve it on `WebAPIRequestException`. Do we need a similar exception for CDN, or to generalise this exception type for both?

**Comment by xPaw** [comment]
Technically there's no exception for wrong status code, but it throws down the line when the compressed length mismatches (which was a recent change I added).

👍  For re-using `WebAPIRequestException`.
