### ISSUE TITLE
OnAccountInfo callback print 2 times

### ISSUE THREAD

**Issue by sp0ok3r** [SteamRE/SteamKit#659]
```
        static void OnAccountInfo(SteamUser.AccountInfoCallback callback)
        {
            Console.WriteLine("test OnAccountInfo");
        }
```

![wat](https://user-images.githubusercontent.com/7952298/55840737-6ac8b700-5b24-11e9-9663-d9a1b1dcd57b.png)

Hello, only happening on this callback, it's supposed to do this?

**Comment by yaakov-h** [comment]
Possibly. Did you subscribe to the callback twice?

If not, use `DebugLog` to see if SteamKit is actually receiving two separate account info messages.

**Comment by sp0ok3r** [comment]
No, only one time. debuglog: 
![wot](https://user-images.githubusercontent.com/7952298/55878740-eb270080-5b94-11e9-90b8-36edf103063f.png)

**Comment by oxters168** [comment]
Apparently I receive account info twice as well. 
![AccountInfo](https://user-images.githubusercontent.com/15348986/56475476-65a72880-6491-11e9-96b6-ec17a0ddc6bb.png)
If I hadn't checked I wouldn't have noticed, it seems to be normal.

**Comment by yaakov-h** [comment]
It seems that the Steam servers are actually sending the account info message twice.

With DebugLog enabled I get the following output:

```
[CMClient] <- Recv'd EMsg: ClientAccountInfo (768) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientAccountInfo (768) (Proto: True)
```

Looking at [your own screenshot](https://github.com/SteamRE/SteamKit/issues/659#issuecomment-481670780) I can see the duplicate message there as well.

**Comment by JustArchi** [comment]
This is pretty normal. I recommend to use `SemaphoreSlim` for people that require this function to be called just once.
