### ISSUE TITLE
I can connect 1000 accounts?

### ISSUE THREAD

**Issue by Linnni** [SteamRE/SteamKit#661]
Hey! Can I connect 1000 accounts in 1 time to manage everything at once? For example, from all at once send a message. Is there a risk to get VAC BAN?

**Comment by sp0ok3r** [comment]
Hey! have a read: [Avoid VOC](https://support.steampowered.com/kb_article.php?ref=7849-Radz-6869#avoidvac) , and yes i think you can connect all 1000acc with some delay and to do not illegal stuff (*eyes looking left side*)

**Comment by Linnni** [comment]
> Hey! have a read: [Avoid VOC](https://support.steampowered.com/kb_article.php?ref=7849-Radz-6869#avoidvac) , and yes i think you can connect all 1000acc with some delay and to do not illegal stuff (_eyes looking left side_)

only legal things bro

**Comment by yaakov-h** [comment]
There's nothing we do to limit concurrent connections, but it's not up to us anyway.

This totally depends on yours and Valve's network infrastructure and security policies, and they can change it at any time.
