### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GitHubSt13** [SteamRE/SteamKit#664]
Im using Titan reportbot project 
https://hostingkartinok.com/show-image.php?id=6f197768737cc419df8af1971dae5914
But when I use many accounts I have memory overflow because of your library.
Cleaner in c# just dont kill objects in your library, even if I won't use this account more

**Comment by yaakov-h** [comment]
What objects are being retained beyond their expected lifecycle and where are they being created?

Your screenshot only shows a detached dotMemory profiler and allocations in expected locations, but not a snapshot differential.

**Comment by GitHubSt13** [comment]
Im noob in debug so if u need some debug info give me instructions.
The problem is:
https://github.com/Marc3842h/Titan/blob/master/Titan/Account/Impl/UnprotectedAccount.cs
After finished seding report via this thread(class) I fully remove it Dispose();
But there are a lot of data in your library that cannot be removed by GC

**Comment by JustArchi** [comment]
If you're claiming SK2 leak then precise the exact portion of the **library** that is suspected to your leak and example case that reproduces it with the library alone.

SK2 devs are not interested in Titan's codebase and whether it implements SK2 objects correctly or not.

**Comment by yaakov-h** [comment]
FWIW I actually did some memory testing on SteamKit2 a while ago and the codebase hasn't changed much since.

If you claim there's a leak, we'll need some sort of proof in order to fix it.

Using our own sample code would be best, otherwise a small project with no additional dependencies and a big "click here for leak" button, or a dotMemory trace would also suffice.

**Comment by GitHubSt13** [comment]
Maybe I don't understand something. Where can I find how to stop session and clear all data for account, after using SteamKit2

**Comment by yaakov-h** [comment]
If you disconnect a `SteamClient` and drop all references to related objects, the GC should collect the lot.

**Comment by GitHubSt13** [comment]
private SteamClient _steamClient;
***
   if (_steamClient.IsConnected)
                {
                    _steamClient.Disconnect();
                }
I do this before Dispose() account's class, but it doesnt work. Memory is still allocated even after account's class removed by GC

**Comment by yaakov-h** [comment]
Please post a dotMemory trace or snapshot, or provide a full working sample.

**Comment by yaakov-h** [comment]
Closing as there is nothing we can act on here.

If you can get a proper profiler trace or a small reproducible project, feel free to re-open.
