### ISSUE TITLE
Why i dont get GetFriendPersonaState? All show me Offline

### ISSUE THREAD

**Issue by Linnni** [SteamRE/SteamKit#667]
i use this methods 
`foreach (var friend in callback.FriendList)
{
                    Console.WriteLine("____________________________");
                    Console.WriteLine(steamFriends.GetFriendPersonaState(friend.SteamID));
                    Console.WriteLine(friend.SteamID.ConvertToUInt64());
                    Console.WriteLine("____________________________");
}
`
And writes to me that all my friends though it is not

**Comment by yaakov-h** [comment]
`FriendListCallback` is only fired when we know who your friends are. At that time, Steam has not yet sent persona information for each of those friends.

If you listen for a `PersonaStateCallback`, you'll then stay informed as Steam sends the info for those friends.
