### ISSUE TITLE
ProtobufDumper doesn't properly implement message backed options.

### ISSUE THREAD

**Issue by justMaku** [SteamRE/SteamKit#670]
Right now ProtobufDumper is coded to handle default values for options with a [custom type as strings](https://github.com/SteamRE/SteamKit/blob/master/Resources/ProtobufDumper/ProtobufDumper/ImageFile.cs#L464) which produces proto files that can not be parsed by `protoc`.

I'm not sure how this should be handled as parsing that data would require a concrete type to exist to throw at `Serializer.Deserialize()` to read the contents of the message, so for now I would just suggest dropping the default value so the resulting proto files are at least valid.

**Example**:

Source Protobuf:

```
extend .google.protobuf.MessageOptions {
	optional .CustomOption MyOption = 69;
}

message CustomOption {
	optional bool use_x = 1;
        optional bool use_y = 2;
}

message SomeMessage {
	option (MyOption) = {
                use_x: true,
                use_y: false
        };
	optional uint32 error_code = 1;
	optional bool result = 2;
}
```

Current output:
```
extend .google.protobuf.MessageOptions {
	optional .MyCustomOption CustomOption = 77000;
}

message MyCustomOption {
	optional bool use_x = 1;
        optional bool use_y = 2;
}

message SomeMessage {
	option (CustomOption) = "random binary garbage"
	optional uint32 error_code = 1;
	optional bool result = 2;
}
```

**Comment by azuisleet** [comment]
Yes, this is a known issue. It only reflects basic types on options. I want to eventually revisit protobuf-net for an easier way to handle this.

**Comment by azuisleet** [comment]
This should be resolved in #671. Give this another shot.

**Comment by yaakov-h** [comment]
Closing since there are no further complaints in three weeks after "should be" resolving.

**Comment by justMaku** [comment]
Yeah, sorry for that! It's working well now.
