### ISSUE TITLE
How to relogin to account without Steam Guard?

### ISSUE THREAD

**Issue by dmitriev02** [SteamRE/SteamKit#673]
I want to store Steam accounts and after restarting the server they must automatically login with out steam guard code.
I tried auth using loginKey - but on some accounts that works, on some - no.
I tried auth using webLogonToken - but it expires and I don't know actual expiration time.

**Comment by JustArchi** [comment]
To the best of my knowledge the only solution to this is to achieve exactly what I did in ASF and provide generated 2FA token on each login attempt.

**Comment by dmitriev02** [comment]
@JustArchi, you mean shared_secret?

**Comment by JustArchi** [comment]
Yes.

**Comment by dmitriev02** [comment]
@JustArchi, I have no access to shared_secret at this accs. I can get only 1 time guard code, login and pass
Do you have any suggestions?

**Comment by JustArchi** [comment]
No, because nothing stops you from enabling 2FA and achieving the above. Any other method, even fetching SteamGuard code from e-mail and retrying with it, is prone to third-party failures.

**Comment by oxters168** [comment]
I don't know much about what is needed for auto login, but what about the sentry file? I don't know what exactly it does, but maybe it could help if you provide it when logging back in automatically?

**Comment by solomax2014** [comment]
@dmitriev02, did you try using LoginKey? If you select to "Remember password", then Steam should send you loginKey so on next auth you can use it instead of a password. + that sentry_hash thing

**Comment by JustArchi** [comment]
Key word is **should**, it doesn't work correctly from time to time. See **[ASF's FAQ entry](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/FAQ#why-do-i-have-to-put-2fasteamguard-code-on-each-login--removed-expired-login-key)**.

**Comment by yaakov-h** [comment]
Closing as answered.
