### ISSUE TITLE
CDNClient methods that accept `string host` download via http

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#677]
`DownloadManifestAsync` and `DownloadDepotChunkAsync` automatically turn the passed host string into a `Server` object with `HTTP` as the protocol. As a consumer I can't control this behaviour (the core method is private and I can't pass my own Server object in)

**Comment by yaakov-h** [comment]
It seems that this is technically possible with:

`ConnectAsync` -> `AuthenticateDepotAsync` -> `DownloadManifestAsync`/`DownloadDepotChunkAsync`.

With a smarter consumer doing their own management, we should have a way to streamline this process.

**Comment by xPaw** [comment]
I think the easy way of fixing it would be making `DownloadDepotChunkCoreAsync` a public overload of `DownloadDepotChunkAsync`

same with `DownloadManifestAsync`
