### ISSUE TITLE
Is old-school content server handling still needed in CDNClient?

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#679]
Maybe I'm wrong, but I believe all servers now use (or at least support) CDN style authentication.

And if that fact is correct, all of the relevant CS code could be ripped out and simplified.

**Comment by xPaw** [comment]
GetServersForSteamPipe webapi does not include `CS` servers, while hitting `/serverlist`/ on a random server does return them.

https://api.steampowered.com/IContentServerDirectoryService/GetServersForSteamPipe/v1/?format=vdf&cell_id=0&max_servers=10000
https://cache8-atl1.steamcontent.com/serverlist/0/1000/

But even then, these CS servers have `usetokenauth` set to 1 anyway.

**Comment by xPaw** [comment]
I was looking at removing CS code, and CDNClient public API starts making little sense. For example `ConnectAsync` becomes useless as it will simply set the `connectedServer` property which is not thread safe.

**Comment by xPaw** [comment]
I just looked at steamclient, and I can't find any references to `authdepot` or `initsession`.

**Comment by azuisleet** [comment]
We should probably

- Remove any CS paths that remain
- Investigate if all methods can be static with no state needed
- Investigate if SteamConfiguration can be passed through for the HTTP client builder)
- Made CDNClient.Server publicly constructable

**Comment by xPaw** [comment]
I looked at cleaning up CDNClient before, and http client reference prevents it from being fully static.

**Comment by yaakov-h** [comment]
Note: Handled by https://github.com/SteamRE/SteamKit/pull/725
