### ISSUE TITLE
Use GetServersForSteamPipe webapi instead of hitting a random CS server

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#680]
https://steamapi.xpaw.me/#IContentServerDirectoryService

Used in `CDNClient.FetchServerListAsync`. The webapi returns the same data as hitting any of the random CS server does. This way the WebAPI stuff can be re-used.

**Comment by azuisleet** [comment]
Resolved via https://github.com/SteamRE/SteamKit/pull/699
