### ISSUE TITLE
😢 Unable to make AuthUser Api Request?? (beta3)

### ISSUE THREAD

**Issue by sp0ok3r** [SteamRE/SteamKit#688]
Hello, so I updated to beta3, and was trying:

```
Dictionary<string, object> newsArgs = new Dictionary<string, object>()
                    {
                        { "steamid", client.SteamID.ConvertToUInt64() },
                        { "sessionkey", cryptedSessionKey },
                        { "encrypted_loginkey", cryptedLoginKey }
                    };
authResult = userAuth.AuthenticateUser(HttpMethod.Post, "AuthenticateUser", newsArgs);
```

log: "Unable to make AuthenticateUser API Request: Argument mismatch in API call. All parameters must be passed as named arguments, or as a single un-named dictionary argument."

Any opinions?

**Comment by JustArchi** [comment]
```
authResult = userAuth.AuthenticateUser(HttpMethod.Post, "AuthenticateUser", newsArgs);
```

Either use `Call()` on static interface, or use dynamic one where you specify method and everything else in the arguments.

**Comment by sp0ok3r** [comment]
solved, thanks Lord Archi!

**Comment by xPaw** [comment]
Side note: Don't put emojis in titles, it's dumb.

**Comment by sp0ok3r** [comment]
sorry Lord xPaw
