### ISSUE TITLE
Better server selection logic

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#69]
Right now, CMClient just selects a random server to connect to. But it could be improved and act in a way Steam client does. Whenever the client gets disconnected/logged out, Steam marks current cm as bad, and doesn't use it in future reconnections (until flushed).

/cc @Netshroud

**Comment by Netshroud** [comment]
We now have smarter server selection which reduces the chance of reconnecting to a known bad CM, and increases the chance of connecting to a known good CM. :smile:
