### ISSUE TITLE
SteamConfiguration.CellID is not used in login

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#690]
`SteamUser.LogOn` and `LogOnAnonymous` accept details object which can have a cellid set, I think it would be a good idea to set it by default to `SteamConfiguration.CellID` if it's not provided in `LogOnDetails`.

**Comment by azuisleet** [comment]
Resolved via https://github.com/SteamRE/SteamKit/pull/699

**Comment by ADustyOldMuffin** [comment]
I'd be interested in working on this if it's open.
