### ISSUE TITLE
Endless disconnections, don't know why.

### ISSUE THREAD

**Issue by cyberangel67** [SteamRE/SteamKit#693]
While trying the SteamGuard sample app, I found myself in a position where I was getting constantly disconnected. As the only message on the screen was being disconnected, the callback result has no information about why it was disconnected.

Therefore I end up in an endless loop, without knowing why.

<img width="669" alt="Capture" src="https://user-images.githubusercontent.com/1366816/59727212-1ce4d380-9278-11e9-8058-2b34692273a1.PNG">

**Comment by VoiDeD** [comment]
There's no definitive answer here, but you might be running into Steam's connection/logon rate limiting. If you attempt to connect or logon too quickly, the Steam servers will rate limit your client by disconnecting it after a logon attempt.

I would try waiting maybe 10-15 minutes and then try connecting again.

**Comment by MsBehaving** [comment]
I too have seen this and it is not because of too many connections, but the issue of not actually knowing is a problem. It would be good if the callback result had why, so appropriate action could be taken.
