### ISSUE TITLE
Nethook2 support for 64bits games

### ISSUE THREAD

**Issue by Henroks** [SteamRE/SteamKit#696]
Hi, I`m trying to watch the protobuffs exchanged with the GC with the new valve game (underlords) but its only released in 64bits and uses steamclient64.dll instead of steamclient.dll, of course. Is there a tool for this already?

**Comment by yaakov-h** [comment]
SteamWorks uses IPC to send messages through the Steam client, which is still 32-bit, rather than through the host game, which can be anything.

Is Underlords doing something special?

**Comment by xPaw** [comment]
Latest nethook works fine with Underlords, minus the missing protobufs.

**Comment by Henroks** [comment]
@xPaw I keep getting "steamclient.dll" not found, and when I change in the code to steamclient64 it doesnt work, probably the pattern/mask is different (I dont know, Just speculating).

@yaakov-h I dont think so, I was not able to use nethook, but i was able to dump the proto/dump files from client.dll and server.dll

**Comment by psychonic** [comment]
Nethook injected into the Steam client works for me as well to catch messages from Underlords, as expected.

The issue is still relevant for processes running without Steam installed though (such as a 64-bit dedicated server process using the steamclient64 from the SteamWorks Redistributable rather than a local Steam client install).

**Comment by Henroks** [comment]
I compiled again with the latest commit, this time I was able to read messages, but I couldnt detect anything different when creating a new group/inviting friends, am I missing something?

![image](https://user-images.githubusercontent.com/52092050/59981864-3bccc800-95e0-11e9-91c1-ee768b4c1920.png)

**Comment by psychonic** [comment]
It’s the ClientToGC and ClientFromGC messages. You can use NetHookAnalyzer2 to view the contents.

**Comment by Henroks** [comment]
Oh, awesome, thanks. First time using it, awesome tool.
