### ISSUE TITLE
NetHook broken on beta client

### ISSUE THREAD

**Issue by rossengeorgiev** [SteamRE/SteamKit#700]
Output:
```
CCrypto::SymmetricEncryptChosenIV = 0x38064f50
pGetMessageList = 0x37fccf70
pInfos = 0x385480f0
numMessages = 468
```
Cannot be ejected.

**Comment by byterussian** [comment]
Same error in production after last day steam update, latest release of NetHook is now broken.

**Comment by psychonic** [comment]
> Same error in production after last day steam update, latest release of NetHook is now broken.

With the commit referenced above, it works fine for me both on the stable client and the latest beta.

**Comment by byterussian** [comment]
Would love to try but wasnt't able to compile. Was hoping for a new binary release.

**Comment by rossengeorgiev** [comment]
@byterussian https://ci.appveyor.com/project/SteamRE/steamkit -> click on any build -> release -> artifacts
