### ISSUE TITLE
ClientServiceCall

### ISSUE THREAD

**Issue by SeRi0uS007** [SteamRE/SteamKit#710]
I want to make program to farm TF2 items, similiar to SteamItemDropIdler ([SIDI](https://github.com/kokole/SteamItemDropIdler)). SIDI itself doesn't work with TF2.
I send all requests that i can see in the NetHook except one `ClientServiceCallResponse`. I have found same issue #230, wich says at is encrypted VAC message.
Are there any way to decrypt or bypass it?

Also i've noticed that `GCClientWelcome` doesn't drop TF2 Supply Crates as earlier. More likely it requires operations with `ClientServiceCall` methods.

**Comment by yaakov-h** [comment]
It wouldn't surprise me if they hooked the items system into VAC to prevent exactly what you're trying to achieve.
