### ISSUE TITLE
@All in chat group

### ISSUE THREAD

**Issue by Linnni** [SteamRE/SteamKit#713]
When sending message to chat groups, commands with '@' do not work
![bandicam 2019-08-18 16-09-52-967](https://user-images.githubusercontent.com/38401362/63223655-b544f900-c1d2-11e9-8d2a-111762455260.jpg)

**Comment by VoiDeD** [comment]
There's likely some special token that the Steam client sends for highlighting users/groups. You'll want to investigate with NetHook.

**Comment by yaakov-h** [comment]
This seems like part of #561?

**Comment by m4dEngi** [comment]
`[mention=all]@all[/mention] `

**Comment by Linnni** [comment]
> This seems like part of #561?

Yes, i use code from there
