### ISSUE TITLE
Ignore/Block incoming friend invites

### ISSUE THREAD

**Issue by 1461748123** [SteamRE/SteamKit#716]
Currently steamFriends.IgnoreFriend(); behaves as blocking instead of proper ignoring. It blocks all user's communication instead of just ignoring the friend invite.

I can't seemed to find a way to ignore a friend invite instead of just straight out blocking them, or maybe I'm just missing something?

Thanks!

**Comment by rossengeorgiev** [comment]
You need to use `removeFriend()`

**Comment by 1461748123** [comment]
> You need to use `removeFriend()`

Thanks! I will try it out!

**Comment by JustArchi** [comment]
To further clarrify, on `SteamFriends.FriendsListCallback` find pending friend invites (`callback.FriendList.Where(friend => friend.Relationship == EFriendRelationship.RequestRecipient)`) and  `SteamFriends.RemoveFriend()` on those you wish to ignore.
