### ISSUE TITLE
X-eresult header

### ISSUE THREAD

**Issue by Outzzz** [SteamRE/SteamKit#733]
service.callasync only return KV object.
but IEconService/CancelTradeOffer endpoint return {"response":{}} and X-eresult header.
how can i get response header?

**Comment by JustArchi** [comment]
@yaakov-h it'd probably be a good idea to somehow expose response headers if possible, not sure how breaking change that would be though, the most api-friendly would be adding them to the `KeyValue` class, but it's awful.

**Comment by yaakov-h** [comment]
tbh I'd rather kill the whole thing and just expose a `public static Task<KeyValue> ReadAsKeyValueAsync(this HttpContent content)` method, leaving the http calls itself to the consumer.

**Comment by yaakov-h** [comment]
Headers were exposed by #603.

**Comment by Outzzz** [comment]
```
POST https://api.steampowered.com/IEconService/CancelTradeOffer/v1/? HTTP/1.1
Host: api.steampowered.com
Origin: null
Content-Type: application/x-www-form-urlencoded
Content-Length: 60

key=******A1A3EF8D758A529768160****&tradeofferid=3846775991

HTTP/1.1 200 OK
X-eresult: 42
Content-Type: application/json; charset=UTF-8
Content-Length: 15
Expires: Tue, 14 Jul 2020 13:02:16 GMT
Date: Tue, 14 Jul 2020 13:02:16 GMT
Connection: keep-alive

{"response":{}}
