### ISSUE TITLE
Use the new ip fields in the logon message (IPv6 support)

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#758]
Now that protogen has been updated, new protos are included.

Valve have been adding ipv6 support in the steam client, so there's new proto fields for it.

`CMsgClientLogon` added `.CMsgIPAddress obfuscated_private_ip` and `.CMsgIPAddress public_ip` fields. Same with `CMsgClientLogonResponse`.

CMsgIPAddress is this:
```
message CMsgIPAddress {
	oneof ip {
		fixed32 v4 = 1;
		bytes v6 = 2;
	}
}
```

See https://github.com/SteamDatabase/Protobufs/commit/a4ba0a9e35a204b8185ca32a8aec697c830cadb2#diff-ae4e2a3dc1bbf60e70ebca0ab4507c8a

See https://github.com/SteamDatabase/Protobufs/search?q=CMsgIPAddress&unscoped_q=CMsgIPAddress for all the messages that use v4/v6 oneof.

**Comment by xPaw** [comment]
See https://github.com/SteamRE/SteamKit/pull/759/commits/7ab4e1a64c1ac573363bf015d8a96b5fdbe6a593 for what code actually needs to be updated in SK2.

**Comment by yaakov-h** [comment]
Should we do something about LoginID, and if so, what?

**Comment by xPaw** [comment]
> Should we do something about LoginID, and if so, what?

Not sure I understand, what's up with LoginID?

**Comment by yaakov-h** [comment]
https://github.com/SteamRE/SteamKit/blob/d7b13702319b1dcd0997772551de6028030c83e3/SteamKit2/SteamKit2/Steam/Handlers/SteamUser/SteamUser.cs#L40-L50

It allows the user to override the "obfustucated" IPv4 address.

**Comment by JustArchi** [comment]
The best way to determine if there is any action needed is to try to connect 2 SteamClients from the same machine (best if the same process).

If you don't get LogonSessionReplaced or something like that during connect of second account, it's no longer needed.

If you do, and setting LoginID of the second session to some arbitrary number resolves the issue, it's still needed.

**Comment by xPaw** [comment]
That's done now.
