### ISSUE TITLE
How to mark a message as read?

### ISSUE THREAD

**Issue by TheCubicNoobik** [SteamRE/SteamKit#772]

**Comment by TheCubicNoobik** [comment]
Found it.

https://github.com/SteamRE/SteamKit/blob/c256b70eb6832147a34e3084e764c22dcca76452/SteamKit2/SteamKit2/Steam/Handlers/SteamFriends/SteamFriends.cs#L710

**Comment by JustArchi** [comment]
This is part of legacy API and will not work with e.g. new group chats. Not to mention that it can stop working anytime as new Steam client is no longer using those.

**[AckMessage](https://github.com/SteamRE/SteamKit/issues/561#issuecomment-549092906)** works with new API.
