### ISSUE TITLE
WebAPI logs an AggregateException, rather than the actual exception

### ISSUE THREAD

**Issue by yaakov-h** [SteamRE/SteamKit#784]
https://github.com/SteamRE/SteamKit/blob/2.2.0/SteamKit2/SteamKit2/Steam/WebAPI/WebAPI.cs#L217-L225

Re-evalute the whole use of this continuation.

**Comment by xPaw** [comment]
Is there any point in this debug log? I would just remove that function and rename `CallAsyncCore` to `CallAsync`.

**Comment by yaakov-h** [comment]
> (such as when waiting for the task times out, and an exception is thrown later)
This should no longer be neccesary with the new timeout APIs on HttpClient. It seems like a holdover from the HttpWebRequest/WebClient days.
