### ISSUE TITLE
Using GameCoordinator With Shared Account

### ISSUE THREAD

**Issue by oxters168** [SteamRE/SteamKit#785]
So I'm working on an application that lets you view your csgo replays. I'm trying to make it so that users don't need to log in to see their previous matches. I know how to do that, and I get a sharecode for each match. I then turn the sharecodes to their matchid, outcomeid, and token. The next step is to use a GC message to get the match info (I need the match info to get the download link of the match). The problem is that that would require an account that owns csgo. I tried doing it through the anonymous account sending GC messages to both csgo (730) and it's dedicated server (740), but they didn't work. I think my solution would be to create a Steam account that owns csgo for the application to use to communicate with the GC. What I think will happen though is that since multiple people would be using the same account at once, Steam will only allow one to send messages to the GC at a time, so I'm afraid it'll be slow. Is this true, and if so, is there some other solution I'm not thinking of here? Sorry for the wall of text, I've been trying to figure this out for the last two days. Thanks for any help.

**Comment by JustArchi** [comment]
You don't want to share details of that account, you could accidentally manage to create links of multiple people to that account which could result even in steam suspensions of unrelated accounts, for example if somebody does something bad.

If there is no better way (I don't know enough about CS:GO GC so wait for somebody else in regards to that), I'd create the app as you initially wanted, then put it behind your own controlled API such as `mydomain.com/Api/GetMatchInfo` and use it in your consumer application.

Obviously if you intend for it to be good then you'll need to add some rate limits and what else, but at least if anything goes wrong then innocent people won't wake up with a need of contacting Steam support.

**Comment by oxters168** [comment]
That's a good point, I definitely don't want to get anyone's Steam account suspended. Just to make sure I understand though, you mean that since people would be logging in to this account from their home networks, the other accounts they log in with in the same network might be identified with this one? I really hope that putting it behind a domain would not be the only solution, I don't want to have to maintain a domain.

**Comment by JustArchi** [comment]
> I understand though, you mean that since people would be logging in to this account from their home networks, the other accounts they log in with in the same network might be identified with this one?

Yes, Steam uses such stuff for indetification purposes. Of course it's easier to link people by their phone numbers for example, but that doesn't mean you can't link through machineID, and SK2 announces itself with everything that Valve may potentially need to go on a hunt.

I didn't say that it's bound to happen, I just say that somebody might abuse your generosity, log in to that account, do stuff you're definitely not fine with (like buying goods with stolen CCs, money laundering, vac cheating) and it might affect other people who were identified linked to that account in the past.

(Not to mention that sharing accounts in **any** form is against Steam ToS and grounds for suspension by alone that fact, regardless of abuse of other people)

**Comment by oxters168** [comment]
I see that's unfortunate, so that solution is out the window. I was also thinking of another solution, but I don't think it will be possible. I was thinking that as the anonymous account I can try adding csgo to the library then use that to be able to communicate to the GC. I searched for how to "purchase" items using SteamKit, but from what I could gather it has to be done through the web store or something?

**Comment by JustArchi** [comment]
CS:GO is free, you can just ask for license 730. If you need code example, check my ASF and `addlicense` command but it's just fancy wrapper over `SteamApps.RequestFreeLicense`.

Whether it will work or not on anonymous account is entirely different thing (probably not, but I've never tried it before).

**Comment by oxters168** [comment]
I'm using another library called DepotDownloader, it uses RequestFreeLicense. When I asked it download csgo files (730), I don't remember the exact error but it was something along the lines of denied. So to download csgo files I used instead the dedicated server (740), that was an idea from a redditor. The dedicated server didn't give me any issues when downloading it's files and it has all the csgo files I need. The GC on the other hand, I have no idea how I'm going to get to it.

**Comment by JustArchi** [comment]
You may always ask for Steam credentials of the user, you'll need to implement at least SteamGuard and 2FA (nothing hard, SK2 has examples on that), but the real problem is that users will most likely be sceptical on inputting their account details in your app, even if it's open-source and legit.

I'd do it API way personally. If you can't get license 730 on anonymous account and you need it for communication with the GC then I'm pretty sure there is not much you can do, but hopefully somebody with actual knowledge on GC will correct me here, I just never bothered with it in the past, so I don't know the details.

**Comment by oxters168** [comment]
Actually the first version of the application I released publicly a few days ago. It has logging in to view your matches. It got many comments of skepticism just like you predicted. I don't want anyone that uses my application to feel afraid or hesitant to use it, and there is no way to prove to them their accounts will be safe. The only way is to remove logging in and replace it somehow.

I just tested again RequestFreeLicense through DepotDownloader to remember what error was received. Here is the error:
![FreeLicenseDenied](https://user-images.githubusercontent.com/15348986/68339979-42229300-00ee-11ea-80a4-0f22508504d6.png)

I really appreciate you trying to figure out something with me. Even if we don't reach a solution, thank you.

**Comment by oxters168** [comment]
It seems Steam has a secure log in called OAuth. Does anyone know if I can use that with SteamKit and if logging in with that would let me use the CSGO GameCoordinator?

**Comment by azuisleet** [comment]
GameCoordinator messaging is done through the Steam Client protocol. You cannot use an OAuth session to facilitate a Steam Client connection. Your use case requires logging in as that user.

If you have any other questions, feel free to open a new issue.
