### ISSUE TITLE
Get inventory with SteamKit

### ISSUE THREAD

**Issue by GiaNTizmO** [SteamRE/SteamKit#788]
Hello! How can i get inventory of steam profile?
I try to use webclient with url get to steam api:
http://steamcommunity.com/id/<USERURL>/inventory/json/<APPID>/2
http://steamcommunity.com/profiles/<STEAMID>/inventory/json/<APPID>/2
but i get:
{"success":false,"Error":"This profile is private."}
I think my logging from SteamKit2 not works with C# WebClient.
How can i get inventory, using SteamKit? Can you give example?

**Comment by azuisleet** [comment]
If the user chooses not to share their inventory, you will not be able to retrieve their inventory in any form. There's nothing related to SteamKit here. If you have a more specific question, feel free to open a new issue.
