### ISSUE TITLE
Doesn't call UpdateMachineAuthCallback after a successfull logon

### ISSUE THREAD

**Issue by remozserver** [SteamRE/SteamKit#790]
Hello,
i can't get called by UpdateMachineAuthCallback after a successfull logon on a steamguard (no 2FA) protected account (mail verification code once)

My Code: https://pastebin.com/hAr2TstB

I've double checked my code, and i think this callback method should be called, but doesn't 

Many thanks for help

Bye
Remoz

**Comment by azuisleet** [comment]
In your example, you are already computing the hash of the sentry file when logging in. You only need to perform UpdateMachineAuthCallback upon request. Your successful session, as indicated by providing the hash on login, doesn't need to be updated again.
