### ISSUE TITLE
[Dota2] Create/Launch lobby issue

### ISSUE THREAD

**Issue by worldofsites** [SteamRE/SteamKit#791]
Hi there.
I have a very strange behaviour.
I work with SteamKit2 and with Dota2.
Task: programmatically create a lobby and invite friends.

_How I do it in the game:_
I create a 1x1 lobby with first account, join this lobby from the second account, exit the lobby in the first account and do not join back (or join - no difference), I launch the lobby from the second account, the game starts, everything is fine!

_How I do it with SteamKit2:_
(1) I create a lobby using **CMsgPracticeLobbyCreate** with the same settings as when I do it right in the game.
Now there are two options that both do not work:
(2.1) I join from the second account to the created lobby, then using **CMsgPracticeLobbyLeave** I exit the lobby in the first account, at this moment the lobby rights goes to the second account, I try to start the lobby from the second account, and I get an endless loading -> **FINDING SERVER**.
(2.2) I send a request to **CMsgPracticeLobbyLaunch**, looks like lobby trying to launch, but nothing happens. When I open the dota2, I see the same thing as in point 2.1 -> **FINDING SERVER**.

Update: This is not related to the region.

What is the problem?
Why, performing the same actions using SteamKit2, as in the game, I can’t start the lobby?
I tried different lobby creation ways, but all to no avail.

Thanks.

Screen:
![image](https://user-images.githubusercontent.com/23352829/69328262-859a0700-0c81-11ea-9247-431d70aff5b9.png)

Create/Leave/Launch lobby code:
```
        private void CreateLobby()
        {
            var createLobby =
                new ClientGCMsgProtobuf<CMsgPracticeLobbyCreate>((uint) EDOTAGCMsg.k_EMsgGCPracticeLobbyCreate);

            createLobby.Body.search_key = "STEAMKIT2.DOTA.LOBBY";
            createLobby.Body.lobby_details = new CMsgPracticeLobbySetDetails();
            createLobby.Body.lobby_details.game_mode = (uint) DOTA_GameMode.DOTA_GAMEMODE_1V1MID;
            createLobby.Body.lobby_details.game_name = "STEAMKIT2.DOTA.LOBBY";
            createLobby.Body.lobby_details.visibility = DOTALobbyVisibility.DOTALobbyVisibility_Public;
            createLobby.Body.lobby_details.game_version = DOTAGameVersion.GAME_VERSION_CURRENT;
            createLobby.Body.lobby_details.server_region = 2;
            createLobby.Body.lobby_details.custom_max_players = 2;
            createLobby.Body.lobby_details.intro_mode = false;
            createLobby.Body.lobby_details.lan = false;
            
            _gameCoordinator.Send(createLobby, DOTA_APP_ID);
        }
        
        private void LaunchLobby()
        {
            var launchLobby = new ClientGCMsgProtobuf<CMsgPracticeLobbyLaunch>((uint) EDOTAGCMsg.k_EMsgGCPracticeLobbyLaunch);
            _gameCoordinator.Send(launchLobby, DOTA_APP_ID);
        }
        
        private void LeaveLobby()
        {
            var leaveLobby = new ClientGCMsgProtobuf<CMsgPracticeLobbyLeave>((uint) EDOTAGCMsg.k_EMsgGCPracticeLobbyLeave);
            _gameCoordinator.Send(leaveLobby, DOTA_APP_ID);
        }
```

**Comment by worldofsites** [comment]
**Updates:**
When I use node.js version https://github.com/Arcana/node-dota2 ->
Described case works for the following create/leave lobby code:
```
                Dota2.createPracticeLobby({"game_name": "node-dota2",
                                           "server_region": dota2.ServerRegion.USEAST,
                                           "game_mode": dota2.schema.DOTA_GameMode.DOTA_GAMEMODE_1V1MID,
                                           "series_type": 2,
                                           "game_version": 1,
                                           "allow_cheats": false,
                                           "fill_with_bots": false,
                                           "allow_spectating": true,
                                           "pass_key": "password",
                                           "radiant_series_wins": 0,
                                           "dire_series_wins": 0,
                                           "allchat": true
                                           },
                                           function(err, body){
                                                console.log(JSON.stringify(body));
                                           });

                
                setTimeout(function(){
                    Dota2.leavePracticeLobby(function(err, body){
                        console.log(JSON.stringify(body));
                    });
                }, 60000);
```

**Comment by azuisleet** [comment]
If you are using just SteamKit2, compared to a fully featured GC implementation like node-dota2, you may not be performing all the initialization that is required, such as sending a GamesPlayed to Steam, performing the GCClientHello handshake, and so on. 

We do not support specific game implementations of GC, so you will need to implement it yourself or use a library that has done so (such as node-dota2).
