### ISSUE TITLE
Nethook2, GetMessageList not hooked

### ISSUE THREAD

**Issue by alainhb2000** [SteamRE/SteamKit#794]
The method GetMessageList is not being hooked with the new versions of the Steam Client.

**Comment by yaakov-h** [comment]
Duplicate of #765.

**Comment by MissyBrayan** [comment]
Hola alain,dime com o podemos hablar x priv,enviame tu numero so puedes por whatsapp soy de aqui de la habana de la red snet,soy amigo de osmel (Sirius black) de aqui de la banana..este es Missy whats app 56891656 agregame estoy interest en tu proyecto de steam

**Comment by yaakov-h** [comment]
Fixed by #765.
