### ISSUE TITLE
Submit my own request

### ISSUE THREAD

**Issue by MakcStudio** [SteamRE/SteamKit#799]
How do I submit my own request? I figured out how I need to write the payload field, now I need to somehow send the data I need. The question is related to this topic: https://github.com/SteamRE/SteamKit/issues/798

I added the class in .....\GC\CSGO\SteamMsgGCSDK.cs (in the screenshot)
![image](https://user-images.githubusercontent.com/41212099/69959570-89971600-1518-11ea-801f-e4653fb7c052.png)

and I use it like this, but the name Tag is not cleared. Can I somehow track the requests I send from my app via nethook to see what the difference is?
![image](https://user-images.githubusercontent.com/41212099/69959632-ab909880-1518-11ea-861e-721e2a36980f.png)

**Comment by MakcStudio** [comment]
apparently in payload the ready infa in the necessary format is written, and that I try to make-becomes not so. Someone is anyone doing something like that, I'll wait for advice..

**Comment by MakcStudio** [comment]
Apparently they use the data in that order:

short = 1
ulong.MaxValue
ulong.MaxValue
ulong (item_id)
byte = 0;


I tried doing this, but it didn't help either. The game does not respond to the request
![image](https://user-images.githubusercontent.com/41212099/69968846-56f71880-152c-11ea-88a0-1548896e43e4.png)

**Comment by MakcStudio** [comment]
![image](https://user-images.githubusercontent.com/41212099/69979601-ab57c380-153f-11ea-9066-f51bb508fb6a.png)

Made another overload on the Send method in SteamKit2\Steam\Handlers\SteamGameCoordinator\SteamGameCoordinator.cs and got what it takes

**Comment by TheOnlyRealMoreChok** [comment]
@MakcStudio Can I ask for a more detailed answer on how to solve this problem? Or perhaps there is an example of working code?

This would help me a lot in writing a custom application for obtaining statistics.

**Comment by MakcStudio** [comment]
Sure) have your client email me and I'll sell him a ready-made sticker cleaning program)) telegram: @makcstudio



Отправлено из мобильной Почты Mail.ru


понедельник, 6 ноября 2023 г. в 18:05 +03:00 от ***@***.***  ***@***.***>:
