### ISSUE TITLE
CANT JOIN CSGO LOBBY

### ISSUE THREAD

**Issue by voltexde** [SteamRE/SteamKit#803]
Hello Guys,

My bot can´t join my csgo lobby.

With best regards.

```
JoinLobby();

static void JoinLobby()
        {
           
            var joinRequest = new ClientMsgProtobuf<CMsgClientMMSJoinLobby>(EMsg.ClientMMSJoinLobby);
            joinRequest.ProtoHeader.routing_appid = 730;
            joinRequest.Header.Proto.routing_appid = 730;
            joinRequest.Body.app_id = 730;
            joinRequest.Body.steam_id_lobby = 109775241051578180;
            joinRequest.Body.persona_name = "blabla";
            steamClient.Send(joinRequest);
        }
```

**Comment by azuisleet** [comment]
We don't support specific game implementations of GC. You'll need to use a tool like NetHook to capture the network messages being sent by the game and compare your implementation with what's actually being sent.
https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2
