### ISSUE TITLE
Handler for SteamRichPresence 

### ISSUE THREAD

**Issue by MopsiMauser** [SteamRE/SteamKit#806]
Hello Guys,

I am using SteamKit version 2.2.0 and I am trying to get some information via the Steam Rich Presence interface. But unfortunately I cannot find any handler regarding this Interface (i.e. in node-steam there is a handler called SteamRichPresence ). Am I missing something or is this interface/handler just not implemented in SteamKit?

Best Regards

**Comment by psychonic** [comment]
These are not exposed in the built-in handlers, but you are able to use your own handlers. See https://github.com/SteamRE/SteamKit/tree/master/Samples/2.Extending

**Comment by MopsiMauser** [comment]
Ok, thanks for the fast response.
