### ISSUE TITLE
recalling onfriendslist

### ISSUE THREAD

**Issue by M1XT3NZ** [SteamRE/SteamKit#808]
So I want to recall onfriendslist for example...

static void OnFriendsList(SteamFriends.FriendsListCallback callback) <--

is there any way to recall it on my end? with for example a refresh button?
if there is a way I was probably too blind to find it.

**Comment by azuisleet** [comment]
That callback is sent by Steam, and there is no general refresh method. SteamFriends manages a cache of the friend data, so you can call SteamFriends.GetFriendCount and iterate through SteamFriends.GetFriendByIndex.

**Comment by M1XT3NZ** [comment]
can i even get the online status through that?
If so im stupid. :D

**Comment by azuisleet** [comment]
Once you have a SteamID of interest, you can use the SteamFriends methods `GetFriendPersonaName` `GetFriendPersonaState` `GetFriendRelationship` and so on to query the cached friend data.

**Comment by M1XT3NZ** [comment]
its the cached yeah but not the absolute newest one.
Which is more or less my goal. to kind of always have the newest personastate of the people.

But i can work with this. Thanks again..
