### ISSUE TITLE
CS: GO Prime Status and VAC

### ISSUE THREAD

**Issue by Highlandernt** [SteamRE/SteamKit#812]
Hi. 
SteamKit can get data about the presence of CS: GO Prime Status?
About the level in CS: GO?
About VAC locks on your account?

**Comment by azuisleet** [comment]
I believe Steam sends a ClientVacStatusResponse upon login when an account has been restricted.

I believe the GameCoordinator messages contain the rest of the data you're looking for (and also a VAC status) in the ClientHello message (CMsgGCCStrike15_v2_MatchmakingGC2ClientHello).

SteamKit does not provide game-specific implementations of GC, so you will need to either build the handshake yourself or find a library that implements the GC handshake for you.

**Comment by Highlandernt** [comment]
OK. How do I get ClientHello?

**Comment by S0PEX** [comment]
@azuisleet Hey I dont wanted to create an extra issue for this so I may ask it here.
I am currently creating an SteamKit-CSGO Library which uses this library and I wanted to provide async methods for stuff like @Highlandernt mentioned. Is there a good way of creating an task which will return once the callback manager received the correct message ?
Example:
```c#
// Request data
var requestMatchmakingStats =
  new ClientGCMsgProtobuf<CMsgGCCStrike15_v2_MatchmakingClient2GCHello>((uint) ECsgoGCMsg.k_EMsgGCCStrike15_v2_MatchmakingClient2GCHello);
_gameCoordinator.Send( requestMatchmakingStats , Appid );

// Return await the task until was received ?
ECsgoGCMsg.k_EMsgGCCStrike15_v2_MatchmakingGC2ClientHello 
```

Also I noticed that my request to the gc are handled without the need of sending the hello
```c#
var clientHello = new ClientGCMsgProtobuf<CMsgClientHello>( ( uint)EGCBaseClientMsg.k_EMsgGCClientHello );
            
_gameCoordinator.Send( clientHello, Appid );
```

Is this normal behavior so the hello is only needed for certain requests ?

Regards Artur

**Comment by yaakov-h** [comment]
The specifics of any particular GC client is out of SteamKit's scope.
