### ISSUE TITLE
Allow ignoring SSL errors

### ISSUE THREAD

**Issue by Bluscream** [SteamRE/SteamKit#817]
I have a lot of users that are using uncommon proxies like fiddler and adguard, apparently the library doesn't accept their custom HTTS certificates. Is there currently a way to let the users use the lib without the need of removing these certs from their system and if not could one be implemented?

**Comment by yaakov-h** [comment]
If you're using a proxy that does TLS interception you should probably install the proxy's root certificate.

Otherwise, this can be done via standard .NET mechanisms and isn't the responsibility of SteamKit itself.
