### ISSUE TITLE
AsyncJob from GetLobbyList always times out.

### ISSUE THREAD

**Issue by Tyaap** [SteamRE/SteamKit#824]
When I await the AsyncJob from SteamMatchmaking.GetLobbyList() it always times out and doesn't receive a GetLobbyListCallback. However the client does receive a GetLobbyListCallback, which I can access by registering a function using the CallbackManager.

**Comment by Benjamin-Dobell** [comment]
@Tyaap Are you calling [ConfigureAwait](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.configureawait?view=netframework-4.8)?

**Comment by Tyaap** [comment]
No I'm not. I'm using a similar aproach to SteamKit sample project 9 (which is working for other async jobs, like SteamUser.GetNumberOfCurrentPlayers).

**Comment by Benjamin-Dobell** [comment]
I've reproduced this and verified the cause. PR incoming.
