### ISSUE TITLE
Add support for specifying the source IP address

### ISSUE THREAD

**Issue by glen-84** [SteamRE/SteamKit#83]
We are using SteamBot and we'd like to try using multiple IP addresses, but SteamKit doesn't allow for this.

One example is the use of a WebClient in WebAPI.AsyncInterface. In order for this to work, we'd need to be able to pass an IPAddress to WebAPI.GetInterface(). AsyncInterface would then need to use an HttpWebRequest or a subclassed WebClient (see [here](http://stackoverflow.com/questions/4273462/can-i-send-webrequest-from-specified-ip-address-with-net-framework)).

Thoughts?

**Comment by VoiDeD** [comment]
I think I'm going to close this issue unless there's some legitimate and pressing need to bind to a specific source address.

On the topic of the sessionid cookie, that's definitely only used as a CSRF token, and you can freely pass any values you like (as long as the cookie and request parameter match) so it's not tied to the local IP address of the client at all.
