### ISSUE TITLE
NetHook2 from #804 PR doesn't write any messages

### ISSUE THREAD

**Issue by fantik11** [SteamRE/SteamKit#833]
I can't capture any messages, look like fix from steam.
When I Inject dll, I saw this console
![image](https://user-images.githubusercontent.com/35728123/78734863-0700e600-7952-11ea-8406-f3bbd473493a.png)
But actually if I do any wokr with steam, I'm didn't see any changes in console and got nethook directory empty

When I'm trying to eject nethook, I'm getting this error
![image](https://user-images.githubusercontent.com/35728123/78735090-91494a00-7952-11ea-9b64-73ee39010296.png)

NetHook what I used - https://github.com/SteamRE/SteamKit/pull/804

**Comment by Sen66** [comment]
There was once again another steam update so I think my version is broken at the moment.

**Comment by xPaw** [comment]
Put your message in #804 then, this doesn't belong in a separate issue. And I think #765 still works.
