### ISSUE TITLE
Reset current game players list

### ISSUE THREAD

**Issue by byterussian** [SteamRE/SteamKit#837]
Hello,

it's more a support question that an issue, wasn't able to connect to the irc channel mentioned in the wiki. Feel free to delete if is OT.

I want to get current players list for some game servers, so i'm simulating the connection to a server by sending **ClientGamesPlayed** with game id and server id. Then I listen and process the **ClientPersonaState** event filtering out who is playing another game, is offline ect. Now I'm "jumping" into many servers to collect those informations and I'm starting to have duplicate players after 2/3 jumps. There is something that can help me to have a clean current players list? Maybe is mixing with recent players tab, idk.

Any help appreciated,
Thanks.

**Comment by yaakov-h** [comment]
Closing as stale, but if you're still looking for help try filtering by the `game_` fields.
