### ISSUE TITLE
SteamKit stopped working?

### ISSUE THREAD

**Issue by ogendogen** [SteamRE/SteamKit#842]
I run small bot using SteamKit and it suddenly stopped working few days ago without any code changes for a long time.
So I launched example with DebugLog to verify it and I get following output every time I launch it (ip address changes). No matter if login and password are correct.
https://github.com/SteamRE/SteamKit/blob/master/Samples/3.DebugLog/Program.cs

> Connecting to Steam...
> MyListener - ServerList: Resolving server list
> MyListener - ServerList: Server list provider had no entries, will query SteamDirectory
> MyListener - ServerList: Resolved 200 servers
> MyListener - ServerList: Next server candidiate: 155.133.230.34:27018 (Tcp)
> MyListener - TcpConnection: Connecting to 155.133.230.34:27018...
> MyListener - TcpConnection: Timed out while connecting to 155.133.230.34:27018
> Disconnected from Steam

What's the problem?
My env: Win7 64bit, VS 2019, .NET Core 3.1

**Comment by yaakov-h** [comment]
Internet connection or firewall issues?

**Comment by ogendogen** [comment]
Well, I'm not sure. I tested sample script from python port and I have no problem with connection to the bot account -> https://github.com/ValvePython/steam/blob/master/recipes/1.Login/one_off_login.py Steam clients works fine as well.
I disabled firewall on my router and disabled windows firewall, but still no luck. Any more ideas?

**Comment by rossengeorgiev** [comment]
Is is trying to connect to the same IP every time, or different ones? CM servers occasionally disappear, so you try the next one.

**Comment by ogendogen** [comment]
As I mentioned before, IP and port changes every time I run it. Tried to run it also on other PC's and Raspberry PI (which is my target platform) with same result. I also tried to run it with mobile data from phone to ensure it's not my network issue. Is it global problem or is it just me?

**Comment by rossengeorgiev** [comment]
The issue is on your side. My guess is something is blocking it. Could be on your device, could be on your network. Any chance you are in a country that is blocking Steam? 🤔

**Comment by ogendogen** [comment]
Not really, Poland here ;)

**Comment by xPaw** [comment]
Warsaw CMs have been dead for a couple of days. Steamkit probably keeps selecting these.

**Comment by ogendogen** [comment]
So can I force it to connect to other servers? How? Where can I find IPs?

**Comment by xPaw** [comment]
You can change the cellid in SteamConfiguration to something other than Poland, should help.

**Comment by ogendogen** [comment]
It works, thanks! Can we automate it to prevent such problems in future?
