### ISSUE TITLE
Move Steam message declarations into their own repository

### ISSUE THREAD

**Issue by Plecra** [SteamRE/SteamKit#843]
It was mentioned in https://github.com/SteamRE/SteamKit/issues/793#issuecomment-557824772 that the message declarations in `SteamKit/Resources/SteamLanguage/` are reverse engineered manually from the steam client.

This is an amazing resource, and an invaluable part of making a port of SteamKit to another language or implementation. Would it be possible to isolate the declarations and maintain them in their own repository like https://github.com/SteamDatabase/Protobufs? Keeping them out of tree would make it much easier to setup a webhook for them, and also give contributions to the declarations more visibility (I'd probably want to watch pull requests for them)

**Comment by yaakov-h** [comment]
Considering that these message predate Valve's heavy use of protobuf, and change about once every five years, I don't see the benefit of splitting them or of setting up webhooks.

EMsg itself has moved to protobuf IIRC, and the rest are about as stable as it gets.

**Comment by Plecra** [comment]
Oh I see, those updates are pretty rare :D Do the current declarations cover the whole protocol? I had assumed there were parts left to do, which could be contributed if someone had the chance

**Comment by yaakov-h** [comment]
They cover everything we know about.
