### ISSUE TITLE
NetHookAnalyzer: TypeLoadException

### ISSUE THREAD

**Issue by ram-gopal-rao** [SteamRE/SteamKit#857]
Hello,

I've been trying to solve this issue for a while but had no luck. I get the same exception in my build from master and the one I downloaded from the releases page. Is there something obvious that I'm missing? I'm kind of new to dotnet.

I was able to compile NetHook and it seems to work as expected and so does the version from the releases page.

Please let me know if you have any questions or need any more info.

![2020-06-03 (2)](https://user-images.githubusercontent.com/26553040/83706544-c89c4600-a5e5-11ea-9dce-ef2d44a83b95.png)

Thanks!

**Comment by xPaw** [comment]
Try installing .NET Core 3.0
