### ISSUE TITLE
OAuth2 . How to authorize a bot through Steam?

### ISSUE THREAD

**Issue by Kezzya** [SteamRE/SteamKit#862]
Sorry for question like this, but i am tired of searching this. I need to authorize my bot (which will be selling and buying items) on site (like dmarket.com) through the steam, but how i can do it? I made an authorization in steam network from the sample 5 and thats all.

Thanks.

**Comment by oxters168** [comment]
I asked a question before that eventually led to me asking if I can use oauth to log in with SteamKit. Unfortunately, it's not possible. Here's a [link](https://github.com/SteamRE/SteamKit/issues/785#issuecomment-577379385) to the relevant comment.
