### ISSUE TITLE
Adding read-only properties to access friendsList/clanList in SteamFriends

### ISSUE THREAD

**Issue by Contron** [SteamRE/SteamKit#87]
As it stands, in order to be able to do anything with the list of friends or clans from the SteamFriends handler, you need to manually iterate over the list by using the GetFriendCount/GetFriendByIndex methods.

Is there a particular reason why the lists aren't exposed as public read-only properties, obviously as a read-only list? A wild guess is that it's due to the locking behaviour, but it'd make iterating over friends much easier.

**Comment by VoiDeD** [comment]
The original design of the SteamFriends handler was unfortunately modeled after the internal IClientFriends interface of the actual Steam client.

As it stands, the current GetFriendCount/GetFriendByIndex business is inherently not threadsafe and is likely to encounter race conditions if the friends list is updated during iteration. The same applies to Valve's implementation.

I wanted to get some push towards refactoring the SteamFriends handler entirely, but it'd require some heavy lifting and we'd have to bite the bullet of breaking our consumers. The best advice I normally give anyone who's unhappy about using SteamFriends is to implement their own handler and listen to the friends related network messages directly.

**Comment by Contron** [comment]
Ah, I feared as much to be honest. I suppose I'll just have to continue with the way I'm doing it now and then perhaps drop down to using your method if I need any additional functionality.

Don't worry about the delay - I appreciate you for taking the time to actually explain as to why it's implemented the way it is.
