### ISSUE TITLE
Retrieve user's contact email?

### ISSUE THREAD

**Issue by RadicalRedemption** [SteamRE/SteamKit#871]
Hello, is it possible to retrieve user's contact email or display name once logged into the account using SteamKit2?

**Comment by rossengeorgiev** [comment]
Yes

**Comment by RadicalRedemption** [comment]
> 
> 
> Yes

Can i please get an example?

**Comment by rossengeorgiev** [comment]
`CMsgClientAccountInfo `will give you the `persona_name`
`CMsgClientEmailAddrInfo` has the email

Listen for those messages right after successful login

**Comment by xPaw** [comment]
SteamKit has `SteamUser.EmailAddrInfoCallback`

**Comment by RadicalRedemption** [comment]
ClientMsgProtobuf<CMsgClientEmailAddrInfo> emailAddrInfo = new ClientMsgProtobuf<CMsgClientEmailAddrInfo>(EMsg.ClientEmailAddrInfo);

Something like that?

**Comment by RadicalRedemption** [comment]
> 
> 
> SteamKit has `SteamUser.EmailAddrInfoCallback`

I don't see that.

**Comment by RadicalRedemption** [comment]
> 
> 
> `CMsgClientAccountInfo `will give you the `persona_name`
> `CMsgClientEmailAddrInfo` has the email
> 
> Listen for those messages right after successful login

 ClientMsgProtobuf<CMsgClientEmailAddrInfo> emailAddrInfo = new ClientMsgProtobuf<CMsgClientEmailAddrInfo>(EMsg.ClientEmailAddrInfo);

Something like that? Then i just read emailAddrInfo.Body.email_address, cuz it is emtpy?

**Comment by yaakov-h** [comment]
Use 2.3.0-Beta.2 or higher to get access to EmailAddrInfoCallback.
