### ISSUE TITLE
CDNClient threadpool/async issues

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#89]
Using tasks in my main application, and calling download functions in CDNClient runs into an issue where HttpWebRequest requests are never excuted and simply time out because threadpool is full. @Netshroud will add more details on this.

**Comment by xPaw** [comment]
@yaakov-h This probably no longer deadlocks on .net core, right?

**Comment by yaakov-h** [comment]
If you never block the thread waiting for tasks - except for your `Main` method, of course - then I don't think it can deadlock.

If you block waiting for any tasks, hard to say.

On Windows it should be fine, as the HTTP internals are done through WinHTTP.

On Unix/macOS, it starts a dedicated long-running Task that processes cURL messages. The default Task Scheduler on .NET Framework will start a dedicated thread to process long-running tasks, but I can't find the .NET Core equivalent code for this.

I assume it does something similar but can't say for sure.

**Comment by xPaw** [comment]
I'll close this as there's probably not much SK can do here.
