### ISSUE TITLE
Setting Steam Background

### ISSUE THREAD

**Issue by AndrewF001** [SteamRE/SteamKit#900]
Hello, this is probably a really stupid or easy question but I've spent 15 hours and haven't gotten anywhere. I'm trying to make a programme that will automatically change my profile backgrounds with the newly added backgrounds from the steam summer sale.

I've established a connection using Sample 5 but don't know how to send my protobuf package. I need to use the classes between line 675 - 878 in https://github.com/SteamRE/SteamKit/blob/be82c6c7b558fd9fe7fd1bfc9d19e36c1ef3389a/SteamKit2/SteamKit2/Base/Generated/SteamMsgPlayer.cs .

I have no clue what I'm doing so I don't know if what I want to do is even possible or if I need to use a different tool. Thanks.

**Comment by yaakov-h** [comment]
Check out Sample 8 instead, which demonstrates exactly how to use the IPlayer service.

**Comment by AndrewF001** [comment]
Thanks, I looked at that sample but I forgot to do the manager.subcribe. The sample only shows a getter, is it similar for setter? For setter do I just need to get the current copy then change the appid and then send it back? Also will I need to serialise it my self?

**Comment by yaakov-h** [comment]
There's nothing special about "getters" or "setters", they're all just RPC messages with a request and a response.

SteamKit will manage serialization for you.
