### ISSUE TITLE
simulate a connection to a game server by a bot

### ISSUE THREAD

**Issue by botoboua** [SteamRE/SteamKit#915]
Is it possible for a bot to simulate a connection to the game server ip: port? It is necessary for the server to see that they are trying to connect to it.

**Comment by yaakov-h** [comment]
It is possible, but that is well out of scope of this project. I believe there are others (for some games) that aim to achieve this.

**Comment by botoboua** [comment]
Please give a couple of links to these projects, I've been trying to find a solution myself for a very long time. I would even hire a specialist to do it for me, only I don’t even know where to find such a specialist.
