### ISSUE TITLE
Does this library support depot uploads?

### ISSUE THREAD

**Issue by Qix-** [SteamRE/SteamKit#919]
Does this library support uploading builds to depots?

I'm trying to sift through the code but all of the steam-specific terms are throwing me off.

**Comment by oxters168** [comment]
While I haven't uploaded to depots, I have downloaded. I used [this](https://github.com/SteamRE/DepotDownloader) library to do so, it works in conjunction with SteamKit. If it doesn't have upload capability, I assume you should be able to make a DepotUploader library using SteamKit. Or there might be a DepotUploader library already out there.

**Comment by Qix-** [comment]
Unfortunately that doesn't help - depot downloads are a much different system than depot builds.

**Comment by azuisleet** [comment]
There's likely a lot more effort to support uploads. Given that Steam users aren't normally uploading depots anyway, it's probably not something we can support.

**Comment by Qix-** [comment]
Really wish you could :| `steamcmd` is really terrible, most devs I've talked to all hate using it and have issues when trying to shoehorn it into their development workflows.

**Comment by xPaw** [comment]
Talk to Valve about improving steamcdn then. I don't see why steamkit needs to support that.

**Comment by Qix-** [comment]
> Talk to Valve about improving steamcdn then

The problem isn't steamcdn. The problem is steamcmd. And I have, as well as (I'm sure) many others. Valve isn't exactly the most responsive or helpful company when it comes to this stuff.

**Comment by xPaw** [comment]
> The problem isn't steamcdn. The problem is steamcmd.

Yeah, I typo'd.

> My goal with this issue was asking if SteamKit already did this and the answer is no.

Yeah it doesn't, I'm not entirely sure you even need anything from SK to implement uploading at all (uploads go over http afaik, unsure about the auth).

**Comment by Qix-** [comment]
Okay, I'll take a look. Thanks @xPaw :)
