### ISSUE TITLE
dota_gcmessages_common_match_management is outdate , please update the proto?

### ISSUE THREAD

**Issue by jellyr** [SteamRE/SteamKit#920]
In CSODOTALobby  structure 
it has "CSODOTALobbyMember all_members".  I need to deserilize this structure but the proto is not the latest and I cannot get all the players in the lobby.
Would you please update the proto at "https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/Protobufs/dota_gcmessages_common_match_management.proto" please ?

**Comment by VoiDeD** [comment]
@jellyr our recommendation would be to compile the protos into your own assembly - we're pretty much always behind as game updates move much quicker than our release cycles, so the included protos are more of a nicety (hence also why they're in an `Internal` namespace - we don't provide any guarantees that they'll be up to date or even included in later versions).

**Comment by jellyr** [comment]
Could you please provide the tool and procedure of how to compile the protos into all these cs file.
Becase my way of doing this is like
`protoc-3.13.0-win64.exe -I=../dota/  --csharp_out=../gencsharp/ ../dota/steammessages.proto`
but there are lots of gramma error.
It would be nice if you can provide the tool and procedure .

**Comment by VoiDeD** [comment]
Check out this script that we use for generating the code that's compiled into SK - https://github.com/SteamRE/SteamKit/blob/master/Resources/ProtobufGen/generate-all.ps1. It has a dependency on our `ProtobufGen` tool that's also located in the repo.

**Comment by jellyr** [comment]
Finally I got it worked! Thank you !
