### ISSUE TITLE
nethook2  does not work on the  the lastest version of dota2

### ISSUE THREAD

**Issue by svenmax** [SteamRE/SteamKit#928]
Thanks for this great project, I would like to report a problem, nethook2 does not work on the latest version of dota2, and nothing can be dumped.
when launch dota2 use x64,it prompt this:
https://www.flickr.com/photos/190941432@N07/50574256458/in/dateposted-public
when launch use x86,it prompt this:
https://www.flickr.com/photos/190941432@N07/50574256673/in/dateposted-public

pls fix it,thank u very much.

**Comment by yaakov-h** [comment]
NetHook2 only supports x86, and unless you’re running a game server, needs to be injected into the Steam process, not the game process.

**Comment by svenmax** [comment]
> NetHook2 only supports x86, and unless you’re running a game server, needs to be injected into the Steam process, not the game process.

thanks for answer.but i did dump  something when injected into the dota2.exe few days ago .today i got nothing.

**Comment by svenmax** [comment]
> NetHook2 only supports x86, and unless you’re running a game server, needs to be injected into the Steam process, not the game process.

pls look at this
https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2#injecting-into-other-executables

> NetHook2 supports injecting into any other process that makes use of Steam's networking library. In particular, you can inject NetHook2 into steamcmd.exe, and srcds.exe to dump traffic from those processes.

To do so, simply provide the ID or the name of the process on the command line when injecting. Ex: rundll32 "<Path To NetHook2.dll>",Inject 1234 or rundll32 "<Path To NetHook2.dll>",Inject srcds.exe. When ejecting, be sure to provide the same process ID or name in the command as well.
