### ISSUE TITLE
Help with building nethook2.dll

### ISSUE THREAD

**Issue by X-Gamer** [SteamRE/SteamKit#93]
WhatVersion of Google protobuf and zlib 1.28 will bee needed i testes all from 2.0 to 3.0 of protobuf and at Visual Basic 2013 many errors in the code of nethook2 .

Over 100 errors in the code

Can anyone help.

Is there no download of the nethook2.dll ?

Project is nethook2.sln

Regards

**Comment by Netshroud** [comment]
Regarding protobuf, here's a hint:
https://github.com/SteamRE/SteamKit/blob/master/Resources/NetHook2/NetHook2/steammessages_base.pb.h#L11
Here's another:
https://github.com/SteamRE/SteamKit/blob/master/Resources/NetHook2/SetupDependencies.ps1#L5

Just run SetupDependencies.bat or .ps1 and it should take care of it for you.

**Comment by X-Gamer** [comment]
Thank you. But i find that visual basic had an error it cannot access some files i fixed it
