### ISSUE TITLE
Steam Register / Add games with steamkit ??

### ISSUE THREAD

**Issue by X-Gamer** [SteamRE/SteamKit#94]
How can i register / add games / keys to an Steam Account with steamkit ?

Has anyone already implementet it in steamkit ?

I also looking for it do give our forum users easy free games and so on without getting a key that only the user gets the game and not be gift able.

I look with nethook2 what will be send and get at cd key activatin but i not find in the steamkit how i can send cd key .

We can also write with skype or email or else you want if someone can help.

Or irc or icq

Regards

**Comment by Netshroud** [comment]
See #68, or come on IRC (irc.gamesurge.net/#opensteamworks) to discuss.
