### ISSUE TITLE
Use in C ++

### ISSUE THREAD

**Issue by jojomojo23** [SteamRE/SteamKit#942]
Hello, I have a program written in C ++ that only works when the original Steam is running. I need to teach my program to work with Steam without starting the original Steam, please tell me how to use this resource for my C ++ program. If you do not start the original Steam, then at the execution stage the program swears at SteamAPI_Init (). I do not know C # at all, I ask the project participants to advise me please.

**Comment by yaakov-h** [comment]
We do not support piracy of Steam applications.
