### ISSUE TITLE
steamworks.net + SteamKit2 = is ok?

### ISSUE THREAD

**Issue by jojomojo23** [SteamRE/SteamKit#943]
You probably misunderstood me due to the difficulties of translation. I had to introduce STeamKit2
  and https://github.com/Facepunch/Facepunch.Steamworks/ - should work fine with each other? Sorry if the question is not correct.

And explain in simple language what exactly is your resource for?

**Comment by yaakov-h** [comment]
If you can run that C# library in your C++ application then you should be able to run this C# library in your C++ application.

If you load both at the same time there shouldn't be any conflicts, but they don't talk to each-other.
