### ISSUE TITLE
What's EMsg.AMGetUserGifts for

### ISSUE THREAD

**Issue by WildCard65** [SteamRE/SteamKit#95]
What's EMsg.AMGetUserGifts and how do I use it?

**Comment by Netshroud** [comment]
It looks like an internal Steam message. If so, you can't use it.

**Comment by WildCard65** [comment]
Alright then, is it possible to find out how to make SteamKit2 handle gift notifications which can be useful for SteamBot as a way of recieving steam game donations(for people who tend to accept Steam Games as donations when gifted to bot which idk who would but it's possible).

**Comment by Netshroud** [comment]
It is possibly possible, though I don't know why you'd want a bot that autoaccepts gifts.

**Comment by WildCard65** [comment]
Well, someone on steam wanted me to make some methods to allow a bot to accept/use gifts but I have no way I know of to get giftids.

**Comment by Netshroud** [comment]
As far as I know, aren't gifts all web-based now? Where does SteamKit2 come into this?

**Comment by WildCard65** [comment]
Well the SteamClient recieves a notification when a game gift is recieved plus it brings up the webpage to accept it so A) The Steam Client gets the giftid from notification.

**Comment by Netshroud** [comment]
So NetHook it and see what happens.

**Comment by WildCard65** [comment]
Can I have example on how to?

**Comment by WildCard65** [comment]
How would I go about making steambot handle the UpdateGuestPassList msg

**Comment by WildCard65** [comment]
Solved. I had help on how to use the nethook dll on SteamBot's reddit thread.
