### ISSUE TITLE
NetHook2.dll Unable to hook CWebSocketConnection::BBuildAndAsyncSendFrame: func scan failed.

### ISSUE THREAD

**Issue by ChrisPei** [SteamRE/SteamKit#950]
![image](https://user-images.githubusercontent.com/576229/101438152-ad234680-394c-11eb-8b98-440e8080b072.png)

Steam seems changed somthing, NetHook2.dll will miss some packages when it's in this state.

**Comment by yaakov-h** [comment]
Looks like this was fixed by #951.
