### ISSUE TITLE
How to add a Steam game to your library without downloading? 

### ISSUE THREAD

**Issue by SimonMillerIO** [SteamRE/SteamKit#964]
I need to add some game to the games library without downloading it to the pc, is there a way to do this using Steam2Kit or maybe there is some other library?

**Comment by DoctorMcKay** [comment]
https://github.com/SteamRE/SteamKit/blob/abff0f218284e740b06f28889bb9a35d3ed583a7/SteamKit2/SteamKit2/Steam/Handlers/SteamApps/SteamApps.cs#L311

**Comment by SimonMillerIO** [comment]
> https://github.com/SteamRE/SteamKit/blob/abff0f218284e740b06f28889bb9a35d3ed583a7/SteamKit2/SteamKit2/Steam/Handlers/SteamApps/SteamApps.cs#L311-L321

How can I get AppId and what is AppId?

**Comment by DoctorMcKay** [comment]
It's in the URL of a store page.

**Comment by meet-v** [comment]
Hey guys! So, has this been implemented in the Steam app for non-coders to use? Or we have to code for this work?
