### ISSUE TITLE
How to send guest passes with SteamKit2

### ISSUE THREAD

**Issue by WildCard65** [SteamRE/SteamKit#97]
I got the giftId and AccountID but not what to put into the gifttype?

**Comment by DoctorMcKay** [comment]
This is an issue tracker. For issues with the project. 

It's not a support forum.

**Comment by Netshroud** [comment]
Guest Passes are out of scope of SteamKit - even Steam doesn't handle them itself anymore.

If you're trying to implement it by extending SteamKit, you're on your own.
