### ISSUE TITLE
Unable to hook

### ISSUE THREAD

**Issue by KoruptTinker** [SteamRE/SteamKit#978]
CCrypto::SymmetricEncryptChosenIV = 0x50c629d0
PchMsgNameFromEMsg = 0x50c67340
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x0
CCMInterface::RecvPkt = 0x0
Unable to hook CWebSocketConnection::BBuildAndAsyncSendFrame: func scan failed.
Unable to hook CCMInterface::RecvPkt: func scan failed.
![image](https://user-images.githubusercontent.com/39380117/113998857-170a1900-9877-11eb-8dba-e3a823f8fe54.png)

**Comment by xPaw** [comment]
Download a newer build: https://github.com/SteamRE/SteamKit/actions/runs/710783332#artifacts
