### ISSUE TITLE
Better nethook2 documentation

### ISSUE THREAD

**Issue by VoiDeD** [SteamRE/SteamKit#98]
I've been trying to remind myself to do this for the past few weeks. Lets get it in writing so I can't run away from it.

Essentially, I'm thinking about throwing a readme.md into the NetHook2 directory, and we can direct any questions about usage there.

**Comment by ykim** [comment]
Thank you for making this issue! I've just been looking around to figure out how to compile nethook2 and inject it into steam. Is there an ETA for how long this would take?

In the meantime, are there any specific resources out there to help someone like me in getting nethook2 up and running?

**Comment by WildCard65** [comment]
http://www.reddit.com/r/SteamBot/comments/2rt2fk/how_to_get_gift_notifications/

**Comment by ykim** [comment]
@WildCard65 : Thanks for the quick response! I did exactly what LightJockey did, but I'm having some issues in Windows 8. In particular, I keep on getting "Unable to acquire SeDebug privilege. Make sure you're running as Administrator (elevated)." I've ran the bat file as an administrator, but I seem to be hitting issues. Do you know of a workaround to this?

**Comment by Netshroud** [comment]
Open a new issue for that as it's not directly related to this one.

**Comment by ykim** [comment]
@Netshroud : I actually figured it out. The issue was that I attempted to specify the absolute path in the bat file, which doesn't work exactly. I got it working now! :+1:

**Comment by Netshroud** [comment]
Interesting, I use absolute paths and it works for me.

Can you gist the bat file that wasn't working?

**Comment by VoiDeD** [comment]
Alright, I wrote up the gist of building and usage, should be enough to get anybody started. I figure at some later point I can write something up for the use of NetHookAnalyzer, but it's fairly straight forward itself.

**Comment by ykim** [comment]
@Netshroud : I think I messed up by not putting my path in quotes. I'm not too familiar with Windows command sadly :(

**Comment by Netshroud** [comment]
IIRC, if there's a space in the path then it needs to be quoted. My Windows PC is out of action at the moment, but I think I needed `rundll32.exe "C:\path\to\NetHook2.dll",Inject`. I don't remember if `rundll32.exe "C:\path\to\NetHook2.dll,Inject"` works.
