### ISSUE TITLE
Check account for community ban

### ISSUE THREAD

**Issue by RadicalRedemption** [SteamRE/SteamKit#982]
Hello, is it possible to check with SteamKit2 if an account has community ban or anything like this?

**Comment by rossengeorgiev** [comment]
https://steamapi.xpaw.me/#ISteamUser/GetPlayerBans

**Comment by RadicalRedemption** [comment]
Would you mind giving a little example of the usage if not a problem? Thanks in advance!

**Comment by RadicalRedemption** [comment]
This actually doesn't show community bans as far as realized after trying it out. Is it possible to check for community bans?

**Comment by RadicalRedemption** [comment]
The only alternative i found so far is to print PersonaName and to see if the name is the account's SteamID64.
