### ISSUE TITLE
Hsteampipe

### ISSUE THREAD

**Issue by promo55** [SteamRE/SteamKit#984]
How can I get the hsteampipe id? Analogue of SteamAPI_GetHSteamPipe () in OSW.

**Comment by m4dEngi** [comment]
In OSW you need to implement this method by yourself. And it's not related to steamkit.

**Comment by promo55** [comment]
In osw, I have HSteamPipe hSteamPipe = SteamAPI_GetHSteamPipe (). I am wondering if there is a similar implementation in steamkit2

**Comment by psychonic** [comment]
No. SteamKit does not interact with the local Steam client instance.
