### ISSUE TITLE
Send comment

### ISSUE THREAD

**Issue by ScubOFC** [SteamRE/SteamKit#986]
Hello , I am writing steam bot and I am want know , can I send comment to steam profile or not ?

**Comment by VoiDeD** [comment]
SteamKit doesn't implement any functionality to leave comments on Steam profiles. That's generally done through the website via ajax calls - so [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0) and friends is likely what you want to start with.
