### ISSUE TITLE
Message through proxy

### ISSUE THREAD

**Issue by ScubOFC** [SteamRE/SteamKit#987]
Hello , I have one more question, how I can send message through proxy ,
so that there is no loss in sending?

**Comment by VoiDeD** [comment]
Can you provide more details for what you're trying to do?

**Comment by ScubOFC** [comment]
I want to cheat messages and it worked for 1 account for about 50 million and it stopped working, I tried send on another account, it worked clocked 10 thousand and now everything winds up by 20 and everything stops
if (callback.Message.Contains("spam"))
                {
                   
                   
                    Console.WriteLine("Write id: ");
                    string id = Console.ReadLine();


                    try
                    {

                       
                        int i = 0;
                        Console.WriteLine("Write count: ");
                        string  valueRandom = Console.ReadLine();
                        while (i <= Convert.ToInt64(valueRandom) - 1) // рондомайзер числа -1 нужен для точного числа который пользователь написал
                        {
                            Random randValue = new Random();
                            long val = firstValue + randValue.Next(secondValue);
                           // Console.WriteLine(val);
                           
                            steamFriends.SendChatMessage(new SteamID((ulong)Convert.ToInt64(id)), EChatEntryType.ChatMsg, val.ToString());
                            i++;
                           
                        }
                    }
                    catch
                    {
                        steamFriends.SendChatMessage(new SteamID(id), EChatEntryType.ChatMsg, "Непредвиденая ошибка!");
                    }
                }

**Comment by yaakov-h** [comment]
I would expect some server-side protections are kicking in for a function that is quite clearly labelled `spamMe`... I would suggest not to do that.

**Comment by ScubOFC** [comment]
![image](https://user-images.githubusercontent.com/76676664/119483038-3c86af80-bd5d-11eb-9712-a41a5917de63.png)
but it was working , why its not working now?

**Comment by VoiDeD** [comment]
Likely only Valve would be able to provide an answer with regards to their rate limiting methods.

That said, this type of thing is why we don't have support for proxying connections to Steam. Spamming and abuse aren't use cases that we support. See also https://github.com/SteamRE/SteamKit/issues/587#issuecomment-412677406.
