### ISSUE TITLE
Add issue templates to this repository

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#988]
One of the things that can be done is adding a link to discussions.

Half of the issues created here today are more suited for discussions.

GitHub also allows creating custom issue forms (e.g. asking for version), but that might still be in beta. Take a look at: https://github.com/SteamDatabase/ValveResourceFormat/issues/new/choose

Some ideas:
1. Issue report for SteamKit
2. Issue report for NetHook (one of the things that can be mentioned in it "did you try latest CI build?")
3. Feature request
4. Link to discussions
5. Link to irc

**Comment by yaakov-h** [comment]
Done in #999 and fixed in subsequent commits.
