### ISSUE TITLE
Update nethook2

### ISSUE THREAD

**Issue by NapasP** [SteamRE/SteamKit#994]
![steam_meXOEeTaZ2](https://user-images.githubusercontent.com/25374993/121773746-7ee62400-cb86-11eb-99b3-b49ccab286b5.png)

**Comment by NapasP** [comment]
New

```
const bool bFoundBuildFunc = steamClientScan.FindFunction(
        "\x55\x8B\xEC\x83\xEC\x70\xA1\x2A\x2A\x2A\x2A\x53",
        "xxxxxxx????x",
        (void **)&pBuildFunc
    );

const bool bFoundRecvPktFunc = steamClientScan.FindFunction(
        "\x55\x8B\xEC\x81\xEC\xA8\x05\x00\x00\xA1",
        "xxxxxxxxxx",
        (void **)&pRecvPktFunc
    );
```

**Comment by yaakov-h** [comment]
Thanks.

Do you have the new values for [`PchMsgNameFromEMsg`](https://github.com/SteamRE/SteamKit/blob/12d90d60ba613c2c7139662252ae9980eb959a62/Resources/NetHook2/NetHook2/crypto.cpp#L42-L46) as well?

**Comment by m4dEngi** [comment]
![Screenshot_2021-06-13_22-17-13](https://user-images.githubusercontent.com/8540109/121819335-29e50380-cc95-11eb-9f88-e062fac7effd.png)
Are those signatures for beta client?

**Comment by m4dEngi** [comment]
```	
const bool bPchMsgNameFromEMsg = steamClientScan.FindFunction(
		"\x55\x8B\xEC\x51\xA1\x00\x00\x00\x00\xA8\x01\x75\x1F",
		"xxxxx????xxxx",
		(void **)&PchMsgNameFromEMsg
	);
```

**Comment by yaakov-h** [comment]
It seems to work for me, though my Steam client isn't triggering message 9803.

If I explicitly call `PcgMsgNameFromEMsg((EMsg)9803)` I get back the string "Unknown", rather than some weird memory overrun.

![image](https://user-images.githubusercontent.com/426009/121830882-7407cc80-cd09-11eb-9019-749efaa7cb03.png)

What version of Steam are you running?

**Comment by m4dEngi** [comment]
Same version. Probably just a glitch caused by debug build and attached debugger. Couldn't reproduce it with release build.
